// frameworks/svelte/apps/router/src/components/LoadingSkeleton.svelte
<script lang="ts">
  interface Props {
    lines?: number;
    showBlock?: boolean;
  }

  let { lines = 5, showBlock = false }: Props = $props();

  let lineArray = $derived(Array.from({ length: lines }, (_, i) => i));
</script>

<div>
  {#if showBlock}
    <div class="skeleton skeleton-block"></div>
  {/if}
  {#each lineArray as i (i)}
    <div class="skeleton skeleton-line" style="width: {i === lines - 1 ? '60%' : '100%'};"></div>
  {/each}
</div>

// frameworks/vue/apps/router/src/components/LoadingSkeleton.vue
<script setup lang="ts">
interface Props {
  lines?: number;
  showBlock?: boolean;
}

withDefaults(defineProps<Props>(), {
  lines: 5,
  showBlock: true,
});
</script>

<template>
  <div>
    <div v-if="showBlock" class="skeleton skeleton-block"></div>
    <div
      v-for="i in lines"
      :key="i"
      class="skeleton skeleton-line"
      :style="{ width: i === lines ? '60%' : '100%' }"
    ></div>
  </div>
</template>
