// frameworks/angular/apps/router/src/app/components/sidebar/sidebar.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [RouterLink, RouterLinkActive],
  template: `
    <aside class="sidebar">
      <div class="sidebar-brand">Angular Bench</div>
      <nav>
        <a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }">Home</a>
        <a routerLink="/dashboard" routerLinkActive="active">Dashboard</a>
        <a routerLink="/table" routerLinkActive="active">Table</a>
        <a routerLink="/form" routerLinkActive="active">Form</a>
        <a routerLink="/profile" routerLinkActive="active">Profile</a>
        <a routerLink="/settings" routerLinkActive="active">Settings</a>
        <a routerLink="/notifications" routerLinkActive="active">Notifications</a>
        <a routerLink="/search" routerLinkActive="active">Search</a>
        <a routerLink="/about" routerLinkActive="active">About</a>
        @if (authService.isAuthenticated()) {
          <a (click)="authService.logout()" style="cursor: pointer;">Logout</a>
        }
      </nav>
    </aside>
  `,
})
export class SidebarComponent {
  constructor(public authService: AuthService) {}
}

// frameworks/vue/apps/router/src/components/Sidebar.vue
<script setup lang="ts">
import { isAuthenticated, logout } from '../auth';

const navLinks = [
  { path: '/', label: 'Home' },
  { path: '/dashboard', label: 'Dashboard' },
  { path: '/table', label: 'Table' },
  { path: '/form', label: 'Form' },
  { path: '/profile', label: 'Profile' },
  { path: '/settings', label: 'Settings' },
  { path: '/notifications', label: 'Notifications' },
  { path: '/search', label: 'Search' },
  { path: '/about', label: 'About' },
];
</script>

<template>
  <aside class="sidebar">
    <div class="sidebar-brand">Vue Router</div>
    <nav>
      <router-link
        v-for="link in navLinks"
        :key="link.path"
        :to="link.path"
        :active-class="link.path === '/' ? '' : 'active'"
        exact-active-class="active"
      >
        {{ link.label }}
      </router-link>
    </nav>
    <div style="padding: 16px; margin-top: auto; border-top: 1px solid var(--color-border)">
      <template v-if="isAuthenticated">
        <button class="secondary" style="width: 100%" @click="logout">
          Logout
        </button>
      </template>
      <template v-else>
        <router-link to="/login">
          <button class="secondary" style="width: 100%">Login</button>
        </router-link>
      </template>
    </div>
  </aside>
</template>
