// frameworks/vue/apps/dashboard/src/components/DashboardTable.vue
<script setup lang="ts">
interface Props {
  data: number[][];
  flashingCells: Set<string>;
}

defineProps<Props>();
</script>

<template>
  <div style="overflow: auto; flex: 1">
    <table class="dashboard-table">
      <tbody>
        <tr v-for="(row, rowIndex) in data" :key="rowIndex">
          <td
            v-for="(cell, colIndex) in row"
            :key="colIndex"
            :class="{ flash: flashingCells.has(`${rowIndex}-${colIndex}`) }"
          >
            {{ cell }}
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

// frameworks/svelte/apps/dashboard/src/components/DashboardTable.svelte
<script lang="ts">
  interface Props {
    data: number[][];
    flashCells: Set<string>;
  }

  let { data, flashCells }: Props = $props();

  function shouldFlash(row: number, col: number): boolean {
    return flashCells.has(`${row}-${col}`);
  }
</script>

<div class="widget" style="overflow-y: auto;">
  <div class="widget-title">Live Table</div>
  <table class="dashboard-table">
    <tbody>
      {#each data as row, rowIndex (rowIndex)}
        <tr>
          {#each row as cell, colIndex (colIndex)}
            <td class:flash={shouldFlash(rowIndex, colIndex)}>
              {cell}
            </td>
          {/each}
        </tr>
      {/each}
    </tbody>
  </table>
</div>
