// frameworks/react/apps/dashboard/src/components/DashboardTable.tsx
interface DashboardTableProps {
  rows: number[][];
  flashCells: Set<string>;
}

export default function DashboardTable({ rows, flashCells }: DashboardTableProps) {
  return (
    <div className="widget" style={{ overflow: 'auto' }}>
      <div className="widget-title">Data Table</div>
      <table className="dashboard-table">
        <tbody>
          {rows.map((row, rowIdx) => (
            <tr key={rowIdx}>
              {row.map((cell, colIdx) => (
                <td
                  key={colIdx}
                  className={flashCells.has(`${rowIdx}-${colIdx}`) ? 'flash' : ''}
                >
                  {cell.toLocaleString()}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// frameworks/svelte/apps/dashboard/src/components/DashboardTable.svelte
<script lang="ts">
  interface Props {
    data: number[][];
    flashCells: Set<string>;
  }

  let { data, flashCells }: Props = $props();

  function shouldFlash(row: number, col: number): boolean {
    return flashCells.has(`${row}-${col}`);
  }
</script>

<div class="widget" style="overflow-y: auto;">
  <div class="widget-title">Live Table</div>
  <table class="dashboard-table">
    <tbody>
      {#each data as row, rowIndex (rowIndex)}
        <tr>
          {#each row as cell, colIndex (colIndex)}
            <td class:flash={shouldFlash(rowIndex, colIndex)}>
              {cell}
            </td>
          {/each}
        </tr>
      {/each}
    </tbody>
  </table>
</div>
