// frameworks/react/apps/dashboard/src/components/KpiCard.tsx
interface KpiCardProps {
  title: string;
  value: number;
  delta: number;
}

export default function KpiCard({ title, value, delta }: KpiCardProps) {
  const isPositive = delta >= 0;
  const arrow = isPositive ? '\u2191' : '\u2193';
  const percentage = value !== 0 ? ((delta / Math.abs(value - delta)) * 100).toFixed(1) : '0.0';

  return (
    <div className="widget kpi-card">
      <div className="widget-title">{title}</div>
      <div className="kpi-value">{value.toLocaleString()}</div>
      <div className={`kpi-delta ${isPositive ? 'positive' : 'negative'}`}>
        {arrow} {Math.abs(delta).toLocaleString()} ({isPositive ? '+' : ''}{percentage}%)
      </div>
    </div>
  );
}

// frameworks/svelte/apps/dashboard/src/components/KpiCard.svelte
<script lang="ts">
  interface Props {
    title: string;
    value: number;
    delta: number;
  }

  let { title, value, delta }: Props = $props();

  let deltaClass = $derived(delta >= 0 ? 'positive' : 'negative');
  let deltaArrow = $derived(delta >= 0 ? '\u2191' : '\u2193');
  let deltaPercent = $derived(
    value !== 0 ? ((Math.abs(delta) / Math.abs(value)) * 100).toFixed(1) : '0.0'
  );
</script>

<div class="widget kpi-card">
  <div class="widget-title">{title}</div>
  <div class="kpi-value">{value.toLocaleString()}</div>
  <div class="kpi-delta {deltaClass}">
    {deltaArrow} {Math.abs(delta).toLocaleString()} ({deltaPercent}%)
  </div>
</div>
