// frameworks/react/apps/dashboard/src/components/StatusGrid.tsx
interface StatusGridProps {
  cells: string[];
}

export default function StatusGrid({ cells }: StatusGridProps) {
  return (
    <div className="widget">
      <div className="widget-title">Status Grid</div>
      <div className="status-grid">
        {cells.map((status, i) => (
          <div key={i} className={`status-cell ${status}`} />
        ))}
      </div>
    </div>
  );
}

// frameworks/svelte/apps/dashboard/src/components/StatusGrid.svelte
<script lang="ts">
  import type { StatusUpdate } from 'shared-data';

  interface Props {
    cells: StatusUpdate['status'][];
  }

  let { cells }: Props = $props();
</script>

<div class="widget">
  <div class="widget-title">Status Grid</div>
  <div class="status-grid">
    {#each cells as status, i (i)}
      <div class="status-cell {status}"></div>
    {/each}
  </div>
</div>
