// frameworks/svelte/apps/router/src/pages/Form.svelte
<script lang="ts">
  import { formSchema } from 'shared-data';
  import type { FormField } from 'shared-data';

  let formValues = $state<Record<string, string | boolean>>({});
  let errors = $state<Record<string, string>>({});
  let submitted = $state(false);
  let submitResult = $state<string | null>(null);

  // Initialize defaults
  for (const field of formSchema.fields) {
    if (field.defaultValue !== undefined) {
      formValues[field.name] = field.defaultValue;
    } else if (field.type === 'checkbox') {
      formValues[field.name] = false;
    } else {
      formValues[field.name] = '';
    }
  }

  function isFieldVisible(field: FormField): boolean {
    if (!field.condition) return true;
    return formValues[field.condition.dependsOn] === field.condition.value;
  }

  function validateField(field: FormField, value: string | boolean): string | null {
    if (!isFieldVisible(field)) return null;
    for (const rule of field.validation) {
      const strVal = typeof value === 'boolean' ? '' : (value ?? '');
      if (rule.type === 'required') {
        if (field.type === 'checkbox' && !value) return rule.message;
        else if (field.type !== 'checkbox' && !strVal.trim()) return rule.message;
      }
      if (rule.type === 'minLength' && typeof rule.value === 'number' && strVal.length > 0 && strVal.length < rule.value) return rule.message;
      if (rule.type === 'maxLength' && typeof rule.value === 'number' && strVal.length > rule.value) return rule.message;
      if (rule.type === 'pattern' && typeof rule.value === 'string' && strVal.length > 0 && !new RegExp(rule.value).test(strVal)) return rule.message;
    }
    return null;
  }

  function handleChange(name: string, value: string | boolean) {
    formValues = { ...formValues, [name]: value };
    if (submitted) {
      const field = formSchema.fields.find((f) => f.name === name);
      if (field) {
        const err = validateField(field, value);
        const ne = { ...errors };
        if (err) ne[name] = err;
        else delete ne[name];
        errors = ne;
      }
    }
  }

  function handleBlur(name: string) {
    const field = formSchema.fields.find((f) => f.name === name);
    if (field) {
      const err = validateField(field, formValues[name]);
      const ne = { ...errors };
      if (err) ne[name] = err;
      else delete ne[name];
      errors = ne;
    }
  }

  function handleSubmit() {
    submitted = true;
    const ne: Record<string, string> = {};
    for (const field of formSchema.fields) {
      const err = validateField(field, formValues[field.name]);
      if (err) ne[field.name] = err;
    }
    errors = ne;
    if (Object.keys(ne).length === 0) {
      submitResult = JSON.stringify(formValues, null, 2);
    }
  }

  function handleReset() {
    for (const field of formSchema.fields) {
      if (field.defaultValue !== undefined) formValues[field.name] = field.defaultValue;
      else if (field.type === 'checkbox') formValues[field.name] = false;
      else formValues[field.name] = '';
    }
    formValues = { ...formValues };
    errors = {};
    submitted = false;
    submitResult = null;
  }

  let visibleFields = $derived(formSchema.fields.filter(isFieldVisible));
</script>

<div class="page-header">
  <h1>Form</h1>
  <p>Dynamic form with validation and conditional fields.</p>
</div>

{#if Object.keys(errors).length > 0 && submitted}
  <div class="error-summary">
    <h3>Please fix the following errors:</h3>
    <ul>
      {#each Object.entries(errors) as [field, msg] (field)}
        <li><a href="#field-{field}">{msg}</a></li>
      {/each}
    </ul>
  </div>
{/if}

<form
  class="form-container"
  style="padding: 0;"
  onsubmit={(e: Event) => { e.preventDefault(); handleSubmit(); }}
>
  {#each visibleFields as field (field.name)}
    <div class="form-group" id="field-{field.name}">
      {#if field.type === 'checkbox'}
        <div class="checkbox-group">
          <label>
            <input
              type="checkbox"
              checked={!!formValues[field.name]}
              onchange={(e: Event) => handleChange(field.name, (e.target as HTMLInputElement).checked)}
              onblur={() => handleBlur(field.name)}
            />
            {field.label}
          </label>
        </div>
      {:else if field.type === 'radio'}
        <label>{field.label}</label>
        <div class="radio-group">
          {#each field.options ?? [] as opt (opt.value)}
            <label>
              <input
                type="radio"
                name={field.name}
                value={opt.value}
                checked={formValues[field.name] === opt.value}
                onchange={(e: Event) => handleChange(field.name, (e.target as HTMLInputElement).value)}
                onblur={() => handleBlur(field.name)}
              />
              {opt.label}
            </label>
          {/each}
        </div>
      {:else if field.type === 'select'}
        <label for={field.name}>{field.label}</label>
        <select
          id={field.name}
          value={typeof formValues[field.name] === 'string' ? formValues[field.name] : ''}
          class:invalid={!!errors[field.name]}
          onchange={(e: Event) => handleChange(field.name, (e.target as HTMLSelectElement).value)}
          onblur={() => handleBlur(field.name)}
        >
          <option value="">-- Select --</option>
          {#each field.options ?? [] as opt (opt.value)}
            <option value={opt.value}>{opt.label}</option>
          {/each}
        </select>
      {:else if field.type === 'textarea'}
        <label for={field.name}>{field.label}</label>
        <textarea
          id={field.name}
          placeholder={field.placeholder}
          value={typeof formValues[field.name] === 'string' ? formValues[field.name] : ''}
          class:invalid={!!errors[field.name]}
          oninput={(e: Event) => handleChange(field.name, (e.target as HTMLTextAreaElement).value)}
          onblur={() => handleBlur(field.name)}
        ></textarea>
      {:else if field.type === 'date'}
        <label for={field.name}>{field.label}</label>
        <input
          type="date"
          id={field.name}
          value={typeof formValues[field.name] === 'string' ? formValues[field.name] : ''}
          class:invalid={!!errors[field.name]}
          oninput={(e: Event) => handleChange(field.name, (e.target as HTMLInputElement).value)}
          onblur={() => handleBlur(field.name)}
        />
      {:else if field.type === 'file'}
        <label for={field.name}>{field.label}</label>
        <input
          type="file"
          id={field.name}
          class:invalid={!!errors[field.name]}
          onchange={(e: Event) => {
            const file = (e.target as HTMLInputElement).files?.[0];
            handleChange(field.name, file ? file.name : '');
          }}
          onblur={() => handleBlur(field.name)}
        />
      {:else}
        <label for={field.name}>{field.label}</label>
        <input
          type="text"
          id={field.name}
          placeholder={field.placeholder}
          value={typeof formValues[field.name] === 'string' ? formValues[field.name] : ''}
          class:invalid={!!errors[field.name]}
          oninput={(e: Event) => handleChange(field.name, (e.target as HTMLInputElement).value)}
          onblur={() => handleBlur(field.name)}
        />
      {/if}

      {#if errors[field.name]}
        <div class="error-message">{errors[field.name]}</div>
      {/if}
    </div>
  {/each}

  <div class="form-actions">
    <button type="submit">Submit</button>
    <button type="button" class="secondary" onclick={handleReset}>Reset</button>
  </div>
</form>

{#if submitResult}
  <div class="submit-result">
    <pre>{submitResult}</pre>
  </div>
{/if}

// frameworks/react/apps/router/src/pages/Form.tsx
import { useState, useCallback } from 'react';
import { formSchema } from 'shared-data';
import type { FormField, ValidationRule } from 'shared-data';

function getInitialValues(): Record<string, string | boolean> {
  const values: Record<string, string | boolean> = {};
  for (const field of formSchema.fields) {
    values[field.name] = field.type === 'checkbox' ? (field.defaultValue ?? false) : ((field.defaultValue as string) ?? '');
  }
  return values;
}

function validateField(value: string | boolean, rules: ValidationRule[]): string | null {
  for (const rule of rules) {
    const strValue = typeof value === 'boolean' ? '' : value;
    switch (rule.type) {
      case 'required':
        if (typeof value === 'boolean' ? !value : !strValue.trim()) return rule.message;
        break;
      case 'minLength':
        if (strValue.length > 0 && strValue.length < (rule.value as number)) return rule.message;
        break;
      case 'maxLength':
        if (strValue.length > (rule.value as number)) return rule.message;
        break;
      case 'pattern':
      case 'custom':
        if (strValue.length > 0 && !new RegExp(rule.value as string).test(strValue)) return rule.message;
        break;
    }
  }
  return null;
}

function isVisible(field: FormField, values: Record<string, string | boolean>): boolean {
  if (!field.condition) return true;
  return values[field.condition.dependsOn] === field.condition.value;
}

export default function Form() {
  const [values, setValues] = useState(getInitialValues);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [touched, setTouched] = useState<Set<string>>(new Set());
  const [submitted, setSubmitted] = useState<string | null>(null);

  const handleChange = useCallback((name: string, value: string | boolean) => {
    setValues((prev) => ({ ...prev, [name]: value }));
    setSubmitted(null);
  }, []);

  const handleBlur = useCallback(
    (name: string) => {
      setTouched((prev) => new Set(prev).add(name));
      const field = formSchema.fields.find((f) => f.name === name);
      if (field && isVisible(field, values)) {
        const error = validateField(values[name], field.validation);
        setErrors((prev) => {
          const next = { ...prev };
          if (error) next[name] = error;
          else delete next[name];
          return next;
        });
      }
    },
    [values]
  );

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const newErrors: Record<string, string> = {};
    for (const field of formSchema.fields) {
      if (!isVisible(field, values)) continue;
      const error = validateField(values[field.name], field.validation);
      if (error) newErrors[field.name] = error;
    }
    setErrors(newErrors);
    const allTouched = new Set<string>();
    formSchema.fields.forEach((f) => allTouched.add(f.name));
    setTouched(allTouched);

    if (Object.keys(newErrors).length === 0) {
      setSubmitted(JSON.stringify(values, null, 2));
    }
  };

  const visibleFields = formSchema.fields.filter((f) => isVisible(f, values));

  return (
    <div>
      <div className="page-header">
        <h1>Form</h1>
        <p>Dynamic form with validation (simplified for router app)</p>
      </div>

      <form onSubmit={handleSubmit} noValidate style={{ maxWidth: '600px' }}>
        {visibleFields.slice(0, 15).map((field) => {
          const hasError = touched.has(field.name) && !!errors[field.name];
          const id = `field-${field.name}`;

          if (field.type === 'checkbox') {
            return (
              <div className="form-group" key={field.name}>
                <label>
                  <input
                    type="checkbox"
                    checked={values[field.name] as boolean}
                    onChange={(e) => handleChange(field.name, e.target.checked)}
                    onBlur={() => handleBlur(field.name)}
                  />
                  {' '}{field.label}
                </label>
                {hasError && <div className="error-message">{errors[field.name]}</div>}
              </div>
            );
          }

          if (field.type === 'select') {
            return (
              <div className="form-group" key={field.name}>
                <label htmlFor={id}>{field.label}</label>
                <select
                  id={id}
                  value={values[field.name] as string}
                  className={hasError ? 'invalid' : ''}
                  onChange={(e) => handleChange(field.name, e.target.value)}
                  onBlur={() => handleBlur(field.name)}
                >
                  <option value="">-- Select --</option>
                  {field.options?.map((opt) => (
                    <option key={opt.value} value={opt.value}>{opt.label}</option>
                  ))}
                </select>
                {hasError && <div className="error-message">{errors[field.name]}</div>}
              </div>
            );
          }

          if (field.type === 'radio') {
            return (
              <div className="form-group" key={field.name}>
                <label>{field.label}</label>
                <div className="radio-group">
                  {field.options?.map((opt) => (
                    <label key={opt.value}>
                      <input
                        type="radio"
                        name={field.name}
                        value={opt.value}
                        checked={values[field.name] === opt.value}
                        onChange={(e) => handleChange(field.name, e.target.value)}
                        onBlur={() => handleBlur(field.name)}
                      />
                      {opt.label}
                    </label>
                  ))}
                </div>
                {hasError && <div className="error-message">{errors[field.name]}</div>}
              </div>
            );
          }

          return (
            <div className="form-group" key={field.name}>
              <label htmlFor={id}>{field.label}</label>
              {field.type === 'textarea' ? (
                <textarea
                  id={id}
                  value={values[field.name] as string}
                  placeholder={field.placeholder}
                  className={hasError ? 'invalid' : ''}
                  onChange={(e) => handleChange(field.name, e.target.value)}
                  onBlur={() => handleBlur(field.name)}
                />
              ) : (
                <input
                  type={field.type === 'date' ? 'date' : 'text'}
                  id={id}
                  value={values[field.name] as string}
                  placeholder={field.placeholder}
                  className={hasError ? 'invalid' : ''}
                  onChange={(e) => handleChange(field.name, e.target.value)}
                  onBlur={() => handleBlur(field.name)}
                />
              )}
              {hasError && <div className="error-message">{errors[field.name]}</div>}
            </div>
          );
        })}

        <div className="form-actions">
          <button type="submit">Submit</button>
          <button
            type="button"
            className="secondary"
            onClick={() => {
              setValues(getInitialValues());
              setErrors({});
              setTouched(new Set());
              setSubmitted(null);
            }}
          >
            Reset
          </button>
        </div>
      </form>

      {submitted && (
        <div className="submit-result">
          <h3 style={{ marginBottom: '8px' }}>Submitted:</h3>
          <pre>{submitted}</pre>
        </div>
      )}
    </div>
  );
}
