// frameworks/vue/apps/router/src/pages/NotFound.vue
<script setup lang="ts">
</script>

<template>
  <div style="text-align: center; padding-top: 80px">
    <h1 style="font-size: 4rem; font-weight: 700; color: var(--color-text-muted)">
      404
    </h1>
    <p style="font-size: 1.2rem; color: var(--color-text-secondary); margin: 12px 0 24px">
      Page not found
    </p>
    <router-link to="/">
      <button>Go Home</button>
    </router-link>
  </div>
</template>

// frameworks/react/apps/router/src/pages/NotFound.tsx
import { Link } from 'react-router-dom';

export default function NotFound() {
  return (
    <div style={{ textAlign: 'center', paddingTop: '80px' }}>
      <h1 style={{ fontSize: '4rem', marginBottom: '8px' }}>404</h1>
      <p style={{ color: 'var(--color-text-secondary)', marginBottom: '24px' }}>
        Page not found
      </p>
      <Link to="/">
        <button>Go Home</button>
      </Link>
    </div>
  );
}
