// frameworks/angular/apps/router/src/app/pages/notifications.component.ts
import { Component, signal, OnInit } from '@angular/core';
import { LoadingSkeletonComponent } from '../components/loading-skeleton/loading-skeleton.component';
import { createMockApi } from 'shared-data';

interface Notification {
  id: number;
  message: string;
  read: boolean;
}

@Component({
  selector: 'app-notifications',
  standalone: true,
  imports: [LoadingSkeletonComponent],
  template: `
    <div class="page-header">
      <h1>Notifications</h1>
      <p>{{ notifications().length }} notifications ({{ unreadCount() }} unread)</p>
    </div>

    @if (loading()) {
      <app-loading-skeleton></app-loading-skeleton>
    } @else {
      <div class="notification-list">
        @for (n of notifications(); track n.id) {
          <div
            class="notification-item"
            [class.unread]="!n.read"
            (click)="markRead(n)"
          >
            {{ n.message }}
          </div>
        }
      </div>
    }
  `,
})
export class NotificationsComponent implements OnInit {
  readonly loading = signal(true);
  readonly notifications = signal<Notification[]>([]);

  get unreadCount(): () => number {
    return () => this.notifications().filter((n) => !n.read).length;
  }

  ngOnInit(): void {
    const api = createMockApi(50);
    api.fetchNotifications(500).then((res) => {
      this.notifications.set(res.data);
      this.loading.set(false);
    });
  }

  markRead(notification: Notification): void {
    this.notifications.update((list) =>
      list.map((n) => (n.id === notification.id ? { ...n, read: true } : n))
    );
  }
}

// frameworks/react/apps/router/src/pages/Notifications.tsx
import { useState, useEffect } from 'react';
import { createMockApi } from 'shared-data/mock-api';
import LoadingSkeleton from '../components/LoadingSkeleton';

const api = createMockApi();

interface Notification {
  id: number;
  message: string;
  read: boolean;
}

export default function Notifications() {
  const [loading, setLoading] = useState(true);
  const [notifications, setNotifications] = useState<Notification[]>([]);

  useEffect(() => {
    let cancelled = false;
    api.fetchNotifications(500).then((res) => {
      if (cancelled) return;
      setNotifications(res.data);
      setLoading(false);
    });
    return () => { cancelled = true; };
  }, []);

  if (loading) return <LoadingSkeleton />;

  const unreadCount = notifications.filter((n) => !n.read).length;

  return (
    <div>
      <div className="page-header">
        <h1>Notifications</h1>
        <p>{unreadCount} unread of {notifications.length} total</p>
      </div>
      <div className="notification-list">
        {notifications.map((n) => (
          <div key={n.id} className={`notification-item ${n.read ? '' : 'unread'}`}>
            {n.message}
          </div>
        ))}
      </div>
    </div>
  );
}
