// frameworks/react/apps/dashboard/src/components/KpiCard.tsx
interface KpiCardProps {
  title: string;
  value: number;
  delta: number;
}

export default function KpiCard({ title, value, delta }: KpiCardProps) {
  const isPositive = delta >= 0;
  const arrow = isPositive ? '\u2191' : '\u2193';
  const percentage = value !== 0 ? ((delta / Math.abs(value - delta)) * 100).toFixed(1) : '0.0';

  return (
    <div className="widget kpi-card">
      <div className="widget-title">{title}</div>
      <div className="kpi-value">{value.toLocaleString()}</div>
      <div className={`kpi-delta ${isPositive ? 'positive' : 'negative'}`}>
        {arrow} {Math.abs(delta).toLocaleString()} ({isPositive ? '+' : ''}{percentage}%)
      </div>
    </div>
  );
}

// frameworks/angular/apps/dashboard/src/app/components/kpi-card/kpi-card.component.ts
import { Component, input, computed } from '@angular/core';

@Component({
  selector: 'app-kpi-card',
  standalone: true,
  template: `
    <div class="widget kpi-card">
      <div class="widget-title">{{ title() }}</div>
      <div class="kpi-value">{{ formattedValue() }}</div>
      <div class="kpi-delta" [class.positive]="delta() >= 0" [class.negative]="delta() < 0">
        {{ delta() >= 0 ? '\u2191' : '\u2193' }}
        {{ formattedDelta() }}
      </div>
    </div>
  `,
})
export class KpiCardComponent {
  readonly title = input.required<string>();
  readonly value = input.required<number>();
  readonly delta = input.required<number>();

  readonly formattedValue = computed(() => this.value().toLocaleString());

  readonly formattedDelta = computed(() => {
    const d = this.delta();
    const pct = this.value() !== 0 ? Math.abs((d / this.value()) * 100).toFixed(1) : '0.0';
    return `${Math.abs(d).toLocaleString()} (${pct}%)`;
  });
}
