// frameworks/angular/apps/table/src/app/app.component.ts
import { Component, signal, computed, effect, OnInit } from '@angular/core';
import { DataTableComponent } from './components/data-table/data-table.component';
import { PaginationComponent } from './components/pagination/pagination.component';
import { generateTableData, type TableRow, type BenchmarkHooks } from 'shared-data';

type SortDirection = 'asc' | 'desc' | 'none';

interface SortState {
  column: keyof TableRow | null;
  direction: SortDirection;
}

declare global {
  interface Window {
    __benchmark?: BenchmarkHooks;
  }
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [DataTableComponent, PaginationComponent],
  templateUrl: './app.component.html',
})
export class AppComponent implements OnInit {
  private allRows = signal<TableRow[]>([]);

  readonly filterText = signal('');
  readonly sortState = signal<SortState>({ column: null, direction: 'none' });
  readonly currentPage = signal(1);
  readonly pageSize = 50;
  readonly selectedIds = signal<Set<number>>(new Set());
  readonly lastClickedIndex = signal<number | null>(null);
  readonly editingCell = signal<{ rowId: number; column: keyof TableRow } | null>(null);

  private filterDebounceTimer: ReturnType<typeof setTimeout> | null = null;
  private debouncedFilter = signal('');

  readonly filteredRows = computed(() => {
    const rows = this.allRows();
    const filter = this.debouncedFilter().toLowerCase();
    if (!filter) return rows;
    return rows.filter(
      (row) =>
        row.firstName.toLowerCase().includes(filter) ||
        row.lastName.toLowerCase().includes(filter) ||
        row.email.toLowerCase().includes(filter) ||
        row.department.toLowerCase().includes(filter)
    );
  });

  readonly sortedRows = computed(() => {
    const rows = [...this.filteredRows()];
    const { column, direction } = this.sortState();
    if (!column || direction === 'none') return rows;

    return rows.sort((a, b) => {
      const aVal = a[column];
      const bVal = b[column];
      let cmp: number;
      if (typeof aVal === 'string' && typeof bVal === 'string') {
        cmp = aVal.localeCompare(bVal);
      } else if (typeof aVal === 'boolean' && typeof bVal === 'boolean') {
        cmp = (aVal === bVal) ? 0 : aVal ? -1 : 1;
      } else {
        cmp = (aVal as number) - (bVal as number);
      }
      return direction === 'asc' ? cmp : -cmp;
    });
  });

  readonly totalPages = computed(() => Math.max(1, Math.ceil(this.sortedRows().length / this.pageSize)));

  readonly paginatedRows = computed(() => {
    const start = (this.currentPage() - 1) * this.pageSize;
    return this.sortedRows().slice(start, start + this.pageSize);
  });

  readonly selectedCount = computed(() => this.selectedIds().size);

  constructor() {
    effect(() => {
      const totalPages = this.totalPages();
      if (this.currentPage() > totalPages) {
        this.currentPage.set(totalPages);
      }
    });
  }

  ngOnInit(): void {
    this.allRows.set(generateTableData(10000, 42));
    this.exposeBenchmarkHooks();
  }

  onFilterChange(value: string): void {
    this.filterText.set(value);
    if (this.filterDebounceTimer) {
      clearTimeout(this.filterDebounceTimer);
    }
    this.filterDebounceTimer = setTimeout(() => {
      this.debouncedFilter.set(value);
      this.currentPage.set(1);
    }, 150);
  }

  onSort(column: keyof TableRow): void {
    const current = this.sortState();
    let newDirection: SortDirection;
    if (current.column !== column) {
      newDirection = 'asc';
    } else if (current.direction === 'asc') {
      newDirection = 'desc';
    } else if (current.direction === 'desc') {
      newDirection = 'none';
    } else {
      newDirection = 'asc';
    }
    this.sortState.set({
      column: newDirection === 'none' ? null : column,
      direction: newDirection,
    });
  }

  onRowClick(row: TableRow, event: MouseEvent): void {
    const currentRows = this.sortedRows();
    const clickedIndex = currentRows.findIndex((r) => r.id === row.id);
    const selected = new Set(this.selectedIds());

    if (event.shiftKey && this.lastClickedIndex() !== null) {
      const start = Math.min(this.lastClickedIndex()!, clickedIndex);
      const end = Math.max(this.lastClickedIndex()!, clickedIndex);
      for (let i = start; i <= end; i++) {
        selected.add(currentRows[i].id);
      }
    } else {
      if (selected.has(row.id)) {
        selected.delete(row.id);
      } else {
        selected.add(row.id);
      }
    }

    this.selectedIds.set(selected);
    this.lastClickedIndex.set(clickedIndex);
  }

  onDeleteSelected(): void {
    const selected = this.selectedIds();
    this.allRows.update((rows) => rows.filter((r) => !selected.has(r.id)));
    this.selectedIds.set(new Set());
    this.lastClickedIndex.set(null);
  }

  onToggleActive(): void {
    const selected = this.selectedIds();
    this.allRows.update((rows) =>
      rows.map((r) => (selected.has(r.id) ? { ...r, isActive: !r.isActive } : r))
    );
  }

  onStartEdit(rowId: number, column: keyof TableRow): void {
    this.editingCell.set({ rowId, column });
  }

  onCommitEdit(rowId: number, column: keyof TableRow, value: string): void {
    this.allRows.update((rows) =>
      rows.map((r) => {
        if (r.id !== rowId) return r;
        const updated = { ...r };
        if (column === 'salary') {
          (updated as Record<string, unknown>)[column] = Number(value) || r.salary;
        } else if (column === 'isActive') {
          (updated as Record<string, unknown>)[column] = value === 'true';
        } else {
          (updated as Record<string, unknown>)[column] = value;
        }
        return updated as TableRow;
      })
    );
    this.editingCell.set(null);
  }

  onCancelEdit(): void {
    this.editingCell.set(null);
  }

  onPageChange(page: number): void {
    this.currentPage.set(Math.max(1, Math.min(page, this.totalPages())));
  }

  private exposeBenchmarkHooks(): void {
    const self = this;
    window.__benchmark = {
      createRows(count: number) {
        self.allRows.set(generateTableData(count, 42));
      },
      updateEveryNthRow(n: number) {
        self.allRows.update((rows) =>
          rows.map((r, i) => (i % n === 0 ? { ...r, lastName: r.lastName + '!' } : r))
        );
      },
      replaceAllRows() {
        self.allRows.set(generateTableData(10000, 99));
      },
      selectRow(index: number) {
        const rows = self.allRows();
        if (rows[index]) {
          const selected = new Set(self.selectedIds());
          if (selected.has(rows[index].id)) {
            selected.delete(rows[index].id);
          } else {
            selected.add(rows[index].id);
          }
          self.selectedIds.set(selected);
        }
      },
      swapRows(a: number, b: number) {
        self.allRows.update((rows) => {
          const newRows = [...rows];
          [newRows[a], newRows[b]] = [newRows[b], newRows[a]];
          return newRows;
        });
      },
      removeRow(index: number) {
        self.allRows.update((rows) => {
          const newRows = [...rows];
          newRows.splice(index, 1);
          return newRows;
        });
      },
      clearRows() {
        self.allRows.set([]);
      },
      appendRows(count: number) {
        const existing = self.allRows();
        const maxId = existing.reduce((max, r) => Math.max(max, r.id), 0);
        const newRows = generateTableData(count, 77).map((r, i) => ({
          ...r,
          id: maxId + i + 1,
        }));
        self.allRows.update((rows) => [...rows, ...newRows]);
      },
      getRowCount() {
        return self.allRows().length;
      },
    };
  }
}

<div style="padding: 16px;">
  <h1>Angular - CRUD Data Table</h1>

  <div class="toolbar">
    <input
      type="text"
      placeholder="Filter rows..."
      [value]="filterText()"
      (input)="onFilterChange($any($event.target).value)"
    />
    <button
      class="danger"
      [disabled]="selectedCount() === 0"
      (click)="onDeleteSelected()"
    >
      Delete Selected ({{ selectedCount() }})
    </button>
    <button
      class="secondary"
      [disabled]="selectedCount() === 0"
      (click)="onToggleActive()"
    >
      Toggle Active
    </button>
    <span style="margin-left: auto; color: var(--color-text-secondary); font-size: 13px;">
      {{ sortedRows().length }} rows
    </span>
  </div>

  <app-data-table
    [rows]="paginatedRows()"
    [sortColumn]="sortState().column"
    [sortDirection]="sortState().direction"
    [selectedIds]="selectedIds()"
    [editingCell]="editingCell()"
    (sort)="onSort($event)"
    (rowClick)="onRowClick($event.row, $event.event)"
    (startEdit)="onStartEdit($event.rowId, $event.column)"
    (commitEdit)="onCommitEdit($event.rowId, $event.column, $event.value)"
    (cancelEdit)="onCancelEdit()"
  ></app-data-table>

  <app-pagination
    [currentPage]="currentPage()"
    [totalPages]="totalPages()"
    (pageChange)="onPageChange($event)"
  ></app-pagination>
</div>

// frameworks/svelte/apps/table/src/App.svelte
<script lang="ts">
  import { generateTableData } from 'shared-data';
  import type { TableRow, BenchmarkHooks } from 'shared-data';
  import DataTable from './components/DataTable.svelte';
  import Pagination from './components/Pagination.svelte';

  type SortDir = 'asc' | 'desc' | 'none';
  type SortKey = keyof TableRow;

  let allRows = $state<TableRow[]>(generateTableData(10000));
  let filterText = $state('');
  let debouncedFilter = $state('');
  let sortKey = $state<SortKey | null>(null);
  let sortDir = $state<SortDir>('none');
  let selectedIds = $state<Set<number>>(new Set());
  let lastClickedIndex = $state<number | null>(null);
  let editingCell = $state<{ rowId: number; field: SortKey } | null>(null);
  let editingValue = $state('');
  let currentPage = $state(1);
  const pageSize = 50;

  let debounceTimer: ReturnType<typeof setTimeout> | undefined;

  function onFilterInput(e: Event) {
    const value = (e.target as HTMLInputElement).value;
    filterText = value;
    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(() => {
      debouncedFilter = value;
      currentPage = 1;
    }, 150);
  }

  let filteredRows = $derived.by(() => {
    if (!debouncedFilter) return allRows;
    const lower = debouncedFilter.toLowerCase();
    return allRows.filter(
      (row) =>
        row.firstName.toLowerCase().includes(lower) ||
        row.lastName.toLowerCase().includes(lower) ||
        row.email.toLowerCase().includes(lower) ||
        row.department.toLowerCase().includes(lower)
    );
  });

  let sortedRows = $derived.by(() => {
    if (!sortKey || sortDir === 'none') return filteredRows;
    const key = sortKey;
    const dir = sortDir;
    return [...filteredRows].sort((a, b) => {
      const aVal = a[key];
      const bVal = b[key];
      if (aVal < bVal) return dir === 'asc' ? -1 : 1;
      if (aVal > bVal) return dir === 'asc' ? 1 : -1;
      return 0;
    });
  });

  let totalPages = $derived(Math.max(1, Math.ceil(sortedRows.length / pageSize)));

  let pageRows = $derived.by(() => {
    const start = (currentPage - 1) * pageSize;
    return sortedRows.slice(start, start + pageSize);
  });

  function handleSort(key: SortKey) {
    if (sortKey === key) {
      if (sortDir === 'asc') sortDir = 'desc';
      else if (sortDir === 'desc') { sortDir = 'none'; sortKey = null; }
      else sortDir = 'asc';
    } else {
      sortKey = key;
      sortDir = 'asc';
    }
  }

  function handleRowClick(rowId: number, event: MouseEvent) {
    const currentIndex = sortedRows.findIndex((r) => r.id === rowId);
    if (event.shiftKey && lastClickedIndex !== null) {
      const start = Math.min(lastClickedIndex, currentIndex);
      const end = Math.max(lastClickedIndex, currentIndex);
      const newSelected = new Set(selectedIds);
      for (let i = start; i <= end; i++) {
        newSelected.add(sortedRows[i].id);
      }
      selectedIds = newSelected;
    } else {
      const newSelected = new Set(selectedIds);
      if (newSelected.has(rowId)) {
        newSelected.delete(rowId);
      } else {
        newSelected.add(rowId);
      }
      selectedIds = newSelected;
    }
    lastClickedIndex = currentIndex;
  }

  function handleDoubleClick(rowId: number, field: SortKey) {
    const row = allRows.find((r) => r.id === rowId);
    if (!row) return;
    editingCell = { rowId, field };
    editingValue = String(row[field]);
  }

  function commitEdit() {
    if (!editingCell) return;
    const { rowId, field } = editingCell;
    allRows = allRows.map((row) => {
      if (row.id !== rowId) return row;
      const updated = { ...row };
      if (field === 'salary') {
        updated[field] = Number(editingValue) || 0;
      } else if (field === 'isActive') {
        updated[field] = editingValue === 'true';
      } else if (field === 'id') {
        updated[field] = Number(editingValue) || 0;
      } else {
        (updated as any)[field] = editingValue;
      }
      return updated;
    });
    editingCell = null;
  }

  function cancelEdit() {
    editingCell = null;
  }

  function deleteSelected() {
    allRows = allRows.filter((row) => !selectedIds.has(row.id));
    selectedIds = new Set();
    lastClickedIndex = null;
  }

  function toggleActiveSelected() {
    allRows = allRows.map((row) =>
      selectedIds.has(row.id) ? { ...row, isActive: !row.isActive } : row
    );
  }

  // Benchmark hooks
  const benchmarkHooks: BenchmarkHooks = {
    createRows(count: number) {
      allRows = generateTableData(count);
      selectedIds = new Set();
      currentPage = 1;
    },
    updateEveryNthRow(n: number) {
      allRows = allRows.map((row, i) =>
        i % n === 0 ? { ...row, lastName: row.lastName + ' !' } : row
      );
    },
    replaceAllRows() {
      allRows = generateTableData(10000, 99);
      selectedIds = new Set();
      currentPage = 1;
    },
    selectRow(index: number) {
      if (index >= 0 && index < allRows.length) {
        const newSelected = new Set<number>();
        newSelected.add(allRows[index].id);
        selectedIds = newSelected;
      }
    },
    swapRows(a: number, b: number) {
      if (a >= 0 && a < allRows.length && b >= 0 && b < allRows.length) {
        const newRows = [...allRows];
        [newRows[a], newRows[b]] = [newRows[b], newRows[a]];
        allRows = newRows;
      }
    },
    removeRow(index: number) {
      if (index >= 0 && index < allRows.length) {
        allRows = [...allRows.slice(0, index), ...allRows.slice(index + 1)];
      }
    },
    clearRows() {
      allRows = [];
      selectedIds = new Set();
      currentPage = 1;
    },
    appendRows(count: number) {
      const maxId = allRows.reduce((max, r) => Math.max(max, r.id), 0);
      const newRows = generateTableData(count, 77).map((r, i) => ({
        ...r,
        id: maxId + i + 1,
      }));
      allRows = [...allRows, ...newRows];
    },
    getRowCount() {
      return allRows.length;
    },
  };

  (window as any).__benchmark = benchmarkHooks;
</script>

<div class="table-container" style="padding: 16px;">
  <div class="toolbar">
    <input
      type="text"
      placeholder="Filter rows..."
      value={filterText}
      oninput={onFilterInput}
    />
    <button
      class="danger"
      disabled={selectedIds.size === 0}
      onclick={deleteSelected}
    >
      Delete Selected ({selectedIds.size})
    </button>
    <button
      class="secondary"
      disabled={selectedIds.size === 0}
      onclick={toggleActiveSelected}
    >
      Toggle Active
    </button>
    <span style="margin-left: auto; color: var(--color-text-secondary); font-size: 13px;">
      {sortedRows.length} rows
    </span>
  </div>

  <DataTable
    rows={pageRows}
    {sortKey}
    {sortDir}
    {selectedIds}
    {editingCell}
    {editingValue}
    onSort={handleSort}
    onRowClick={handleRowClick}
    onDoubleClick={handleDoubleClick}
    onCommitEdit={commitEdit}
    onCancelEdit={cancelEdit}
    onEditValueChange={(v: string) => editingValue = v}
  />

  <Pagination
    {currentPage}
    {totalPages}
    onPageChange={(p: number) => currentPage = p}
  />
</div>
