// frameworks/vue/apps/table/src/components/Pagination.vue
<script setup lang="ts">
import { ref, watch } from 'vue';

interface Props {
  currentPage: number;
  totalPages: number;
}

const props = defineProps<Props>();

const emit = defineEmits<{
  'update:current-page': [page: number];
}>();

const pageInput = ref(String(props.currentPage));

watch(
  () => props.currentPage,
  (val) => {
    pageInput.value = String(val);
  }
);

function goToPage(page: number) {
  const clamped = Math.max(1, Math.min(page, props.totalPages));
  emit('update:current-page', clamped);
}

function onPageInputKeydown(event: KeyboardEvent) {
  if (event.key === 'Enter') {
    const parsed = parseInt(pageInput.value, 10);
    if (!isNaN(parsed)) {
      goToPage(parsed);
    } else {
      pageInput.value = String(props.currentPage);
    }
  }
}
</script>

<template>
  <div class="pagination">
    <button :disabled="currentPage <= 1" @click="goToPage(1)">
      First
    </button>
    <button :disabled="currentPage <= 1" @click="goToPage(currentPage - 1)">
      Prev
    </button>
    <span class="page-info">
      Page
      <input
        v-model="pageInput"
        type="text"
        @keydown="onPageInputKeydown"
      />
      of {{ totalPages }}
    </span>
    <button
      :disabled="currentPage >= totalPages"
      @click="goToPage(currentPage + 1)"
    >
      Next
    </button>
    <button
      :disabled="currentPage >= totalPages"
      @click="goToPage(totalPages)"
    >
      Last
    </button>
  </div>
</template>

// frameworks/svelte/apps/table/src/components/Pagination.svelte
<script lang="ts">
  interface Props {
    currentPage: number;
    totalPages: number;
    onPageChange: (page: number) => void;
  }

  let { currentPage, totalPages, onPageChange }: Props = $props();

  let pageInputValue = $state('');

  $effect(() => {
    pageInputValue = String(currentPage);
  });

  function goToFirst() { onPageChange(1); }
  function goToPrev() { if (currentPage > 1) onPageChange(currentPage - 1); }
  function goToNext() { if (currentPage < totalPages) onPageChange(currentPage + 1); }
  function goToLast() { onPageChange(totalPages); }

  function handlePageInput(e: KeyboardEvent) {
    if (e.key === 'Enter') {
      const val = parseInt(pageInputValue, 10);
      if (!isNaN(val) && val >= 1 && val <= totalPages) {
        onPageChange(val);
      } else {
        pageInputValue = String(currentPage);
      }
    }
  }
</script>

<div class="pagination">
  <button onclick={goToFirst} disabled={currentPage <= 1}>First</button>
  <button onclick={goToPrev} disabled={currentPage <= 1}>Prev</button>
  <span class="page-info">
    Page
    <input
      type="text"
      value={pageInputValue}
      oninput={(e: Event) => pageInputValue = (e.target as HTMLInputElement).value}
      onkeydown={handlePageInput}
    />
    of {totalPages}
  </span>
  <button onclick={goToNext} disabled={currentPage >= totalPages}>Next</button>
  <button onclick={goToLast} disabled={currentPage >= totalPages}>Last</button>
</div>
