// frameworks/svelte/apps/dashboard/src/components/KpiCard.svelte
<script lang="ts">
  interface Props {
    title: string;
    value: number;
    delta: number;
  }

  let { title, value, delta }: Props = $props();

  let deltaClass = $derived(delta >= 0 ? 'positive' : 'negative');
  let deltaArrow = $derived(delta >= 0 ? '\u2191' : '\u2193');
  let deltaPercent = $derived(
    value !== 0 ? ((Math.abs(delta) / Math.abs(value)) * 100).toFixed(1) : '0.0'
  );
</script>

<div class="widget kpi-card">
  <div class="widget-title">{title}</div>
  <div class="kpi-value">{value.toLocaleString()}</div>
  <div class="kpi-delta {deltaClass}">
    {deltaArrow} {Math.abs(delta).toLocaleString()} ({deltaPercent}%)
  </div>
</div>

// frameworks/vue/apps/dashboard/src/components/KpiCard.vue
<script setup lang="ts">
import { computed } from 'vue';

interface Props {
  title: string;
  value: number;
  delta: number;
}

const props = defineProps<Props>();

const deltaClass = computed(() =>
  props.delta >= 0 ? 'positive' : 'negative'
);

const deltaArrow = computed(() => (props.delta >= 0 ? '▲' : '▼'));

const deltaPercent = computed(() => {
  if (props.value === 0) return '0.0';
  return Math.abs((props.delta / props.value) * 100).toFixed(1);
});
</script>

<template>
  <div>
    <div class="widget-title">{{ title }}</div>
    <div class="kpi-value">{{ value.toLocaleString() }}</div>
    <div class="kpi-delta" :class="deltaClass">
      {{ deltaArrow }} {{ deltaPercent }}%
    </div>
  </div>
</template>
