// frameworks/svelte/apps/dashboard/src/components/StatusGrid.svelte
<script lang="ts">
  import type { StatusUpdate } from 'shared-data';

  interface Props {
    cells: StatusUpdate['status'][];
  }

  let { cells }: Props = $props();
</script>

<div class="widget">
  <div class="widget-title">Status Grid</div>
  <div class="status-grid">
    {#each cells as status, i (i)}
      <div class="status-cell {status}"></div>
    {/each}
  </div>
</div>

// frameworks/vue/apps/dashboard/src/components/StatusGrid.vue
<script setup lang="ts">
import type { StatusUpdate } from 'shared-data';

interface Props {
  cells: StatusUpdate['status'][];
}

defineProps<Props>();
</script>

<template>
  <div class="status-grid">
    <div
      v-for="(status, index) in cells"
      :key="index"
      class="status-cell"
      :class="status"
    ></div>
  </div>
</template>
