// frameworks/svelte/apps/nested-tree/src/App.svelte
<script lang="ts">
  import { setContext } from 'svelte';
  import Level from './components/Level.svelte';

  let theme = $state<'light' | 'dark'>('dark');
  let counter = $state(0);
  let wideMode = $state(false);
  let lifecycleCount = $state(0);

  let maxDepth = $derived(wideMode ? 10 : 50);
  let lifecycleItems = $derived(Array.from({ length: lifecycleCount }, (_, i) => i));

  setContext('theme', {
    get value() { return theme; },
  });

  setContext('counter', {
    get value() { return counter; },
  });

  function toggleTheme() {
    theme = theme === 'dark' ? 'light' : 'dark';
  }

  function increment() {
    counter++;
  }

  function toggleWideMode() {
    wideMode = !wideMode;
  }

  // Benchmark hooks
  (window as any).__benchmark = {
    setTheme(t: 'light' | 'dark') {
      theme = t;
    },
    toggleTheme() {
      theme = theme === 'dark' ? 'light' : 'dark';
    },
    getTheme() {
      return theme;
    },
    incrementCounter() {
      counter++;
    },
    getCounter() {
      return counter;
    },
    setWideMode(w: boolean) {
      wideMode = w;
    },
    getLeafTimestamp(): string | null {
      const leaf = document.querySelector('[data-bench-leaf]');
      return leaf?.textContent ?? null;
    },
    mountComponents(n: number) {
      lifecycleCount = n;
    },
    unmountComponents() {
      lifecycleCount = 0;
    },
  };
</script>

<div style="padding: 16px;" data-theme={theme}>
  <div class="toolbar">
    <button onclick={toggleTheme}>
      Theme: {theme}
    </button>
    <button onclick={increment}>
      Increment ({counter})
    </button>
    <button class="secondary" onclick={toggleWideMode}>
      {wideMode ? 'Deep Mode (50)' : 'Wide Mode (3x10)'}
    </button>
  </div>

  <div style="margin-top: 16px;">
    <Level depth={1} {maxDepth} {wideMode} />
  </div>

  <div id="lifecycle-container">
    {#each lifecycleItems as i (i)}
      <Level depth={1} maxDepth={3} wideMode={false} />
    {/each}
  </div>
</div>

// frameworks/vue/apps/nested-tree/src/App.vue
<script setup lang="ts">
import { ref, provide, onMounted } from 'vue';
import Level from './components/Level.vue';

const theme = ref<'light' | 'dark'>('dark');
const counter = ref(0);
const wideMode = ref(false);
const lifecycleCount = ref(0);

provide('theme', theme);
provide('counter', counter);
provide('wideMode', wideMode);

function toggleTheme() {
  theme.value = theme.value === 'dark' ? 'light' : 'dark';
}

function increment() {
  counter.value++;
}

function toggleWideMode() {
  wideMode.value = !wideMode.value;
}

const maxDepth = ref(50);
const computedMaxDepth = () => (wideMode.value ? 10 : maxDepth.value);

// Benchmark hooks
onMounted(() => {
  const hooks = {
    toggleTheme() {
      toggleTheme();
    },
    incrementCounter() {
      increment();
    },
    setCounter(val: number) {
      counter.value = val;
    },
    getCounter() {
      return counter.value;
    },
    getTheme() {
      return theme.value;
    },
    toggleWideMode() {
      toggleWideMode();
    },
    mountComponents(n: number) {
      lifecycleCount.value = n;
    },
    unmountComponents() {
      lifecycleCount.value = 0;
    },
  };
  (window as unknown as Record<string, unknown>).__benchmark = hooks;
});
</script>

<template>
  <div :data-theme="theme" style="padding: 16px">
    <h1 style="margin-bottom: 12px">Vue - Deeply Nested Component Tree</h1>
    <div class="toolbar">
      <button @click="toggleTheme">
        Toggle Theme ({{ theme }})
      </button>
      <button @click="increment">
        Increment ({{ counter }})
      </button>
      <button class="secondary" @click="toggleWideMode">
        {{ wideMode ? 'Normal Mode (depth 50)' : 'Wide Mode (3×10)' }}
      </button>
    </div>
    <div
      style="
        margin-top: 12px;
        border: 1px solid var(--color-border);
        border-radius: var(--radius);
        padding: 8px;
        overflow: auto;
        max-height: calc(100vh - 140px);
      "
    >
      <Level :depth="1" :max-depth="computedMaxDepth()" />
    </div>
    <div id="lifecycle-container">
      <Level
        v-for="i in lifecycleCount"
        :key="i"
        :depth="1"
        :max-depth="3"
      />
    </div>
  </div>
</template>
