// frameworks/vue/apps/nested-tree/src/App.vue
<script setup lang="ts">
import { ref, provide, onMounted } from 'vue';
import Level from './components/Level.vue';

const theme = ref<'light' | 'dark'>('dark');
const counter = ref(0);
const wideMode = ref(false);
const lifecycleCount = ref(0);

provide('theme', theme);
provide('counter', counter);
provide('wideMode', wideMode);

function toggleTheme() {
  theme.value = theme.value === 'dark' ? 'light' : 'dark';
}

function increment() {
  counter.value++;
}

function toggleWideMode() {
  wideMode.value = !wideMode.value;
}

const maxDepth = ref(50);
const computedMaxDepth = () => (wideMode.value ? 10 : maxDepth.value);

// Benchmark hooks
onMounted(() => {
  const hooks = {
    toggleTheme() {
      toggleTheme();
    },
    incrementCounter() {
      increment();
    },
    setCounter(val: number) {
      counter.value = val;
    },
    getCounter() {
      return counter.value;
    },
    getTheme() {
      return theme.value;
    },
    toggleWideMode() {
      toggleWideMode();
    },
    mountComponents(n: number) {
      lifecycleCount.value = n;
    },
    unmountComponents() {
      lifecycleCount.value = 0;
    },
  };
  (window as unknown as Record<string, unknown>).__benchmark = hooks;
});
</script>

<template>
  <div :data-theme="theme" style="padding: 16px">
    <h1 style="margin-bottom: 12px">Vue - Deeply Nested Component Tree</h1>
    <div class="toolbar">
      <button @click="toggleTheme">
        Toggle Theme ({{ theme }})
      </button>
      <button @click="increment">
        Increment ({{ counter }})
      </button>
      <button class="secondary" @click="toggleWideMode">
        {{ wideMode ? 'Normal Mode (depth 50)' : 'Wide Mode (3×10)' }}
      </button>
    </div>
    <div
      style="
        margin-top: 12px;
        border: 1px solid var(--color-border);
        border-radius: var(--radius);
        padding: 8px;
        overflow: auto;
        max-height: calc(100vh - 140px);
      "
    >
      <Level :depth="1" :max-depth="computedMaxDepth()" />
    </div>
    <div id="lifecycle-container">
      <Level
        v-for="i in lifecycleCount"
        :key="i"
        :depth="1"
        :max-depth="3"
      />
    </div>
  </div>
</template>

// frameworks/react/apps/nested-tree/src/App.tsx
import { useState, createContext, useEffect } from 'react';
import Level from './components/Level';

export const ThemeContext = createContext<'light' | 'dark'>('dark');
export const CounterContext = createContext<number>(0);

const MAX_DEPTH_NORMAL = 50;
const MAX_DEPTH_WIDE = 10;
const CHILDREN_PER_LEVEL_WIDE = 3;

export default function App() {
  const [theme, setTheme] = useState<'light' | 'dark'>('dark');
  const [counter, setCounter] = useState(0);
  const [wideMode, setWideMode] = useState(false);
  const [lifecycleCount, setLifecycleCount] = useState(0);

  const maxDepth = wideMode ? MAX_DEPTH_WIDE : MAX_DEPTH_NORMAL;
  const childrenPerLevel = wideMode ? CHILDREN_PER_LEVEL_WIDE : 1;

  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme);
  }, [theme]);

  // Benchmark hooks
  useEffect(() => {
    const hooks = {
      incrementCounter: () => setCounter((c) => c + 1),
      toggleTheme: () => setTheme((t) => (t === 'light' ? 'dark' : 'light')),
      toggleWideMode: () => setWideMode((w) => !w),
      mountComponents: (n: number) => setLifecycleCount(n),
      unmountComponents: () => setLifecycleCount(0),
    };
    (window as unknown as Record<string, unknown>).__benchmark = hooks;
    return () => {
      delete (window as unknown as Record<string, unknown>).__benchmark;
    };
  }, []);

  return (
    <ThemeContext.Provider value={theme}>
      <CounterContext.Provider value={counter}>
        <div style={{ padding: '16px' }}>
          <h1 style={{ marginBottom: '8px' }}>Deeply Nested Component Tree</h1>
          <div className="toolbar">
            <button onClick={() => setTheme((t) => (t === 'light' ? 'dark' : 'light'))}>
              Toggle Theme ({theme})
            </button>
            <button onClick={() => setCounter((c) => c + 1)}>
              Increment ({counter})
            </button>
            <button
              className={wideMode ? 'danger' : 'secondary'}
              onClick={() => setWideMode((w) => !w)}
            >
              {wideMode ? 'Wide Mode ON' : 'Wide Mode OFF'}
            </button>
          </div>
          <div
            style={{
              marginTop: '12px',
              maxHeight: 'calc(100vh - 120px)',
              overflow: 'auto',
            }}
          >
            <Level
              depth={1}
              maxDepth={maxDepth}
              childrenPerLevel={childrenPerLevel}
            />
          </div>
          <div id="lifecycle-container">
            {Array.from({ length: lifecycleCount }, (_, i) => (
              <Level key={i} depth={1} maxDepth={3} childrenPerLevel={1} />
            ))}
          </div>
        </div>
      </CounterContext.Provider>
    </ThemeContext.Provider>
  );
}
