// frameworks/angular/apps/router/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { SidebarComponent } from './components/sidebar/sidebar.component';
import type { RouterBenchmarkHooks } from 'shared-data';
import { Router, NavigationEnd } from '@angular/router';
import { filter } from 'rxjs/operators';

declare global {
  interface Window {
    __benchmark?: RouterBenchmarkHooks;
  }
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, SidebarComponent],
  templateUrl: './app.component.html',
})
export class AppComponent implements OnInit {
  private loadTime = performance.now();

  constructor(private router: Router) {}

  ngOnInit(): void {
    this.router.events
      .pipe(filter((e) => e instanceof NavigationEnd))
      .subscribe(() => {
        this.loadTime = performance.now();
      });

    this.exposeBenchmarkHooks();
  }

  private exposeBenchmarkHooks(): void {
    window.__benchmark = {
      navigateTo: async (path: string) => {
        const start = performance.now();
        await this.router.navigateByUrl(path);
        // Wait for rendering
        return new Promise<number>((resolve) => {
          requestAnimationFrame(() => {
            setTimeout(() => {
              resolve(performance.now() - start);
            }, 0);
          });
        });
      },
      getLoadTime: () => this.loadTime,
    };
  }
}

<div class="app-layout">
  <app-sidebar></app-sidebar>
  <main class="main-content">
    <div class="page-fade">
      <router-outlet></router-outlet>
    </div>
  </main>
</div>

// frameworks/vue/apps/router/src/App.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import { useRouter } from 'vue-router';
import type { RouterBenchmarkHooks } from 'shared-data';
import Sidebar from './components/Sidebar.vue';

const router = useRouter();

onMounted(() => {
  const loadTime = performance.now();

  const hooks: RouterBenchmarkHooks = {
    async navigateTo(path: string) {
      const start = performance.now();
      await router.push(path);
      // Wait for next paint
      await new Promise<void>((resolve) => {
        requestAnimationFrame(() => setTimeout(resolve, 0));
      });
      return performance.now() - start;
    },
    getLoadTime() {
      return loadTime;
    },
  };
  (window as unknown as Record<string, unknown>).__benchmark = hooks;
});
</script>

<template>
  <div class="app-layout">
    <Sidebar />
    <main class="main-content">
      <router-view v-slot="{ Component }">
        <Transition name="page" mode="out-in">
          <component :is="Component" />
        </Transition>
      </router-view>
    </main>
  </div>
</template>

<style>
.page-enter-active,
.page-leave-active {
  transition: opacity 200ms ease;
}
.page-enter-from,
.page-leave-to {
  opacity: 0;
}
</style>
