// frameworks/svelte/apps/table/src/components/Pagination.svelte
<script lang="ts">
  interface Props {
    currentPage: number;
    totalPages: number;
    onPageChange: (page: number) => void;
  }

  let { currentPage, totalPages, onPageChange }: Props = $props();

  let pageInputValue = $state('');

  $effect(() => {
    pageInputValue = String(currentPage);
  });

  function goToFirst() { onPageChange(1); }
  function goToPrev() { if (currentPage > 1) onPageChange(currentPage - 1); }
  function goToNext() { if (currentPage < totalPages) onPageChange(currentPage + 1); }
  function goToLast() { onPageChange(totalPages); }

  function handlePageInput(e: KeyboardEvent) {
    if (e.key === 'Enter') {
      const val = parseInt(pageInputValue, 10);
      if (!isNaN(val) && val >= 1 && val <= totalPages) {
        onPageChange(val);
      } else {
        pageInputValue = String(currentPage);
      }
    }
  }
</script>

<div class="pagination">
  <button onclick={goToFirst} disabled={currentPage <= 1}>First</button>
  <button onclick={goToPrev} disabled={currentPage <= 1}>Prev</button>
  <span class="page-info">
    Page
    <input
      type="text"
      value={pageInputValue}
      oninput={(e: Event) => pageInputValue = (e.target as HTMLInputElement).value}
      onkeydown={handlePageInput}
    />
    of {totalPages}
  </span>
  <button onclick={goToNext} disabled={currentPage >= totalPages}>Next</button>
  <button onclick={goToLast} disabled={currentPage >= totalPages}>Last</button>
</div>

// frameworks/angular/apps/table/src/app/components/pagination/pagination.component.ts
import { Component, input, output } from '@angular/core';

@Component({
  selector: 'app-pagination',
  standalone: true,
  templateUrl: './pagination.component.html',
})
export class PaginationComponent {
  readonly currentPage = input.required<number>();
  readonly totalPages = input.required<number>();

  readonly pageChange = output<number>();

  goToFirst(): void {
    this.pageChange.emit(1);
  }

  goToPrev(): void {
    this.pageChange.emit(this.currentPage() - 1);
  }

  goToNext(): void {
    this.pageChange.emit(this.currentPage() + 1);
  }

  goToLast(): void {
    this.pageChange.emit(this.totalPages());
  }

  onPageInput(event: Event): void {
    const value = parseInt((event.target as HTMLInputElement).value, 10);
    if (!isNaN(value)) {
      this.pageChange.emit(value);
    }
  }
}

<div class="pagination">
  <button (click)="goToFirst()" [disabled]="currentPage() <= 1">First</button>
  <button (click)="goToPrev()" [disabled]="currentPage() <= 1">Prev</button>
  <span class="page-info">
    Page
    <input
      type="number"
      [value]="currentPage()"
      (change)="onPageInput($event)"
      [min]="1"
      [max]="totalPages()"
    />
    of {{ totalPages() }}
  </span>
  <button (click)="goToNext()" [disabled]="currentPage() >= totalPages()">Next</button>
  <button (click)="goToLast()" [disabled]="currentPage() >= totalPages()">Last</button>
</div>
