// frameworks/vue/apps/form/src/components/ErrorSummary.vue
<script setup lang="ts">
interface Props {
  errors: { key: string; message: string }[];
}

defineProps<Props>();

function scrollToField(key: string) {
  const el = document.getElementById(`field-${key}`);
  el?.scrollIntoView({ behavior: 'smooth', block: 'center' });
}
</script>

<template>
  <div class="error-summary">
    <h3>Please fix the following errors ({{ errors.length }}):</h3>
    <ul>
      <li v-for="error in errors" :key="error.key">
        <a href="#" @click.prevent="scrollToField(error.key)">
          {{ error.message }}
        </a>
      </li>
    </ul>
  </div>
</template>

// frameworks/react/apps/form/src/components/ErrorSummary.tsx
interface ErrorSummaryProps {
  errors: [string, string][];
}

export default function ErrorSummary({ errors }: ErrorSummaryProps) {
  if (errors.length === 0) return null;

  return (
    <div className="error-summary">
      <h3>{errors.length} error{errors.length !== 1 ? 's' : ''} found</h3>
      <ul>
        {errors.map(([name, message]) => (
          <li key={name}>
            <a
              href={`#group-${name}`}
              onClick={(e) => {
                e.preventDefault();
                const el = document.getElementById(`group-${name}`);
                if (el) el.scrollIntoView({ behavior: 'smooth', block: 'center' });
              }}
            >
              {message}
            </a>
          </li>
        ))}
      </ul>
    </div>
  );
}
