// frameworks/svelte/apps/form/src/components/FormField.svelte
<script lang="ts">
  import type { FormField } from 'shared-data';

  interface Props {
    field: FormField;
    value: string | boolean;
    error: string;
    onChange: (value: string | boolean) => void;
    onBlur: () => void;
  }

  let { field, value, error, onChange, onBlur }: Props = $props();

  let stringValue = $derived(typeof value === 'boolean' ? '' : (value ?? ''));
  let boolValue = $derived(typeof value === 'boolean' ? value : false);
  let hasError = $derived(!!error);

  function handleInput(e: Event) {
    const target = e.target as HTMLInputElement;
    onChange(target.value);
  }

  function handleCheckbox(e: Event) {
    const target = e.target as HTMLInputElement;
    onChange(target.checked);
  }

  function handleSelect(e: Event) {
    const target = e.target as HTMLSelectElement;
    onChange(target.value);
  }

  function handleFileChange(e: Event) {
    const target = e.target as HTMLInputElement;
    const file = target.files?.[0];
    onChange(file ? file.name : '');
  }
</script>

<div class="form-group" id="field-{field.name}">
  {#if field.type === 'checkbox'}
    <div class="checkbox-group">
      <label>
        <input
          type="checkbox"
          checked={boolValue}
          onchange={handleCheckbox}
          onblur={onBlur}
        />
        {field.label}
      </label>
    </div>
  {:else if field.type === 'radio'}
    <label>{field.label}</label>
    <div class="radio-group">
      {#each field.options ?? [] as option (option.value)}
        <label>
          <input
            type="radio"
            name={field.name}
            value={option.value}
            checked={stringValue === option.value}
            onchange={handleInput}
            onblur={onBlur}
          />
          {option.label}
        </label>
      {/each}
    </div>
  {:else if field.type === 'select'}
    <label for={field.name}>{field.label}</label>
    <select
      id={field.name}
      value={stringValue}
      class:invalid={hasError}
      onchange={handleSelect}
      onblur={onBlur}
    >
      <option value="">-- Select --</option>
      {#each field.options ?? [] as option (option.value)}
        <option value={option.value}>{option.label}</option>
      {/each}
    </select>
  {:else if field.type === 'textarea'}
    <label for={field.name}>{field.label}</label>
    <textarea
      id={field.name}
      placeholder={field.placeholder}
      value={stringValue}
      class:invalid={hasError}
      oninput={handleInput}
      onblur={onBlur}
    ></textarea>
  {:else if field.type === 'file'}
    <label for={field.name}>{field.label}</label>
    <input
      type="file"
      id={field.name}
      class:invalid={hasError}
      onchange={handleFileChange}
      onblur={onBlur}
    />
  {:else if field.type === 'date'}
    <label for={field.name}>{field.label}</label>
    <input
      type="date"
      id={field.name}
      value={stringValue}
      class:invalid={hasError}
      oninput={handleInput}
      onblur={onBlur}
    />
  {:else}
    <label for={field.name}>{field.label}</label>
    <input
      type="text"
      id={field.name}
      placeholder={field.placeholder}
      value={stringValue}
      class:invalid={hasError}
      oninput={handleInput}
      onblur={onBlur}
    />
  {/if}

  {#if hasError}
    <div class="error-message">{error}</div>
  {/if}
</div>

// frameworks/react/apps/form/src/components/FormField.tsx
import type { FormField as FormFieldType } from 'shared-data';

interface FormFieldProps {
  field: FormFieldType;
  value: string | boolean;
  error?: string;
  onChange: (name: string, value: string | boolean) => void;
  onBlur: (name: string) => void;
}

export default function FormField({ field, value, error, onChange, onBlur }: FormFieldProps) {
  const id = `field-${field.name}`;
  const hasError = !!error;

  const renderInput = () => {
    switch (field.type) {
      case 'text':
        return (
          <input
            type="text"
            id={id}
            name={field.name}
            value={value as string}
            placeholder={field.placeholder}
            className={hasError ? 'invalid' : ''}
            onChange={(e) => onChange(field.name, e.target.value)}
            onBlur={() => onBlur(field.name)}
          />
        );

      case 'select':
        return (
          <select
            id={id}
            name={field.name}
            value={value as string}
            className={hasError ? 'invalid' : ''}
            onChange={(e) => onChange(field.name, e.target.value)}
            onBlur={() => onBlur(field.name)}
          >
            <option value="">-- Select --</option>
            {field.options?.map((opt) => (
              <option key={opt.value} value={opt.value}>
                {opt.label}
              </option>
            ))}
          </select>
        );

      case 'checkbox':
        return (
          <div className="checkbox-group">
            <label>
              <input
                type="checkbox"
                id={id}
                name={field.name}
                checked={value as boolean}
                onChange={(e) => onChange(field.name, e.target.checked)}
                onBlur={() => onBlur(field.name)}
              />
              {field.label}
            </label>
          </div>
        );

      case 'radio':
        return (
          <div className="radio-group">
            {field.options?.map((opt) => (
              <label key={opt.value}>
                <input
                  type="radio"
                  name={field.name}
                  value={opt.value}
                  checked={value === opt.value}
                  onChange={(e) => onChange(field.name, e.target.value)}
                  onBlur={() => onBlur(field.name)}
                />
                {opt.label}
              </label>
            ))}
          </div>
        );

      case 'date':
        return (
          <input
            type="date"
            id={id}
            name={field.name}
            value={value as string}
            className={hasError ? 'invalid' : ''}
            onChange={(e) => onChange(field.name, e.target.value)}
            onBlur={() => onBlur(field.name)}
          />
        );

      case 'textarea':
        return (
          <textarea
            id={id}
            name={field.name}
            value={value as string}
            placeholder={field.placeholder}
            className={hasError ? 'invalid' : ''}
            onChange={(e) => onChange(field.name, e.target.value)}
            onBlur={() => onBlur(field.name)}
          />
        );

      case 'file':
        return (
          <input
            type="file"
            id={id}
            name={field.name}
            className={hasError ? 'invalid' : ''}
            onChange={(e) => {
              const file = e.target.files?.[0];
              onChange(field.name, file ? file.name : '');
            }}
            onBlur={() => onBlur(field.name)}
          />
        );

      default:
        return null;
    }
  };

  // Checkbox has its own label pattern
  if (field.type === 'checkbox') {
    return (
      <div className="form-group" id={`group-${field.name}`}>
        {renderInput()}
        {hasError && <div className="error-message">{error}</div>}
      </div>
    );
  }

  return (
    <div className="form-group" id={`group-${field.name}`}>
      <label htmlFor={id}>{field.label}</label>
      {renderInput()}
      {hasError && <div className="error-message">{error}</div>}
    </div>
  );
}
