// frameworks/svelte/apps/form/src/components/RepeatableGroup.svelte
<script lang="ts">
  import type { RepeatableGroupField } from 'shared-data';

  interface Props {
    groupId: number;
    fields: RepeatableGroupField[];
    values: Record<string, string>;
    errors: Record<string, string>;
    onRemove: () => void;
    onFieldChange: (fieldName: string, value: string) => void;
  }

  let { groupId, fields, values, errors, onRemove, onFieldChange }: Props = $props();

  function errorKey(fieldName: string): string {
    return `${groupId}_${fieldName}`;
  }
</script>

<div class="repeatable-group">
  <button type="button" class="danger remove-btn" onclick={onRemove}>Remove</button>

  {#each fields as field (field.name)}
    <div class="form-group" id="field-{errorKey(field.name)}">
      <label for="{errorKey(field.name)}">{field.label}</label>
      {#if field.type === 'textarea'}
        <textarea
          id="{errorKey(field.name)}"
          placeholder={field.placeholder}
          value={values[field.name] || ''}
          class:invalid={!!errors[errorKey(field.name)]}
          oninput={(e: Event) => onFieldChange(field.name, (e.target as HTMLTextAreaElement).value)}
        ></textarea>
      {:else}
        <input
          type="text"
          id="{errorKey(field.name)}"
          placeholder={field.placeholder}
          value={values[field.name] || ''}
          class:invalid={!!errors[errorKey(field.name)]}
          oninput={(e: Event) => onFieldChange(field.name, (e.target as HTMLInputElement).value)}
        />
      {/if}
      {#if errors[errorKey(field.name)]}
        <div class="error-message">{errors[errorKey(field.name)]}</div>
      {/if}
    </div>
  {/each}
</div>

// frameworks/react/apps/form/src/components/RepeatableGroup.tsx
import type { RepeatableGroupField } from 'shared-data';

interface RepeatableGroupProps {
  groupId: number;
  fields: RepeatableGroupField[];
  values: Record<string, string>;
  errors: Record<string, string>;
  touched: Set<string>;
  onChange: (groupId: number, fieldName: string, value: string) => void;
  onRemove: (groupId: number) => void;
}

export default function RepeatableGroup({
  groupId,
  fields,
  values,
  errors,
  touched,
  onChange,
  onRemove,
}: RepeatableGroupProps) {
  return (
    <div className="repeatable-group">
      <button
        type="button"
        className="danger remove-btn"
        onClick={() => onRemove(groupId)}
      >
        Remove
      </button>
      {fields.map((field) => {
        const errorKey = `group-${groupId}-${field.name}`;
        const hasError = touched.has(errorKey) && !!errors[errorKey];
        const fieldId = `group-${groupId}-${field.name}`;

        return (
          <div className="form-group" key={field.name} id={fieldId}>
            <label htmlFor={fieldId}>{field.label}</label>
            {field.type === 'textarea' ? (
              <textarea
                id={fieldId}
                name={fieldId}
                value={values[field.name] || ''}
                placeholder={field.placeholder}
                className={hasError ? 'invalid' : ''}
                onChange={(e) => onChange(groupId, field.name, e.target.value)}
              />
            ) : (
              <input
                type="text"
                id={fieldId}
                name={fieldId}
                value={values[field.name] || ''}
                placeholder={field.placeholder}
                className={hasError ? 'invalid' : ''}
                onChange={(e) => onChange(groupId, field.name, e.target.value)}
              />
            )}
            {hasError && <div className="error-message">{errors[errorKey]}</div>}
          </div>
        );
      })}
    </div>
  );
}
