// frameworks/angular/apps/form/src/app/components/repeatable-group/repeatable-group.component.ts
import { Component, input, output } from '@angular/core';
import { ReactiveFormsModule, FormGroup } from '@angular/forms';
import type { RepeatableGroupField } from 'shared-data';

@Component({
  selector: 'app-repeatable-group',
  standalone: true,
  imports: [ReactiveFormsModule],
  template: `
    <div class="repeatable-group" [formGroup]="group()">
      <button
        type="button"
        class="remove-btn danger"
        (click)="remove.emit()"
      >Remove</button>

      @for (field of fields(); track field.name) {
        <div class="form-group">
          <label [for]="fieldId(field.name)">{{ field.label }}</label>
          @if (field.type === 'textarea') {
            <textarea
              [id]="fieldId(field.name)"
              [formControlName]="field.name"
              [placeholder]="field.placeholder ?? ''"
              [class.invalid]="isInvalid(field.name)"
            ></textarea>
          } @else {
            <input
              type="text"
              [id]="fieldId(field.name)"
              [formControlName]="field.name"
              [placeholder]="field.placeholder ?? ''"
              [class.invalid]="isInvalid(field.name)"
            />
          }
          @if (isInvalid(field.name)) {
            @for (rule of field.validation; track rule.type) {
              @if (hasError(field.name, rule.type)) {
                <div class="error-message">{{ rule.message }}</div>
              }
            }
          }
        </div>
      }
    </div>
  `,
})
export class RepeatableGroupComponent {
  readonly group = input.required<FormGroup>();
  readonly index = input.required<number>();
  readonly fields = input.required<RepeatableGroupField[]>();
  readonly showErrors = input(false);

  readonly remove = output<void>();

  fieldId(fieldName: string): string {
    return `ref-${this.index()}-${fieldName}`;
  }

  isInvalid(fieldName: string): boolean {
    const ctrl = this.group().get(fieldName);
    return ctrl !== null && ctrl.invalid && (ctrl.touched || this.showErrors());
  }

  hasError(fieldName: string, ruleType: string): boolean {
    const ctrl = this.group().get(fieldName);
    if (!ctrl) return false;
    const mapping: Record<string, string> = {
      required: 'required',
      minLength: 'minlength',
      maxLength: 'maxlength',
      pattern: 'pattern',
    };
    return ctrl.hasError(mapping[ruleType] || ruleType);
  }
}

// frameworks/react/apps/form/src/components/RepeatableGroup.tsx
import type { RepeatableGroupField } from 'shared-data';

interface RepeatableGroupProps {
  groupId: number;
  fields: RepeatableGroupField[];
  values: Record<string, string>;
  errors: Record<string, string>;
  touched: Set<string>;
  onChange: (groupId: number, fieldName: string, value: string) => void;
  onRemove: (groupId: number) => void;
}

export default function RepeatableGroup({
  groupId,
  fields,
  values,
  errors,
  touched,
  onChange,
  onRemove,
}: RepeatableGroupProps) {
  return (
    <div className="repeatable-group">
      <button
        type="button"
        className="danger remove-btn"
        onClick={() => onRemove(groupId)}
      >
        Remove
      </button>
      {fields.map((field) => {
        const errorKey = `group-${groupId}-${field.name}`;
        const hasError = touched.has(errorKey) && !!errors[errorKey];
        const fieldId = `group-${groupId}-${field.name}`;

        return (
          <div className="form-group" key={field.name} id={fieldId}>
            <label htmlFor={fieldId}>{field.label}</label>
            {field.type === 'textarea' ? (
              <textarea
                id={fieldId}
                name={fieldId}
                value={values[field.name] || ''}
                placeholder={field.placeholder}
                className={hasError ? 'invalid' : ''}
                onChange={(e) => onChange(groupId, field.name, e.target.value)}
              />
            ) : (
              <input
                type="text"
                id={fieldId}
                name={fieldId}
                value={values[field.name] || ''}
                placeholder={field.placeholder}
                className={hasError ? 'invalid' : ''}
                onChange={(e) => onChange(groupId, field.name, e.target.value)}
              />
            )}
            {hasError && <div className="error-message">{errors[errorKey]}</div>}
          </div>
        );
      })}
    </div>
  );
}
