// frameworks/svelte/apps/form/src/components/DebugPanel.svelte
<script lang="ts">
  interface Props {
    data: Record<string, string | boolean>;
    groups: { id: number; values: Record<string, string> }[];
  }

  let { data, groups }: Props = $props();

  let isOpen = $state(false);

  let debugJson = $derived(
    JSON.stringify(
      {
        ...data,
        references: groups.map((g) => g.values),
      },
      null,
      2
    )
  );
</script>

<div class="debug-panel">
  <h3>
    <button
      type="button"
      class="secondary"
      style="padding: 2px 8px; font-size: 12px;"
      onclick={() => isOpen = !isOpen}
    >
      {isOpen ? 'Hide' : 'Show'} Debug Panel
    </button>
  </h3>
  {#if isOpen}
    <pre>{debugJson}</pre>
  {/if}
</div>

// frameworks/vue/apps/form/src/components/DebugPanel.vue
<script setup lang="ts">
import { computed } from 'vue';

interface Props {
  state: Record<string, unknown>;
}

const props = defineProps<Props>();

const formattedState = computed(() => JSON.stringify(props.state, null, 2));
</script>

<template>
  <div class="debug-panel">
    <h3>Form State (Debug)</h3>
    <pre>{{ formattedState }}</pre>
  </div>
</template>
