// frameworks/svelte/apps/form/src/components/ErrorSummary.svelte
<script lang="ts">
  interface Props {
    errors: Record<string, string>;
  }

  let { errors }: Props = $props();

  let errorEntries = $derived(Object.entries(errors));
</script>

{#if errorEntries.length > 0}
  <div class="error-summary">
    <h3>Please fix the following errors ({errorEntries.length}):</h3>
    <ul>
      {#each errorEntries as [field, message] (field)}
        <li>
          <a href="#field-{field}" onclick={(e: MouseEvent) => {
            e.preventDefault();
            document.getElementById(`field-${field}`)?.scrollIntoView({ behavior: 'smooth', block: 'center' });
          }}>
            {message}
          </a>
        </li>
      {/each}
    </ul>
  </div>
{/if}

// frameworks/vue/apps/form/src/components/ErrorSummary.vue
<script setup lang="ts">
interface Props {
  errors: { key: string; message: string }[];
}

defineProps<Props>();

function scrollToField(key: string) {
  const el = document.getElementById(`field-${key}`);
  el?.scrollIntoView({ behavior: 'smooth', block: 'center' });
}
</script>

<template>
  <div class="error-summary">
    <h3>Please fix the following errors ({{ errors.length }}):</h3>
    <ul>
      <li v-for="error in errors" :key="error.key">
        <a href="#" @click.prevent="scrollToField(error.key)">
          {{ error.message }}
        </a>
      </li>
    </ul>
  </div>
</template>
