// frameworks/svelte/apps/form/src/components/FormField.svelte
<script lang="ts">
  import type { FormField } from 'shared-data';

  interface Props {
    field: FormField;
    value: string | boolean;
    error: string;
    onChange: (value: string | boolean) => void;
    onBlur: () => void;
  }

  let { field, value, error, onChange, onBlur }: Props = $props();

  let stringValue = $derived(typeof value === 'boolean' ? '' : (value ?? ''));
  let boolValue = $derived(typeof value === 'boolean' ? value : false);
  let hasError = $derived(!!error);

  function handleInput(e: Event) {
    const target = e.target as HTMLInputElement;
    onChange(target.value);
  }

  function handleCheckbox(e: Event) {
    const target = e.target as HTMLInputElement;
    onChange(target.checked);
  }

  function handleSelect(e: Event) {
    const target = e.target as HTMLSelectElement;
    onChange(target.value);
  }

  function handleFileChange(e: Event) {
    const target = e.target as HTMLInputElement;
    const file = target.files?.[0];
    onChange(file ? file.name : '');
  }
</script>

<div class="form-group" id="field-{field.name}">
  {#if field.type === 'checkbox'}
    <div class="checkbox-group">
      <label>
        <input
          type="checkbox"
          checked={boolValue}
          onchange={handleCheckbox}
          onblur={onBlur}
        />
        {field.label}
      </label>
    </div>
  {:else if field.type === 'radio'}
    <label>{field.label}</label>
    <div class="radio-group">
      {#each field.options ?? [] as option (option.value)}
        <label>
          <input
            type="radio"
            name={field.name}
            value={option.value}
            checked={stringValue === option.value}
            onchange={handleInput}
            onblur={onBlur}
          />
          {option.label}
        </label>
      {/each}
    </div>
  {:else if field.type === 'select'}
    <label for={field.name}>{field.label}</label>
    <select
      id={field.name}
      value={stringValue}
      class:invalid={hasError}
      onchange={handleSelect}
      onblur={onBlur}
    >
      <option value="">-- Select --</option>
      {#each field.options ?? [] as option (option.value)}
        <option value={option.value}>{option.label}</option>
      {/each}
    </select>
  {:else if field.type === 'textarea'}
    <label for={field.name}>{field.label}</label>
    <textarea
      id={field.name}
      placeholder={field.placeholder}
      value={stringValue}
      class:invalid={hasError}
      oninput={handleInput}
      onblur={onBlur}
    ></textarea>
  {:else if field.type === 'file'}
    <label for={field.name}>{field.label}</label>
    <input
      type="file"
      id={field.name}
      class:invalid={hasError}
      onchange={handleFileChange}
      onblur={onBlur}
    />
  {:else if field.type === 'date'}
    <label for={field.name}>{field.label}</label>
    <input
      type="date"
      id={field.name}
      value={stringValue}
      class:invalid={hasError}
      oninput={handleInput}
      onblur={onBlur}
    />
  {:else}
    <label for={field.name}>{field.label}</label>
    <input
      type="text"
      id={field.name}
      placeholder={field.placeholder}
      value={stringValue}
      class:invalid={hasError}
      oninput={handleInput}
      onblur={onBlur}
    />
  {/if}

  {#if hasError}
    <div class="error-message">{error}</div>
  {/if}
</div>

// frameworks/vue/apps/form/src/components/FormField.vue
<script setup lang="ts">
import type { FormField } from 'shared-data';

interface Props {
  field: FormField;
  value: string | boolean;
  error?: string;
  touched: boolean;
}

const props = defineProps<Props>();

const emit = defineEmits<{
  'update:value': [value: string | boolean];
  blur: [];
}>();

function onInputChange(event: Event) {
  const target = event.target as HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement;
  if (props.field.type === 'checkbox') {
    emit('update:value', (target as HTMLInputElement).checked);
  } else {
    emit('update:value', target.value);
  }
}

function onRadioChange(optionValue: string) {
  emit('update:value', optionValue);
}

const showError = () => props.touched && !!props.error;
</script>

<template>
  <div :id="'field-' + field.name" class="form-group">
    <label :for="'input-' + field.name">{{ field.label }}</label>

    <!-- Text input -->
    <input
      v-if="field.type === 'text'"
      :id="'input-' + field.name"
      :name="field.name"
      type="text"
      :value="value as string"
      :placeholder="field.placeholder"
      :class="{ invalid: showError() }"
      @input="onInputChange"
      @blur="emit('blur')"
    />

    <!-- Select -->
    <select
      v-else-if="field.type === 'select'"
      :id="'input-' + field.name"
      :name="field.name"
      :value="value as string"
      :class="{ invalid: showError() }"
      @change="onInputChange"
      @blur="emit('blur')"
    >
      <option value="">-- Select --</option>
      <option
        v-for="opt in field.options"
        :key="opt.value"
        :value="opt.value"
      >
        {{ opt.label }}
      </option>
    </select>

    <!-- Checkbox -->
    <div v-else-if="field.type === 'checkbox'" class="checkbox-group">
      <label>
        <input
          :id="'input-' + field.name"
          :name="field.name"
          type="checkbox"
          :checked="value as boolean"
          @change="onInputChange"
          @blur="emit('blur')"
        />
        {{ field.label }}
      </label>
    </div>

    <!-- Radio -->
    <div v-else-if="field.type === 'radio'" class="radio-group">
      <label v-for="opt in field.options" :key="opt.value">
        <input
          type="radio"
          :name="field.name"
          :value="opt.value"
          :checked="value === opt.value"
          @change="onRadioChange(opt.value)"
          @blur="emit('blur')"
        />
        {{ opt.label }}
      </label>
    </div>

    <!-- Date -->
    <input
      v-else-if="field.type === 'date'"
      :id="'input-' + field.name"
      :name="field.name"
      type="date"
      :value="value as string"
      :class="{ invalid: showError() }"
      @input="onInputChange"
      @blur="emit('blur')"
    />

    <!-- Textarea -->
    <textarea
      v-else-if="field.type === 'textarea'"
      :id="'input-' + field.name"
      :name="field.name"
      :value="value as string"
      :placeholder="field.placeholder"
      :class="{ invalid: showError() }"
      @input="onInputChange"
      @blur="emit('blur')"
    ></textarea>

    <!-- File -->
    <input
      v-else-if="field.type === 'file'"
      :id="'input-' + field.name"
      :name="field.name"
      type="file"
      :class="{ invalid: showError() }"
      @change="onInputChange"
      @blur="emit('blur')"
    />

    <div v-if="showError()" class="error-message">{{ error }}</div>
  </div>
</template>
