// frameworks/vue/apps/dashboard/src/App.vue
<script setup lang="ts">
import { ref, reactive, onMounted, onUnmounted } from 'vue';
import { createMockWebSocket } from 'shared-data/mock-ws';
import type {
  DashboardBatch,
  DashboardBenchmarkHooks,
  DashboardBenchmarkResult,
  KpiUpdate,
  StatusUpdate,
} from 'shared-data';
import ChartWidget from './components/ChartWidget.vue';
import KpiCard from './components/KpiCard.vue';
import StatusGrid from './components/StatusGrid.vue';
import DashboardTable from './components/DashboardTable.vue';

const ws = createMockWebSocket();
const isRunning = ref(false);
const speed = ref(60);
const benchmarkMode = ref(false);
const benchmarkResult = ref<DashboardBenchmarkResult | null>(null);

// Chart data: 4 line charts, 4 bar charts
const lineChartData = reactive<number[][]>(
  Array.from({ length: 4 }, () => Array.from({ length: 100 }, () => 50))
);
const barChartData = reactive<number[][]>(
  Array.from({ length: 4 }, () => Array.from({ length: 8 }, () => 50))
);

// KPI state
const kpis = reactive<KpiUpdate[]>([
  { index: 0, value: 1250, delta: 0 },
  { index: 1, value: 8734, delta: 0 },
]);

// Table state: 50 rows x 5 columns
const tableData = reactive<number[][]>(
  Array.from({ length: 50 }, (_, i) =>
    Array.from({ length: 5 }, (_, j) => (i + 1) * 100 + j)
  )
);
const flashingCells = ref<Set<string>>(new Set());

// Status grid: 100 cells
const statusCells = reactive<StatusUpdate['status'][]>(
  Array.from({ length: 100 }, () => 'idle' as StatusUpdate['status'])
);

function handleBatch(batch: DashboardBatch) {
  // Update line charts
  for (let i = 0; i < 4; i++) {
    const points = batch.lineCharts[i];
    if (points) {
      lineChartData[i] = points.map((p) => p.value);
    }
  }

  // Update bar charts
  for (let i = 0; i < 4; i++) {
    if (batch.barCharts[i]) {
      barChartData[i] = batch.barCharts[i];
    }
  }

  // Update KPIs
  for (const kpi of batch.kpis) {
    if (kpi.index < kpis.length) {
      kpis[kpi.index] = kpi;
    }
  }

  // Update table rows with flash
  const newFlashing = new Set<string>();
  for (const update of batch.tableRows) {
    if (update.rowIndex < tableData.length) {
      tableData[update.rowIndex] = update.values;
      for (let c = 0; c < update.values.length; c++) {
        newFlashing.add(`${update.rowIndex}-${c}`);
      }
    }
  }
  flashingCells.value = newFlashing;
  setTimeout(() => {
    flashingCells.value = new Set();
  }, 300);

  // Update status cells
  for (const update of batch.statusCells) {
    if (update.cellIndex < statusCells.length) {
      statusCells[update.cellIndex] = update.status;
    }
  }
}

function start() {
  ws.connect(handleBatch);
  ws.setRate(speed.value);
  isRunning.value = true;
}

function stop() {
  ws.disconnect();
  isRunning.value = false;
}

function toggleRunning() {
  if (isRunning.value) {
    stop();
  } else {
    start();
  }
}

function onSpeedChange(event: Event) {
  const val = Number((event.target as HTMLInputElement).value);
  speed.value = val;
  if (isRunning.value) {
    ws.setRate(val);
  }
}

function runBenchmark(): Promise<DashboardBenchmarkResult> {
  return new Promise((resolve) => {
    benchmarkMode.value = true;
    benchmarkResult.value = null;

    const frameTimes: number[] = [];
    let frameCount = 0;
    let lastFrameTime = performance.now();
    let rafId: number;

    function countFrame() {
      const now = performance.now();
      frameTimes.push(now - lastFrameTime);
      lastFrameTime = now;
      frameCount++;
      rafId = requestAnimationFrame(countFrame);
    }

    ws.connect(handleBatch);
    ws.setRate(60);
    isRunning.value = true;
    rafId = requestAnimationFrame(countFrame);

    setTimeout(() => {
      cancelAnimationFrame(rafId);
      ws.disconnect();
      isRunning.value = false;
      benchmarkMode.value = false;

      const sorted = [...frameTimes].sort((a, b) => a - b);
      const avg = frameTimes.reduce((s, t) => s + t, 0) / frameTimes.length;
      const p99 = sorted[Math.floor(sorted.length * 0.99)] || 0;
      const expectedFrames = 10 * 60;
      const dropped = Math.max(0, expectedFrames - frameCount);

      const result: DashboardBenchmarkResult = {
        framesRendered: frameCount,
        droppedFrames: dropped,
        avgFrameTime: Math.round(avg * 100) / 100,
        p99FrameTime: Math.round(p99 * 100) / 100,
        duration: 10000,
      };

      benchmarkResult.value = result;
      resolve(result);
    }, 10000);
  });
}

onMounted(() => {
  const hooks: DashboardBenchmarkHooks = {
    start,
    stop,
    setSpeed(batchesPerSecond: number) {
      speed.value = batchesPerSecond;
      if (isRunning.value) {
        ws.setRate(batchesPerSecond);
      }
    },
    runBenchmark,
  };
  (window as unknown as Record<string, unknown>).__benchmark = hooks;
});

onUnmounted(() => {
  ws.disconnect();
});

const CHART_COLORS = ['#3b82f6', '#22c55e', '#f59e0b', '#ef4444'];
</script>

<template>
  <div class="dashboard">
    <h1 style="margin-bottom: 8px">Vue - Real-Time Dashboard</h1>
    <div class="dashboard-controls">
      <button @click="toggleRunning">
        {{ isRunning ? 'Stop' : 'Start' }}
      </button>
      <div class="speed-slider">
        <label>Speed: {{ speed }} batches/sec</label>
        <input
          type="range"
          min="1"
          max="60"
          :value="speed"
          @input="onSpeedChange"
        />
      </div>
      <button class="secondary" @click="runBenchmark">
        Benchmark (10s)
      </button>
      <span
        v-if="benchmarkResult"
        style="font-size: 12px; font-family: var(--font-mono); color: var(--color-text-secondary)"
      >
        Frames: {{ benchmarkResult.framesRendered }} |
        Dropped: {{ benchmarkResult.droppedFrames }} |
        Avg: {{ benchmarkResult.avgFrameTime }}ms |
        P99: {{ benchmarkResult.p99FrameTime }}ms
      </span>
    </div>

    <div class="dashboard-grid">
      <!-- Row 1: 4 line charts -->
      <ChartWidget
        v-for="i in 4"
        :key="'line-' + i"
        :title="'Line Chart ' + i"
        type="line"
        :data="lineChartData[i - 1]"
        :color="CHART_COLORS[i - 1]"
      />
      <!-- Row 2: 4 bar charts -->
      <ChartWidget
        v-for="i in 4"
        :key="'bar-' + i"
        :title="'Bar Chart ' + i"
        type="bar"
        :data="barChartData[i - 1]"
        :color="CHART_COLORS[i - 1]"
      />
      <!-- Row 3: 2 KPIs, data table, status grid -->
      <div class="widget kpi-card">
        <KpiCard title="Revenue" :value="kpis[0].value" :delta="kpis[0].delta" />
      </div>
      <div class="widget kpi-card">
        <KpiCard title="Users" :value="kpis[1].value" :delta="kpis[1].delta" />
      </div>
      <div class="widget">
        <div class="widget-title">Live Data</div>
        <DashboardTable :data="tableData" :flashing-cells="flashingCells" />
      </div>
      <div class="widget">
        <div class="widget-title">Status Grid</div>
        <StatusGrid :cells="statusCells" />
      </div>
    </div>
  </div>
</template>

// frameworks/angular/apps/dashboard/src/app/app.component.ts
import { Component, signal, OnInit, OnDestroy } from '@angular/core';
import { ChartWidgetComponent } from './components/chart-widget/chart-widget.component';
import { KpiCardComponent } from './components/kpi-card/kpi-card.component';
import { StatusGridComponent } from './components/status-grid/status-grid.component';
import { DashboardTableComponent } from './components/dashboard-table/dashboard-table.component';
import {
  createMockWebSocket,
  type MockWebSocket,
  type DashboardBatch,
  type DashboardBenchmarkHooks,
  type DashboardBenchmarkResult,
} from 'shared-data';

const CHART_COLORS = ['#3b82f6', '#22c55e', '#f59e0b', '#ef4444'];

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [ChartWidgetComponent, KpiCardComponent, StatusGridComponent, DashboardTableComponent],
  templateUrl: './app.component.html',
})
export class AppComponent implements OnInit, OnDestroy {
  private ws: MockWebSocket | null = null;

  readonly isRunning = signal(false);
  readonly speed = signal(60);

  // Chart data: 4 line charts, 4 bar charts
  readonly lineChartData = signal<number[][]>([[], [], [], []]);
  readonly barChartData = signal<number[][]>([[], [], [], []]);

  // KPIs
  readonly kpis = signal<{ value: number; delta: number }[]>([
    { value: 0, delta: 0 },
    { value: 0, delta: 0 },
  ]);

  // Table data: 50 rows x 5 columns
  readonly tableData = signal<number[][]>(
    Array.from({ length: 50 }, (_, i) =>
      Array.from({ length: 5 }, (_, j) => (i + 1) * 100 + j)
    )
  );
  readonly flashingCells = signal<Set<string>>(new Set());

  // Status grid: 100 cells
  readonly statusCells = signal<('ok' | 'warning' | 'error' | 'idle')[]>(
    Array.from({ length: 100 }, () => 'idle' as const)
  );

  readonly chartColors = CHART_COLORS;

  // Benchmark
  readonly benchmarkResult = signal<DashboardBenchmarkResult | null>(null);

  ngOnInit(): void {
    this.ws = createMockWebSocket(42);
    this.exposeBenchmarkHooks();
  }

  ngOnDestroy(): void {
    this.stop();
  }

  start(): void {
    if (this.isRunning()) return;
    this.isRunning.set(true);
    this.ws!.connect((batch: DashboardBatch) => this.handleBatch(batch));
    this.ws!.setRate(this.speed());
  }

  stop(): void {
    if (!this.isRunning()) return;
    this.ws!.disconnect();
    this.isRunning.set(false);
  }

  toggleRunning(): void {
    if (this.isRunning()) {
      this.stop();
    } else {
      this.start();
    }
  }

  onSpeedChange(event: Event): void {
    const value = parseInt((event.target as HTMLInputElement).value, 10);
    this.speed.set(value);
    if (this.isRunning()) {
      this.ws!.setRate(value);
    }
  }

  private handleBatch(batch: DashboardBatch): void {
    // Update line charts
    this.lineChartData.set(
      batch.lineCharts.map((chart) => chart.map((dp) => dp.value))
    );

    // Update bar charts
    this.barChartData.set(batch.barCharts);

    // Update KPIs
    this.kpis.set(
      batch.kpis.map((kpi) => ({ value: kpi.value, delta: kpi.delta }))
    );

    // Update table data with flashing
    const newTable = this.tableData().map((row) => [...row]);
    const newFlashing = new Set<string>();
    for (const update of batch.tableRows) {
      newTable[update.rowIndex] = update.values;
      for (let col = 0; col < update.values.length; col++) {
        newFlashing.add(`${update.rowIndex}-${col}`);
      }
    }
    this.tableData.set(newTable);
    this.flashingCells.set(newFlashing);

    // Clear flash after animation
    setTimeout(() => {
      this.flashingCells.set(new Set());
    }, 300);

    // Update status grid
    const cells = [...this.statusCells()];
    for (const update of batch.statusCells) {
      cells[update.cellIndex] = update.status;
    }
    this.statusCells.set(cells);
  }

  async runBenchmark(): Promise<DashboardBenchmarkResult> {
    this.benchmarkResult.set(null);

    if (this.isRunning()) {
      this.stop();
    }

    const duration = 10000;
    const targetRate = 60;
    let framesRendered = 0;
    let lastFrameTime = performance.now();
    const frameTimes: number[] = [];
    let rafId: number;

    const countFrames = () => {
      const now = performance.now();
      frameTimes.push(now - lastFrameTime);
      lastFrameTime = now;
      framesRendered++;
      rafId = requestAnimationFrame(countFrames);
    };

    rafId = requestAnimationFrame(countFrames);

    this.ws = createMockWebSocket(42);
    this.ws.connect((batch: DashboardBatch) => this.handleBatch(batch));
    this.ws.setRate(targetRate);
    this.isRunning.set(true);

    const startTime = performance.now();

    await new Promise<void>((resolve) => {
      setTimeout(() => {
        cancelAnimationFrame(rafId);
        this.stop();
        resolve();
      }, duration);
    });

    const elapsed = performance.now() - startTime;
    const expectedFrames = Math.round((elapsed / 1000) * 60);
    const droppedFrames = Math.max(0, expectedFrames - framesRendered);

    frameTimes.sort((a, b) => a - b);
    const avgFrameTime =
      frameTimes.length > 0
        ? frameTimes.reduce((a, b) => a + b, 0) / frameTimes.length
        : 0;
    const p99Index = Math.floor(frameTimes.length * 0.99);
    const p99FrameTime = frameTimes.length > 0 ? frameTimes[p99Index] : 0;

    const result: DashboardBenchmarkResult = {
      framesRendered,
      droppedFrames,
      avgFrameTime: Math.round(avgFrameTime * 100) / 100,
      p99FrameTime: Math.round(p99FrameTime * 100) / 100,
      duration: Math.round(elapsed),
    };

    this.benchmarkResult.set(result);
    return result;
  }

  private exposeBenchmarkHooks(): void {
    (window as unknown as { __benchmark: DashboardBenchmarkHooks }).__benchmark = {
      start: () => this.start(),
      stop: () => this.stop(),
      setSpeed: (bps: number) => {
        this.speed.set(bps);
        if (this.isRunning()) {
          this.ws!.setRate(bps);
        }
      },
      runBenchmark: () => this.runBenchmark(),
    };
  }
}

<div class="dashboard">
  <h1>Angular - Real-Time Dashboard</h1>

  <div class="dashboard-controls">
    <button (click)="toggleRunning()">
      {{ isRunning() ? 'Stop' : 'Start' }}
    </button>

    <div class="speed-slider">
      <label>Speed: {{ speed() }} batches/sec</label>
      <input
        type="range"
        min="1"
        max="60"
        [value]="speed()"
        (input)="onSpeedChange($event)"
      />
    </div>

    <button class="secondary" (click)="runBenchmark()">Benchmark</button>

    @if (benchmarkResult(); as result) {
      <span style="font-size: 12px; color: var(--color-text-secondary); font-family: var(--font-mono);">
        Frames: {{ result.framesRendered }} |
        Dropped: {{ result.droppedFrames }} |
        Avg: {{ result.avgFrameTime }}ms |
        P99: {{ result.p99FrameTime }}ms |
        Duration: {{ result.duration }}ms
      </span>
    }
  </div>

  <div class="dashboard-grid">
    <!-- 4 Line Charts -->
    @for (i of [0, 1, 2, 3]; track i) {
      <app-chart-widget
        [title]="'Line Chart ' + (i + 1)"
        type="line"
        [data]="lineChartData()[i]"
        [color]="chartColors[i]"
      ></app-chart-widget>
    }

    <!-- 4 Bar Charts -->
    @for (i of [0, 1, 2, 3]; track i) {
      <app-chart-widget
        [title]="'Bar Chart ' + (i + 1)"
        type="bar"
        [data]="barChartData()[i]"
        [color]="chartColors[i]"
      ></app-chart-widget>
    }

    <!-- 2 KPI Cards -->
    @for (kpi of kpis(); track $index) {
      <app-kpi-card
        [title]="$index === 0 ? 'Revenue' : 'Users'"
        [value]="kpi.value"
        [delta]="kpi.delta"
      ></app-kpi-card>
    }

    <!-- Dashboard Table -->
    <app-dashboard-table
      [data]="tableData()"
      [flashingCells]="flashingCells()"
    ></app-dashboard-table>

    <!-- Status Grid -->
    <app-status-grid
      [cells]="statusCells()"
    ></app-status-grid>
  </div>
</div>
