// frameworks/vue/apps/form/src/components/ErrorSummary.vue
<script setup lang="ts">
interface Props {
  errors: { key: string; message: string }[];
}

defineProps<Props>();

function scrollToField(key: string) {
  const el = document.getElementById(`field-${key}`);
  el?.scrollIntoView({ behavior: 'smooth', block: 'center' });
}
</script>

<template>
  <div class="error-summary">
    <h3>Please fix the following errors ({{ errors.length }}):</h3>
    <ul>
      <li v-for="error in errors" :key="error.key">
        <a href="#" @click.prevent="scrollToField(error.key)">
          {{ error.message }}
        </a>
      </li>
    </ul>
  </div>
</template>

// frameworks/angular/apps/form/src/app/components/error-summary/error-summary.component.ts
import { Component, input } from '@angular/core';

@Component({
  selector: 'app-error-summary',
  standalone: true,
  template: `
    <div class="error-summary">
      <h3>Please fix the following errors:</h3>
      <ul>
        @for (error of errors(); track error.field) {
          <li>
            <a [href]="'#field-' + error.field" (click)="scrollToField($event, error.field)">
              {{ error.message }}
            </a>
          </li>
        }
      </ul>
    </div>
  `,
})
export class ErrorSummaryComponent {
  readonly errors = input.required<{ field: string; message: string }[]>();

  scrollToField(event: Event, fieldName: string): void {
    event.preventDefault();
    const el = document.getElementById('field-' + fieldName) ?? document.getElementById(fieldName);
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'center' });
      const input = el.querySelector('input, select, textarea') as HTMLElement | null;
      if (input) input.focus();
    }
  }
}
