// frameworks/angular/apps/router/src/app/pages/dashboard.component.ts
import { Component, signal, OnInit, OnDestroy, ElementRef, viewChild, AfterViewInit } from '@angular/core';
import { LoadingSkeletonComponent } from '../components/loading-skeleton/loading-skeleton.component';
import {
  createMockApi,
  createMockWebSocket,
  renderChart,
  type MockWebSocket,
  type DashboardBatch,
  type ChartConfig,
} from 'shared-data';

@Component({
  selector: 'app-dashboard-page',
  standalone: true,
  imports: [LoadingSkeletonComponent],
  template: `
    <div class="page-header">
      <h1>Dashboard</h1>
      <p>Simplified real-time dashboard with 4 widgets</p>
    </div>

    @if (loading()) {
      <app-loading-skeleton></app-loading-skeleton>
    } @else {
      <div class="dashboard-controls">
        <button (click)="toggleRunning()">
          {{ isRunning() ? 'Stop' : 'Start' }}
        </button>
      </div>
      <div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 12px;">
        <div class="widget">
          <div class="widget-title">Line Chart</div>
          <canvas #chart1></canvas>
        </div>
        <div class="widget">
          <div class="widget-title">Bar Chart</div>
          <canvas #chart2></canvas>
        </div>
        <div class="widget kpi-card">
          <div class="widget-title">Revenue</div>
          <div class="kpi-value">{{ kpi1Value().toLocaleString() }}</div>
          <div class="kpi-delta" [class.positive]="kpi1Delta() >= 0" [class.negative]="kpi1Delta() < 0">
            {{ kpi1Delta() >= 0 ? '\u2191' : '\u2193' }} {{ Math.abs(kpi1Delta()) }}
          </div>
        </div>
        <div class="widget kpi-card">
          <div class="widget-title">Users</div>
          <div class="kpi-value">{{ kpi2Value().toLocaleString() }}</div>
          <div class="kpi-delta" [class.positive]="kpi2Delta() >= 0" [class.negative]="kpi2Delta() < 0">
            {{ kpi2Delta() >= 0 ? '\u2191' : '\u2193' }} {{ Math.abs(kpi2Delta()) }}
          </div>
        </div>
      </div>
    }
  `,
})
export class DashboardPageComponent implements OnInit, OnDestroy, AfterViewInit {
  readonly Math = Math;
  private ws: MockWebSocket | null = null;
  readonly loading = signal(true);
  readonly isRunning = signal(false);
  readonly kpi1Value = signal(0);
  readonly kpi1Delta = signal(0);
  readonly kpi2Value = signal(0);
  readonly kpi2Delta = signal(0);

  private lineData: number[] = [];
  private barData: number[] = [];

  readonly chart1Ref = viewChild<ElementRef<HTMLCanvasElement>>('chart1');
  readonly chart2Ref = viewChild<ElementRef<HTMLCanvasElement>>('chart2');

  private viewReady = false;

  ngOnInit(): void {
    const api = createMockApi(50);
    api.fetchDashboardData().then((res) => {
      this.kpi1Value.set(res.data.kpis[0]);
      this.kpi2Value.set(res.data.kpis[1]);
      this.loading.set(false);
    });
  }

  ngAfterViewInit(): void {
    this.viewReady = true;
  }

  ngOnDestroy(): void {
    this.stop();
  }

  toggleRunning(): void {
    if (this.isRunning()) {
      this.stop();
    } else {
      this.start();
    }
  }

  start(): void {
    if (this.isRunning()) return;
    this.ws = createMockWebSocket(42);
    this.isRunning.set(true);
    this.ws.connect((batch: DashboardBatch) => {
      if (batch.lineCharts[0]) {
        this.lineData = batch.lineCharts[0].map((dp) => dp.value);
      }
      if (batch.barCharts[0]) {
        this.barData = batch.barCharts[0];
      }
      if (batch.kpis[0]) {
        this.kpi1Value.set(batch.kpis[0].value);
        this.kpi1Delta.set(batch.kpis[0].delta);
      }
      if (batch.kpis[1]) {
        this.kpi2Value.set(batch.kpis[1].value);
        this.kpi2Delta.set(batch.kpis[1].delta);
      }
      this.drawCharts();
    });
    this.ws.setRate(30);
  }

  stop(): void {
    if (this.ws) {
      this.ws.disconnect();
      this.ws = null;
    }
    this.isRunning.set(false);
  }

  private drawCharts(): void {
    if (!this.viewReady) return;
    const c1 = this.chart1Ref();
    const c2 = this.chart2Ref();

    if (c1 && this.lineData.length > 0) {
      const canvas = c1.nativeElement;
      const rect = canvas.parentElement!.getBoundingClientRect();
      const cfg: ChartConfig = {
        type: 'line',
        width: Math.max(rect.width - 24, 100),
        height: Math.max(150, 100),
        data: this.lineData,
        color: '#3b82f6',
      };
      renderChart(canvas, cfg);
    }

    if (c2 && this.barData.length > 0) {
      const canvas = c2.nativeElement;
      const rect = canvas.parentElement!.getBoundingClientRect();
      const cfg: ChartConfig = {
        type: 'bar',
        width: Math.max(rect.width - 24, 100),
        height: Math.max(150, 100),
        data: this.barData,
        color: '#22c55e',
      };
      renderChart(canvas, cfg);
    }
  }
}

// frameworks/vue/apps/router/src/pages/Dashboard.vue
<script setup lang="ts">
import { ref, reactive, onMounted, onUnmounted } from 'vue';
import { createMockWebSocket } from 'shared-data/mock-ws';
import { renderChart } from 'shared-data/canvas-charts';
import type { DashboardBatch, KpiUpdate, StatusUpdate, ChartConfig } from 'shared-data';
import LoadingSkeleton from '../components/LoadingSkeleton.vue';

const loading = ref(true);
const ws = createMockWebSocket();
const isRunning = ref(false);

const lineChartData = reactive<number[][]>(
  Array.from({ length: 2 }, () => Array.from({ length: 100 }, () => 50))
);
const barChartData = reactive<number[][]>(
  Array.from({ length: 2 }, () => Array.from({ length: 8 }, () => 50))
);
const kpis = reactive<KpiUpdate[]>([
  { index: 0, value: 1250, delta: 0 },
  { index: 1, value: 8734, delta: 0 },
]);

const canvasRefs = ref<(HTMLCanvasElement | null)[]>([]);

function setCanvasRef(el: unknown, index: number) {
  canvasRefs.value[index] = el as HTMLCanvasElement | null;
}

function drawCharts() {
  const configs: { index: number; type: 'line' | 'bar'; data: number[]; color: string }[] = [
    { index: 0, type: 'line', data: lineChartData[0], color: '#3b82f6' },
    { index: 1, type: 'line', data: lineChartData[1], color: '#22c55e' },
    { index: 2, type: 'bar', data: barChartData[0], color: '#f59e0b' },
    { index: 3, type: 'bar', data: barChartData[1], color: '#ef4444' },
  ];

  for (const cfg of configs) {
    const canvas = canvasRefs.value[cfg.index];
    if (!canvas) continue;
    const rect = canvas.parentElement?.getBoundingClientRect();
    const chartConfig: ChartConfig = {
      type: cfg.type,
      width: rect?.width ?? 300,
      height: rect?.height ? rect.height - 30 : 150,
      data: cfg.data,
      color: cfg.color,
      backgroundColor: '#1e293b',
    };
    renderChart(canvas, chartConfig);
  }
}

function handleBatch(batch: DashboardBatch) {
  for (let i = 0; i < 2; i++) {
    if (batch.lineCharts[i]) {
      lineChartData[i] = batch.lineCharts[i].map((p) => p.value);
    }
    if (batch.barCharts[i]) {
      barChartData[i] = batch.barCharts[i];
    }
  }
  for (const kpi of batch.kpis) {
    if (kpi.index < kpis.length) {
      kpis[kpi.index] = kpi;
    }
  }
  drawCharts();
}

function toggleRunning() {
  if (isRunning.value) {
    ws.disconnect();
    isRunning.value = false;
  } else {
    ws.connect(handleBatch);
    ws.setRate(30);
    isRunning.value = true;
  }
}

onMounted(() => {
  // Simulate data fetch delay
  setTimeout(() => {
    loading.value = false;
    // Draw initial charts after DOM updates
    setTimeout(drawCharts, 50);
  }, 50);
});

onUnmounted(() => {
  ws.disconnect();
});
</script>

<template>
  <div>
    <div class="page-header">
      <h1>Dashboard</h1>
      <p>Simplified real-time dashboard (4 widgets)</p>
    </div>

    <LoadingSkeleton v-if="loading" :lines="4" />

    <template v-else>
      <div style="margin-bottom: 12px">
        <button @click="toggleRunning">
          {{ isRunning ? 'Stop' : 'Start' }} Updates
        </button>
      </div>

      <div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 12px; height: 400px">
        <div
          v-for="(cfg, i) in [
            { title: 'Line Chart 1' },
            { title: 'Line Chart 2' },
            { title: 'Bar Chart 1' },
            { title: 'Bar Chart 2' },
          ]"
          :key="i"
          style="
            background: var(--color-bg-secondary);
            border: 1px solid var(--color-border);
            border-radius: var(--radius);
            padding: 12px;
            display: flex;
            flex-direction: column;
          "
        >
          <div style="font-size: 12px; font-weight: 600; color: var(--color-text-secondary); text-transform: uppercase; margin-bottom: 8px">
            {{ cfg.title }}
          </div>
          <canvas :ref="(el) => setCanvasRef(el, i)" style="width: 100%; flex: 1"></canvas>
        </div>
      </div>

      <div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 12px; margin-top: 12px">
        <div
          v-for="(kpi, i) in kpis"
          :key="i"
          style="
            background: var(--color-bg-secondary);
            border: 1px solid var(--color-border);
            border-radius: var(--radius);
            padding: 16px;
            text-align: center;
          "
        >
          <div style="font-size: 12px; font-weight: 600; color: var(--color-text-secondary); text-transform: uppercase; margin-bottom: 8px">
            {{ i === 0 ? 'Revenue' : 'Users' }}
          </div>
          <div style="font-size: 2rem; font-weight: 700; font-family: var(--font-mono)">
            {{ kpi.value.toLocaleString() }}
          </div>
          <div
            style="margin-top: 4px"
            :style="{ color: kpi.delta >= 0 ? 'var(--color-success)' : 'var(--color-error)' }"
          >
            {{ kpi.delta >= 0 ? '▲' : '▼' }}
            {{ Math.abs(kpi.value > 0 ? (kpi.delta / kpi.value) * 100 : 0).toFixed(1) }}%
          </div>
        </div>
      </div>
    </template>
  </div>
</template>
