// frameworks/react/apps/router/src/pages/Home.tsx
export default function Home() {
  return (
    <div>
      <div className="page-header">
        <h1>Home</h1>
        <p>Welcome to the React Framework Benchmark Suite</p>
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: '16px' }}>
        {[
          { title: 'Dashboard', desc: 'Real-time data dashboard with 12 widgets' },
          { title: 'Table', desc: 'CRUD data table with 1,000 rows' },
          { title: 'Form', desc: 'Dynamic form with 30 fields and validation' },
          { title: 'Profile', desc: 'User profile page (auth required)' },
          { title: 'Settings', desc: 'Application settings (auth required)' },
          { title: 'Notifications', desc: '500 notifications list (auth required)' },
          { title: 'Search', desc: 'Debounced search with mock API' },
          { title: 'About', desc: 'About this benchmark project' },
        ].map((card) => (
          <div
            key={card.title}
            style={{
              padding: '16px',
              background: 'var(--color-bg-secondary)',
              borderRadius: 'var(--radius)',
              border: '1px solid var(--color-border)',
            }}
          >
            <h3 style={{ marginBottom: '4px' }}>{card.title}</h3>
            <p style={{ color: 'var(--color-text-secondary)', fontSize: '13px' }}>{card.desc}</p>
          </div>
        ))}
      </div>
    </div>
  );
}

// frameworks/vue/apps/router/src/pages/Home.vue
<script setup lang="ts">
</script>

<template>
  <div>
    <div class="page-header">
      <h1>Home</h1>
      <p>Welcome to the Vue Router benchmark application.</p>
    </div>
    <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px">
      <router-link
        v-for="link in [
          { path: '/dashboard', title: 'Dashboard', desc: 'Real-time data widgets' },
          { path: '/table', title: 'Table', desc: 'CRUD data table with 1k rows' },
          { path: '/form', title: 'Form', desc: 'Dynamic form with validation' },
          { path: '/profile', title: 'Profile', desc: 'User profile (auth required)' },
          { path: '/settings', title: 'Settings', desc: 'App settings (auth required)' },
          { path: '/notifications', title: 'Notifications', desc: '500 notification items (auth required)' },
          { path: '/search', title: 'Search', desc: 'Debounced search with API' },
          { path: '/about', title: 'About', desc: 'About this application' },
        ]"
        :key="link.path"
        :to="link.path"
        style="
          padding: 16px;
          background: var(--color-bg-secondary);
          border: 1px solid var(--color-border);
          border-radius: var(--radius);
          text-decoration: none;
        "
      >
        <h3 style="margin-bottom: 4px">{{ link.title }}</h3>
        <p style="font-size: 13px; color: var(--color-text-secondary)">
          {{ link.desc }}
        </p>
      </router-link>
    </div>
  </div>
</template>
