// frameworks/svelte/apps/router/src/pages/Login.svelte
<script lang="ts">
  import { getContext } from 'svelte';
  import { navigate } from 'svelte-routing';
  import { createMockApi } from 'shared-data';

  const api = createMockApi();
  const auth = getContext<{ isAuthenticated: boolean; login: () => void }>('auth');

  let username = $state('demo');
  let password = $state('password');
  let loggingIn = $state(false);
  let error = $state('');

  async function handleLogin() {
    if (!username.trim() || !password.trim()) {
      error = 'Please enter username and password.';
      return;
    }

    loggingIn = true;
    error = '';

    try {
      await api.login(username, password);
      auth.login();
      navigate('/profile', { replace: true });
    } catch {
      error = 'Login failed. Please try again.';
    } finally {
      loggingIn = false;
    }
  }
</script>

<div class="login-page">
  <div class="login-card">
    <h2>Login</h2>

    {#if error}
      <div style="background: var(--color-error); color: white; padding: 8px 12px; border-radius: var(--radius); margin-bottom: 16px; font-size: 13px;">
        {error}
      </div>
    {/if}

    <form onsubmit={(e: Event) => { e.preventDefault(); handleLogin(); }}>
      <div class="form-group" style="margin-bottom: 16px;">
        <label for="username">Username</label>
        <input
          type="text"
          id="username"
          value={username}
          oninput={(e: Event) => username = (e.target as HTMLInputElement).value}
          placeholder="Enter username"
          style="width: 100%;"
        />
      </div>

      <div class="form-group" style="margin-bottom: 16px;">
        <label for="password">Password</label>
        <input
          type="password"
          id="password"
          value={password}
          oninput={(e: Event) => password = (e.target as HTMLInputElement).value}
          placeholder="Enter password"
          style="width: 100%;"
        />
      </div>

      <button type="submit" style="width: 100%;" disabled={loggingIn}>
        {loggingIn ? 'Logging in...' : 'Login'}
      </button>
    </form>

    <p style="margin-top: 16px; text-align: center; font-size: 12px; color: var(--color-text-muted);">
      Use any username/password. This is a mock login.
    </p>
  </div>
</div>

// frameworks/vue/apps/router/src/pages/Login.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useRouter, useRoute } from 'vue-router';
import { login } from '../auth';

const router = useRouter();
const route = useRoute();

const username = ref('admin');
const password = ref('password');
const error = ref('');
const loading = ref(false);

async function handleLogin() {
  error.value = '';
  if (!username.value.trim()) {
    error.value = 'Username is required';
    return;
  }

  loading.value = true;
  // Simulate API call
  await new Promise((r) => setTimeout(r, 50));
  loading.value = false;

  login(username.value);

  const redirect = route.query.redirect as string | undefined;
  router.push(redirect ?? '/');
}
</script>

<template>
  <div class="login-page">
    <div class="login-card">
      <h2>Login</h2>
      <form @submit.prevent="handleLogin">
        <div class="form-group">
          <label for="username">Username</label>
          <input
            id="username"
            v-model="username"
            type="text"
            placeholder="Enter username"
          />
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input
            id="password"
            v-model="password"
            type="password"
            placeholder="Enter password"
          />
        </div>
        <div v-if="error" style="color: var(--color-error); font-size: 13px; margin-bottom: 12px">
          {{ error }}
        </div>
        <button type="submit" :disabled="loading" style="width: 100%">
          {{ loading ? 'Logging in...' : 'Login' }}
        </button>
      </form>
      <p
        style="
          margin-top: 16px;
          font-size: 12px;
          color: var(--color-text-muted);
          text-align: center;
        "
      >
        Use any username and password to log in.
      </p>
    </div>
  </div>
</template>
