// frameworks/angular/apps/router/src/app/pages/profile.component.ts
import { Component } from '@angular/core';
import { AuthService } from '../services/auth.service';

@Component({
  selector: 'app-profile',
  standalone: true,
  template: `
    <div class="page-header">
      <h1>Profile</h1>
      <p>Welcome, {{ authService.user() }}</p>
    </div>
    <div class="widget" style="max-width: 600px; padding: 24px;">
      <div style="margin-bottom: 16px;">
        <strong>Username:</strong> {{ authService.user() }}
      </div>
      <div style="margin-bottom: 16px;">
        <strong>Email:</strong> {{ authService.user() }}&#64;example.com
      </div>
      <div style="margin-bottom: 16px;">
        <strong>Role:</strong> Administrator
      </div>
      <div>
        <strong>Member since:</strong> January 2024
      </div>
    </div>
  `,
})
export class ProfileComponent {
  constructor(public authService: AuthService) {}
}

// frameworks/vue/apps/router/src/pages/Profile.vue
<script setup lang="ts">
import { currentUser } from '../auth';
</script>

<template>
  <div>
    <div class="page-header">
      <h1>Profile</h1>
      <p>Manage your profile settings</p>
    </div>
    <div
      style="
        background: var(--color-bg-secondary);
        border: 1px solid var(--color-border);
        border-radius: var(--radius);
        padding: 24px;
        max-width: 600px;
      "
    >
      <div style="display: flex; align-items: center; gap: 16px; margin-bottom: 24px">
        <div
          style="
            width: 64px;
            height: 64px;
            border-radius: 50%;
            background: var(--color-primary);
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 24px;
            font-weight: 700;
            color: white;
          "
        >
          {{ (currentUser ?? 'U')[0].toUpperCase() }}
        </div>
        <div>
          <h2>{{ currentUser ?? 'User' }}</h2>
          <p style="color: var(--color-text-secondary)">{{ currentUser }}@example.com</p>
        </div>
      </div>
      <div style="display: grid; gap: 12px">
        <div class="form-group">
          <label>Display Name</label>
          <input type="text" :value="currentUser ?? ''" readonly />
        </div>
        <div class="form-group">
          <label>Email</label>
          <input type="email" :value="(currentUser ?? '') + '@example.com'" readonly />
        </div>
        <div class="form-group">
          <label>Role</label>
          <input type="text" value="Administrator" readonly />
        </div>
        <div class="form-group">
          <label>Member Since</label>
          <input type="text" value="2024-01-15" readonly />
        </div>
      </div>
    </div>
  </div>
</template>
