// frameworks/react/apps/router/src/pages/Search.tsx
import { useState, useRef, useEffect } from 'react';
import { createMockApi } from 'shared-data/mock-api';

const api = createMockApi();

interface SearchResult {
  id: number;
  title: string;
  snippet: string;
}

export default function Search() {
  const [query, setQuery] = useState('');
  const [results, setResults] = useState<SearchResult[]>([]);
  const [searching, setSearching] = useState(false);
  const debounceRef = useRef<ReturnType<typeof setTimeout>>();

  useEffect(() => {
    if (!query.trim()) {
      setResults([]);
      return;
    }

    setSearching(true);
    if (debounceRef.current) clearTimeout(debounceRef.current);

    debounceRef.current = setTimeout(() => {
      api.search(query).then((res) => {
        setResults(res.data);
        setSearching(false);
      });
    }, 200);

    return () => {
      if (debounceRef.current) clearTimeout(debounceRef.current);
    };
  }, [query]);

  return (
    <div>
      <div className="page-header">
        <h1>Search</h1>
        <p>Search with 200ms debounced API mock</p>
      </div>
      <div className="search-container">
        <input
          type="text"
          placeholder="Type to search..."
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          style={{ width: '100%' }}
        />
        {searching && (
          <div style={{ padding: '12px 0', color: 'var(--color-text-secondary)' }}>
            Searching...
          </div>
        )}
        <div className="search-results">
          {results.map((r) => (
            <div key={r.id} className="search-result-item">
              <h3>{r.title}</h3>
              <p>{r.snippet}</p>
            </div>
          ))}
        </div>
        {!searching && query.trim() && results.length === 0 && (
          <div style={{ padding: '12px 0', color: 'var(--color-text-secondary)' }}>
            No results found.
          </div>
        )}
      </div>
    </div>
  );
}

// frameworks/vue/apps/router/src/pages/Search.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import { createMockApi } from 'shared-data/mock-api';

const api = createMockApi(50);
const query = ref('');
const results = ref<{ id: number; title: string; snippet: string }[]>([]);
const searching = ref(false);

let debounceTimeout: ReturnType<typeof setTimeout> | null = null;

watch(query, (val) => {
  if (debounceTimeout) clearTimeout(debounceTimeout);
  if (!val.trim()) {
    results.value = [];
    searching.value = false;
    return;
  }
  searching.value = true;
  debounceTimeout = setTimeout(async () => {
    const resp = await api.search(val);
    results.value = resp.data;
    searching.value = false;
  }, 200);
});
</script>

<template>
  <div>
    <div class="page-header">
      <h1>Search</h1>
      <p>Search with 200ms debounced API mock</p>
    </div>
    <div class="search-container">
      <input
        v-model="query"
        type="text"
        placeholder="Type to search..."
        style="width: 100%; font-size: 16px; padding: 10px 14px"
      />
      <div v-if="searching" style="margin-top: 12px; color: var(--color-text-secondary)">
        Searching...
      </div>
      <div v-else-if="query && results.length === 0" style="margin-top: 12px; color: var(--color-text-secondary)">
        No results found.
      </div>
      <div v-else class="search-results">
        <div
          v-for="result in results"
          :key="result.id"
          class="search-result-item"
        >
          <h3>{{ result.title }}</h3>
          <p>{{ result.snippet }}</p>
        </div>
      </div>
    </div>
  </div>
</template>
