// frameworks/vue/apps/nested-tree/src/App.vue
<script setup lang="ts">
import { ref, provide, onMounted } from 'vue';
import Level from './components/Level.vue';

const theme = ref<'light' | 'dark'>('dark');
const counter = ref(0);
const wideMode = ref(false);
const lifecycleCount = ref(0);

provide('theme', theme);
provide('counter', counter);
provide('wideMode', wideMode);

function toggleTheme() {
  theme.value = theme.value === 'dark' ? 'light' : 'dark';
}

function increment() {
  counter.value++;
}

function toggleWideMode() {
  wideMode.value = !wideMode.value;
}

const maxDepth = ref(50);
const computedMaxDepth = () => (wideMode.value ? 10 : maxDepth.value);

// Benchmark hooks
onMounted(() => {
  const hooks = {
    toggleTheme() {
      toggleTheme();
    },
    incrementCounter() {
      increment();
    },
    setCounter(val: number) {
      counter.value = val;
    },
    getCounter() {
      return counter.value;
    },
    getTheme() {
      return theme.value;
    },
    toggleWideMode() {
      toggleWideMode();
    },
    mountComponents(n: number) {
      lifecycleCount.value = n;
    },
    unmountComponents() {
      lifecycleCount.value = 0;
    },
  };
  (window as unknown as Record<string, unknown>).__benchmark = hooks;
});
</script>

<template>
  <div :data-theme="theme" style="padding: 16px">
    <h1 style="margin-bottom: 12px">Vue - Deeply Nested Component Tree</h1>
    <div class="toolbar">
      <button @click="toggleTheme">
        Toggle Theme ({{ theme }})
      </button>
      <button @click="increment">
        Increment ({{ counter }})
      </button>
      <button class="secondary" @click="toggleWideMode">
        {{ wideMode ? 'Normal Mode (depth 50)' : 'Wide Mode (3×10)' }}
      </button>
    </div>
    <div
      style="
        margin-top: 12px;
        border: 1px solid var(--color-border);
        border-radius: var(--radius);
        padding: 8px;
        overflow: auto;
        max-height: calc(100vh - 140px);
      "
    >
      <Level :depth="1" :max-depth="computedMaxDepth()" />
    </div>
    <div id="lifecycle-container">
      <Level
        v-for="i in lifecycleCount"
        :key="i"
        :depth="1"
        :max-depth="3"
      />
    </div>
  </div>
</template>

// frameworks/angular/apps/nested-tree/src/app/app.component.ts
import { Component, signal, OnInit } from '@angular/core';
import { LevelComponent } from './components/level/level.component';
import { ThemeService } from './components/level/theme.service';
import { CounterService } from './components/level/counter.service';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [LevelComponent],
  templateUrl: './app.component.html',
  providers: [ThemeService, CounterService],
})
export class AppComponent implements OnInit {
  readonly wideMode = signal(false);
  readonly maxDepth = 50;
  readonly lifecycleCount = signal(0);
  readonly lifecycleItems = (): number[] => Array.from({ length: this.lifecycleCount() }, (_, i) => i);

  constructor(
    private themeService: ThemeService,
    private counterService: CounterService
  ) {}

  get theme() {
    return this.themeService.theme;
  }

  get counter() {
    return this.counterService.counter;
  }

  ngOnInit(): void {
    this.exposeBenchmarkHooks();
  }

  toggleTheme(): void {
    this.themeService.toggle();
  }

  increment(): void {
    this.counterService.increment();
  }

  toggleWideMode(): void {
    this.wideMode.update((v) => !v);
  }

  get effectiveMaxDepth(): number {
    return this.wideMode() ? 10 : this.maxDepth;
  }

  private exposeBenchmarkHooks(): void {
    const self = this;
    (window as unknown as Record<string, unknown>)['__benchmark'] = {
      toggleTheme() {
        self.toggleTheme();
      },
      incrementCounter() {
        self.increment();
      },
      getCounter() {
        return self.counter();
      },
      getTheme() {
        return self.theme();
      },
      toggleWideMode() {
        self.toggleWideMode();
      },
      mountComponents(n: number) {
        self.lifecycleCount.set(n);
      },
      unmountComponents() {
        self.lifecycleCount.set(0);
      },
    };
  }
}

<div class="nested-tree" [attr.data-theme]="theme()">
  <h1>Angular - Nested Component Tree</h1>

  <div class="toolbar">
    <button (click)="toggleTheme()">
      Toggle Theme ({{ theme() }})
    </button>
    <button (click)="increment()">
      Increment Counter ({{ counter() }})
    </button>
    <button class="secondary" (click)="toggleWideMode()">
      {{ wideMode() ? 'Normal Mode' : 'Wide Mode' }}
    </button>
  </div>

  <app-level
    [depth]="1"
    [maxDepth]="effectiveMaxDepth"
    [wideMode]="wideMode()"
  ></app-level>

  <div id="lifecycle-container">
    @for (i of lifecycleItems(); track i) {
      <app-level [depth]="1" [maxDepth]="3" [wideMode]="false"></app-level>
    }
  </div>
</div>
