// frameworks/react/apps/nested-tree/src/components/Level.tsx
import { useState, useContext } from 'react';
import { ThemeContext, CounterContext } from '../App';

interface LevelProps {
  depth: number;
  maxDepth: number;
  childrenPerLevel: number;
}

export default function Level({ depth, maxDepth, childrenPerLevel }: LevelProps) {
  const theme = useContext(ThemeContext);
  const counter = useContext(CounterContext);
  const [expanded, setExpanded] = useState(true);

  const isLeaf = depth >= maxDepth;

  return (
    <div
      data-level={depth}
      {...(isLeaf ? { 'data-bench-leaf': '' } : {})}
      className={theme}
      style={{
        marginLeft: '12px',
        padding: '4px 8px',
        borderLeft: `2px solid ${theme === 'dark' ? '#334155' : '#cbd5e1'}`,
        fontSize: '13px',
      }}
    >
      <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
        {!isLeaf && (
          <button
            className="secondary"
            style={{ padding: '1px 6px', fontSize: '11px', minWidth: '20px' }}
            onClick={() => setExpanded((e) => !e)}
          >
            {expanded ? '\u25BC' : '\u25B6'}
          </button>
        )}
        <span>
          Level {depth} | Counter: {counter}
        </span>
        {isLeaf && (
          <span
            data-bench-leaf=""
            style={{
              fontFamily: 'var(--font-mono)',
              fontSize: '11px',
              color: 'var(--color-text-muted)',
            }}
          >
            rendered at {performance.now().toFixed(2)}ms
          </span>
        )}
      </div>

      {!isLeaf && expanded && (
        <div>
          {Array.from({ length: childrenPerLevel }, (_, i) => (
            <Level
              key={`${depth + 1}-${i}`}
              depth={depth + 1}
              maxDepth={maxDepth}
              childrenPerLevel={childrenPerLevel}
            />
          ))}
        </div>
      )}
    </div>
  );
}

// frameworks/svelte/apps/nested-tree/src/components/Level.svelte
<script lang="ts">
  import { getContext } from 'svelte';
  import Level from './Level.svelte';

  interface Props {
    depth: number;
    maxDepth: number;
    wideMode: boolean;
  }

  let { depth, maxDepth, wideMode }: Props = $props();

  let expanded = $state(true);

  const themeCtx = getContext<{ readonly value: 'light' | 'dark' }>('theme');
  const counterCtx = getContext<{ readonly value: number }>('counter');

  let theme = $derived(themeCtx.value);
  let counter = $derived(counterCtx.value);

  let isLeaf = $derived(depth >= maxDepth);
  let childCount = $derived(wideMode ? 3 : 1);
  let children = $derived(Array.from({ length: childCount }, (_, i) => i));

  function toggleExpanded() {
    expanded = !expanded;
  }
</script>

<div
  class="level"
  data-level={depth}
  data-bench-leaf={isLeaf ? '' : undefined}
  data-theme={theme}
  style="padding-left: 12px; border-left: 2px solid {theme === 'dark' ? '#334155' : '#cbd5e1'}; margin: 4px 0;"
>
  <div style="display: flex; align-items: center; gap: 8px; padding: 4px 0;">
    {#if !isLeaf}
      <button
        class="secondary"
        style="padding: 2px 6px; font-size: 11px;"
        onclick={toggleExpanded}
      >
        {expanded ? '\u25BC' : '\u25B6'}
      </button>
    {/if}
    <span style="font-size: 13px; color: var(--color-text-secondary);">
      Level {depth}
    </span>
    <span style="font-size: 12px; color: var(--color-text-muted); font-family: var(--font-mono);">
      counter={counter}
    </span>
  </div>

  {#if isLeaf}
    <div
      data-bench-leaf
      style="padding: 4px 0; font-size: 12px; font-family: var(--font-mono); color: var(--color-primary);"
    >
      Leaf @ {performance.now().toFixed(2)}ms
    </div>
  {:else if expanded}
    {#each children as idx (idx)}
      <Level depth={depth + 1} {maxDepth} {wideMode} />
    {/each}
  {/if}
</div>
