// frameworks/react/apps/dashboard/src/components/StatusGrid.tsx
interface StatusGridProps {
  cells: string[];
}

export default function StatusGrid({ cells }: StatusGridProps) {
  return (
    <div className="widget">
      <div className="widget-title">Status Grid</div>
      <div className="status-grid">
        {cells.map((status, i) => (
          <div key={i} className={`status-cell ${status}`} />
        ))}
      </div>
    </div>
  );
}

// frameworks/angular/apps/dashboard/src/app/components/status-grid/status-grid.component.ts
import { Component, input } from '@angular/core';

@Component({
  selector: 'app-status-grid',
  standalone: true,
  template: `
    <div class="widget">
      <div class="widget-title">Status Grid</div>
      <div class="status-grid">
        @for (cell of cells(); track $index) {
          <div class="status-cell" [class]="cell"></div>
        }
      </div>
    </div>
  `,
})
export class StatusGridComponent {
  readonly cells = input.required<('ok' | 'warning' | 'error' | 'idle')[]>();
}
