// frameworks/vue/apps/dashboard/src/components/ChartWidget.vue
<script setup lang="ts">
import { ref, watch, onMounted } from 'vue';
import { renderChart } from 'shared-data/canvas-charts';
import type { ChartConfig } from 'shared-data';

interface Props {
  title: string;
  type: 'line' | 'bar';
  data: number[];
  color?: string;
}

const props = withDefaults(defineProps<Props>(), {
  color: '#3b82f6',
});

const canvasRef = ref<HTMLCanvasElement | null>(null);

function draw() {
  if (!canvasRef.value) return;
  const rect = canvasRef.value.parentElement?.getBoundingClientRect();
  const config: ChartConfig = {
    type: props.type,
    width: rect?.width ?? 300,
    height: rect?.height ? rect.height - 30 : 150,
    data: props.data,
    color: props.color,
    backgroundColor: '#1e293b',
  };
  renderChart(canvasRef.value, config);
}

onMounted(draw);
watch(() => props.data, draw, { deep: true });
watch(() => props.type, draw);
</script>

<template>
  <div class="widget">
    <div class="widget-title">{{ title }}</div>
    <canvas ref="canvasRef"></canvas>
  </div>
</template>

// frameworks/angular/apps/dashboard/src/app/components/chart-widget/chart-widget.component.ts
import {
  Component,
  input,
  effect,
  ElementRef,
  viewChild,
  AfterViewInit,
} from '@angular/core';
import { renderChart, type ChartConfig } from 'shared-data';

@Component({
  selector: 'app-chart-widget',
  standalone: true,
  template: `
    <div class="widget">
      <div class="widget-title">{{ title() }}</div>
      <canvas #chartCanvas></canvas>
    </div>
  `,
})
export class ChartWidgetComponent implements AfterViewInit {
  readonly title = input.required<string>();
  readonly type = input.required<'line' | 'bar'>();
  readonly data = input.required<number[]>();
  readonly color = input('#3b82f6');

  readonly canvasRef = viewChild.required<ElementRef<HTMLCanvasElement>>('chartCanvas');

  private initialized = false;

  constructor() {
    effect(() => {
      const data = this.data();
      if (this.initialized && data && data.length > 0) {
        this.draw(data);
      }
    });
  }

  ngAfterViewInit(): void {
    this.initialized = true;
    const data = this.data();
    if (data && data.length > 0) {
      this.draw(data);
    }
  }

  private draw(data: number[]): void {
    const canvas = this.canvasRef().nativeElement;
    const rect = canvas.parentElement!.getBoundingClientRect();
    const config: ChartConfig = {
      type: this.type(),
      width: Math.max(rect.width - 24, 100),
      height: Math.max(rect.height - 40, 60),
      data,
      color: this.color(),
    };
    renderChart(canvas, config);
  }
}
