// frameworks/react/apps/router/src/pages/Dashboard.tsx
import { useState, useEffect, useRef } from 'react';
import { createMockApi } from 'shared-data/mock-api';
import { renderChart } from 'shared-data/canvas-charts';
import type { ChartConfig } from 'shared-data';
import LoadingSkeleton from '../components/LoadingSkeleton';

const api = createMockApi();
const CHART_COLORS = ['#3b82f6', '#22c55e', '#f59e0b', '#ef4444'];

export default function Dashboard() {
  const [loading, setLoading] = useState(true);
  const [kpis, setKpis] = useState<number[]>([]);
  const [tableRows, setTableRows] = useState<number[][]>([]);
  const canvasRefs = useRef<(HTMLCanvasElement | null)[]>([null, null, null, null]);

  useEffect(() => {
    let cancelled = false;
    api.fetchDashboardData().then((res) => {
      if (cancelled) return;
      setKpis(res.data.kpis);
      setTableRows(res.data.tableRows.slice(0, 20));
      setLoading(false);
    });
    return () => { cancelled = true; };
  }, []);

  // Render charts after data loads
  useEffect(() => {
    if (loading) return;
    canvasRefs.current.forEach((canvas, i) => {
      if (!canvas) return;
      const data = Array.from({ length: 20 }, (_, j) => Math.sin((j + i * 5) * 0.3) * 40 + 50);
      const config: ChartConfig = {
        type: i < 2 ? 'line' : 'bar',
        width: canvas.parentElement?.clientWidth || 300,
        height: 150,
        data,
        color: CHART_COLORS[i],
      };
      renderChart(canvas, config);
    });
  }, [loading]);

  if (loading) return <LoadingSkeleton />;

  return (
    <div>
      <div className="page-header">
        <h1>Dashboard</h1>
        <p>Simplified dashboard with 4 widgets</p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', marginBottom: '16px' }}>
        {kpis.map((value, i) => (
          <div
            key={i}
            style={{
              padding: '16px',
              background: 'var(--color-bg-secondary)',
              borderRadius: 'var(--radius)',
              border: '1px solid var(--color-border)',
              textAlign: 'center',
            }}
          >
            <div style={{ fontSize: '12px', color: 'var(--color-text-secondary)', textTransform: 'uppercase' }}>
              KPI {i + 1}
            </div>
            <div style={{ fontSize: '1.8rem', fontWeight: 700, fontFamily: 'var(--font-mono)' }}>
              {value.toLocaleString()}
            </div>
          </div>
        ))}
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
        {[0, 1, 2, 3].map((i) => (
          <div
            key={i}
            style={{
              padding: '12px',
              background: 'var(--color-bg-secondary)',
              borderRadius: 'var(--radius)',
              border: '1px solid var(--color-border)',
            }}
          >
            <div style={{ fontSize: '12px', color: 'var(--color-text-secondary)', textTransform: 'uppercase', marginBottom: '8px' }}>
              {i < 2 ? 'Line' : 'Bar'} Chart {(i % 2) + 1}
            </div>
            <canvas ref={(el) => { canvasRefs.current[i] = el; }} />
          </div>
        ))}
      </div>
    </div>
  );
}

// frameworks/svelte/apps/router/src/pages/Dashboard.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { createMockApi, createMockWebSocket, renderChart } from 'shared-data';
  import type { DashboardBatch, ChartConfig } from 'shared-data';
  import LoadingSkeleton from '../components/LoadingSkeleton.svelte';

  const api = createMockApi();
  const ws = createMockWebSocket(42);

  let loading = $state(true);
  let running = $state(false);

  // Simplified dashboard: 4 widgets (2 line charts, 1 KPI, 1 status)
  let lineChartData = $state<number[][]>([[], []]);
  let kpiValue = $state(0);
  let kpiDelta = $state(0);
  let statusCells = $state<string[]>(Array.from({ length: 25 }, () => 'idle'));

  let canvas1: HTMLCanvasElement | undefined = $state();
  let canvas2: HTMLCanvasElement | undefined = $state();

  function handleBatch(batch: DashboardBatch) {
    lineChartData = [
      batch.lineCharts[0]?.map((p) => p.value) ?? [],
      batch.lineCharts[1]?.map((p) => p.value) ?? [],
    ];

    if (batch.kpis[0]) {
      kpiValue = batch.kpis[0].value;
      kpiDelta = batch.kpis[0].delta;
    }

    const newStatus = [...statusCells];
    for (const update of batch.statusCells.slice(0, 5)) {
      if (update.cellIndex < 25) {
        newStatus[update.cellIndex] = update.status;
      }
    }
    statusCells = newStatus;
  }

  $effect(() => {
    if (!canvas1 || lineChartData[0].length === 0) return;
    renderChart(canvas1, {
      type: 'line',
      width: canvas1.clientWidth || 300,
      height: canvas1.clientHeight || 180,
      data: lineChartData[0],
      color: '#3b82f6',
    });
  });

  $effect(() => {
    if (!canvas2 || lineChartData[1].length === 0) return;
    renderChart(canvas2, {
      type: 'bar',
      width: canvas2.clientWidth || 300,
      height: canvas2.clientHeight || 180,
      data: lineChartData[1],
      color: '#f59e0b',
    });
  });

  function toggleRunning() {
    if (running) {
      ws.disconnect();
      running = false;
    } else {
      ws.connect(handleBatch);
      ws.setRate(30);
      running = true;
    }
  }

  onMount(async () => {
    await api.fetchDashboardData();
    loading = false;
    return () => {
      ws.disconnect();
    };
  });
</script>

<div class="page-header">
  <h1>Dashboard</h1>
  <p>Simplified real-time dashboard with 4 widgets.</p>
</div>

{#if loading}
  <LoadingSkeleton lines={6} showBlock />
{:else}
  <div style="margin-bottom: 12px;">
    <button onclick={toggleRunning}>
      {running ? 'Stop' : 'Start'}
    </button>
  </div>

  <div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 12px;">
    <div style="background: var(--color-bg-secondary); border: 1px solid var(--color-border); border-radius: var(--radius); padding: 12px;">
      <div style="font-size: 12px; color: var(--color-text-secondary); text-transform: uppercase; margin-bottom: 8px;">Line Chart</div>
      <canvas bind:this={canvas1} style="width: 100%; height: 180px;"></canvas>
    </div>

    <div style="background: var(--color-bg-secondary); border: 1px solid var(--color-border); border-radius: var(--radius); padding: 12px;">
      <div style="font-size: 12px; color: var(--color-text-secondary); text-transform: uppercase; margin-bottom: 8px;">Bar Chart</div>
      <canvas bind:this={canvas2} style="width: 100%; height: 180px;"></canvas>
    </div>

    <div style="background: var(--color-bg-secondary); border: 1px solid var(--color-border); border-radius: var(--radius); padding: 12px; display: flex; flex-direction: column; align-items: center; justify-content: center;">
      <div style="font-size: 12px; color: var(--color-text-secondary); text-transform: uppercase; margin-bottom: 8px;">KPI</div>
      <div style="font-size: 2rem; font-weight: 700; font-family: var(--font-mono);">{kpiValue.toLocaleString()}</div>
      <div style="font-size: 0.9rem; color: {kpiDelta >= 0 ? 'var(--color-success)' : 'var(--color-error)'};">
        {kpiDelta >= 0 ? '\u2191' : '\u2193'} {Math.abs(kpiDelta)}
      </div>
    </div>

    <div style="background: var(--color-bg-secondary); border: 1px solid var(--color-border); border-radius: var(--radius); padding: 12px;">
      <div style="font-size: 12px; color: var(--color-text-secondary); text-transform: uppercase; margin-bottom: 8px;">Status</div>
      <div style="display: grid; grid-template-columns: repeat(5, 1fr); gap: 3px;">
        {#each statusCells as status, i (i)}
          <div
            style="aspect-ratio: 1; border-radius: 2px; background: {
              status === 'ok' ? 'var(--color-success)' :
              status === 'warning' ? 'var(--color-warning)' :
              status === 'error' ? 'var(--color-error)' :
              'var(--color-bg-tertiary)'
            };"
          ></div>
        {/each}
      </div>
    </div>
  </div>
{/if}
