// frameworks/react/apps/router/src/pages/Login.tsx
import { useState, useContext } from 'react';
import { useNavigate, Navigate } from 'react-router-dom';
import { AuthContext } from '../App';

export default function Login() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const { login, isAuthenticated } = useContext(AuthContext);
  const navigate = useNavigate();

  if (isAuthenticated) {
    return <Navigate to="/" replace />;
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    if (!username.trim()) {
      setError('Username is required');
      return;
    }

    setLoading(true);
    try {
      await login(username, password);
      navigate('/profile', { replace: true });
    } catch {
      setError('Login failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="login-page">
      <div className="login-card">
        <h2>Login</h2>
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label htmlFor="login-user">Username</label>
            <input
              id="login-user"
              type="text"
              value={username}
              placeholder="Enter any username"
              onChange={(e) => setUsername(e.target.value)}
            />
          </div>
          <div className="form-group">
            <label htmlFor="login-pass">Password</label>
            <input
              id="login-pass"
              type="password"
              value={password}
              placeholder="Any password"
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>
          {error && (
            <div style={{ color: 'var(--color-error)', fontSize: '13px', marginBottom: '12px' }}>
              {error}
            </div>
          )}
          <button type="submit" disabled={loading} style={{ width: '100%' }}>
            {loading ? 'Logging in...' : 'Login'}
          </button>
        </form>
      </div>
    </div>
  );
}

// frameworks/svelte/apps/router/src/pages/Login.svelte
<script lang="ts">
  import { getContext } from 'svelte';
  import { navigate } from 'svelte-routing';
  import { createMockApi } from 'shared-data';

  const api = createMockApi();
  const auth = getContext<{ isAuthenticated: boolean; login: () => void }>('auth');

  let username = $state('demo');
  let password = $state('password');
  let loggingIn = $state(false);
  let error = $state('');

  async function handleLogin() {
    if (!username.trim() || !password.trim()) {
      error = 'Please enter username and password.';
      return;
    }

    loggingIn = true;
    error = '';

    try {
      await api.login(username, password);
      auth.login();
      navigate('/profile', { replace: true });
    } catch {
      error = 'Login failed. Please try again.';
    } finally {
      loggingIn = false;
    }
  }
</script>

<div class="login-page">
  <div class="login-card">
    <h2>Login</h2>

    {#if error}
      <div style="background: var(--color-error); color: white; padding: 8px 12px; border-radius: var(--radius); margin-bottom: 16px; font-size: 13px;">
        {error}
      </div>
    {/if}

    <form onsubmit={(e: Event) => { e.preventDefault(); handleLogin(); }}>
      <div class="form-group" style="margin-bottom: 16px;">
        <label for="username">Username</label>
        <input
          type="text"
          id="username"
          value={username}
          oninput={(e: Event) => username = (e.target as HTMLInputElement).value}
          placeholder="Enter username"
          style="width: 100%;"
        />
      </div>

      <div class="form-group" style="margin-bottom: 16px;">
        <label for="password">Password</label>
        <input
          type="password"
          id="password"
          value={password}
          oninput={(e: Event) => password = (e.target as HTMLInputElement).value}
          placeholder="Enter password"
          style="width: 100%;"
        />
      </div>

      <button type="submit" style="width: 100%;" disabled={loggingIn}>
        {loggingIn ? 'Logging in...' : 'Login'}
      </button>
    </form>

    <p style="margin-top: 16px; text-align: center; font-size: 12px; color: var(--color-text-muted);">
      Use any username/password. This is a mock login.
    </p>
  </div>
</div>
