// frameworks/vue/apps/router/src/pages/Notifications.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { createMockApi } from 'shared-data/mock-api';
import LoadingSkeleton from '../components/LoadingSkeleton.vue';

const api = createMockApi(50);
const loading = ref(true);
const notifications = ref<{ id: number; message: string; read: boolean }[]>([]);

function toggleRead(id: number) {
  notifications.value = notifications.value.map((n) =>
    n.id === id ? { ...n, read: !n.read } : n
  );
}

function markAllRead() {
  notifications.value = notifications.value.map((n) => ({ ...n, read: true }));
}

const unreadCount = () => notifications.value.filter((n) => !n.read).length;

onMounted(async () => {
  const resp = await api.fetchNotifications(500);
  notifications.value = resp.data;
  loading.value = false;
});
</script>

<template>
  <div>
    <div class="page-header">
      <h1>Notifications</h1>
      <p>{{ unreadCount() }} unread notifications</p>
    </div>

    <LoadingSkeleton v-if="loading" :lines="6" />

    <template v-else>
      <div style="margin-bottom: 12px">
        <button class="secondary" @click="markAllRead">Mark All Read</button>
      </div>
      <div class="notification-list">
        <div
          v-for="notification in notifications"
          :key="notification.id"
          class="notification-item"
          :class="{ unread: !notification.read }"
          style="cursor: pointer"
          @click="toggleRead(notification.id)"
        >
          {{ notification.message }}
        </div>
      </div>
    </template>
  </div>
</template>

// frameworks/svelte/apps/router/src/pages/Notifications.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { createMockApi } from 'shared-data';
  import LoadingSkeleton from '../components/LoadingSkeleton.svelte';

  const api = createMockApi();

  let loading = $state(true);
  let notifications = $state<{ id: number; message: string; read: boolean }[]>([]);

  function toggleRead(id: number) {
    notifications = notifications.map((n) =>
      n.id === id ? { ...n, read: !n.read } : n
    );
  }

  function markAllRead() {
    notifications = notifications.map((n) => ({ ...n, read: true }));
  }

  let unreadCount = $derived(notifications.filter((n) => !n.read).length);

  onMount(async () => {
    const response = await api.fetchNotifications(500);
    notifications = response.data;
    loading = false;
  });
</script>

<div class="page-header">
  <h1>Notifications</h1>
  <p>You have {unreadCount} unread notifications. This page requires authentication.</p>
</div>

{#if loading}
  <LoadingSkeleton lines={8} />
{:else}
  <div style="margin-bottom: 12px;">
    <button class="secondary" onclick={markAllRead}>Mark All Read</button>
  </div>

  <div class="notification-list">
    {#each notifications as notification (notification.id)}
      <div
        class="notification-item"
        class:unread={!notification.read}
        onclick={() => toggleRead(notification.id)}
        role="button"
        tabindex="0"
        onkeydown={(e: KeyboardEvent) => { if (e.key === 'Enter') toggleRead(notification.id); }}
      >
        <div style="display: flex; justify-content: space-between; align-items: center;">
          <span>{notification.message}</span>
          {#if !notification.read}
            <span style="width: 8px; height: 8px; border-radius: 50%; background: var(--color-primary); flex-shrink: 0;"></span>
          {/if}
        </div>
      </div>
    {/each}
  </div>
{/if}
