// frameworks/vue/apps/router/src/pages/Search.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import { createMockApi } from 'shared-data/mock-api';

const api = createMockApi(50);
const query = ref('');
const results = ref<{ id: number; title: string; snippet: string }[]>([]);
const searching = ref(false);

let debounceTimeout: ReturnType<typeof setTimeout> | null = null;

watch(query, (val) => {
  if (debounceTimeout) clearTimeout(debounceTimeout);
  if (!val.trim()) {
    results.value = [];
    searching.value = false;
    return;
  }
  searching.value = true;
  debounceTimeout = setTimeout(async () => {
    const resp = await api.search(val);
    results.value = resp.data;
    searching.value = false;
  }, 200);
});
</script>

<template>
  <div>
    <div class="page-header">
      <h1>Search</h1>
      <p>Search with 200ms debounced API mock</p>
    </div>
    <div class="search-container">
      <input
        v-model="query"
        type="text"
        placeholder="Type to search..."
        style="width: 100%; font-size: 16px; padding: 10px 14px"
      />
      <div v-if="searching" style="margin-top: 12px; color: var(--color-text-secondary)">
        Searching...
      </div>
      <div v-else-if="query && results.length === 0" style="margin-top: 12px; color: var(--color-text-secondary)">
        No results found.
      </div>
      <div v-else class="search-results">
        <div
          v-for="result in results"
          :key="result.id"
          class="search-result-item"
        >
          <h3>{{ result.title }}</h3>
          <p>{{ result.snippet }}</p>
        </div>
      </div>
    </div>
  </div>
</template>

// frameworks/svelte/apps/router/src/pages/Search.svelte
<script lang="ts">
  import { createMockApi } from 'shared-data';

  const api = createMockApi();

  let query = $state('');
  let results = $state<{ id: number; title: string; snippet: string }[]>([]);
  let searching = $state(false);

  let debounceTimer: ReturnType<typeof setTimeout> | undefined;

  function handleInput(e: Event) {
    const value = (e.target as HTMLInputElement).value;
    query = value;

    clearTimeout(debounceTimer);
    if (!value.trim()) {
      results = [];
      searching = false;
      return;
    }

    searching = true;
    debounceTimer = setTimeout(async () => {
      const response = await api.search(value);
      results = response.data;
      searching = false;
    }, 200);
  }
</script>

<div class="page-header">
  <h1>Search</h1>
  <p>Search with 200ms debounced API mock.</p>
</div>

<div class="search-container">
  <input
    type="text"
    placeholder="Search..."
    value={query}
    oninput={handleInput}
    style="width: 100%; padding: 10px 14px; font-size: 16px;"
  />

  {#if searching}
    <div style="margin-top: 16px; color: var(--color-text-secondary);">Searching...</div>
  {/if}

  {#if results.length > 0 && !searching}
    <div class="search-results">
      {#each results as result (result.id)}
        <div class="search-result-item">
          <h3>{result.title}</h3>
          <p>{result.snippet}</p>
        </div>
      {/each}
    </div>
  {/if}

  {#if query.trim() && results.length === 0 && !searching}
    <div style="margin-top: 16px; color: var(--color-text-secondary);">No results found.</div>
  {/if}
</div>
