// frameworks/react/apps/dashboard/src/App.tsx
import { useState, useRef, useEffect, useCallback } from 'react';
import { createMockWebSocket } from 'shared-data/mock-ws';
import type { DashboardBatch, DashboardBenchmarkResult } from 'shared-data';
import Widget from './components/Widget';
import KpiCard from './components/KpiCard';
import StatusGrid from './components/StatusGrid';
import DashboardTable from './components/DashboardTable';

const CHART_COLORS = ['#3b82f6', '#22c55e', '#f59e0b', '#ef4444'];

const SPEED_STEPS = [1, 10, 30, 60];

interface KpiState {
  value: number;
  delta: number;
}

export default function App() {
  const [running, setRunning] = useState(false);
  const [speed, setSpeed] = useState(60);
  const [benchmarkRunning, setBenchmarkRunning] = useState(false);
  const [benchmarkResult, setBenchmarkResult] = useState<DashboardBenchmarkResult | null>(null);

  // Dashboard data state
  const [lineChartData, setLineChartData] = useState<number[][]>(() =>
    Array.from({ length: 4 }, () => Array.from({ length: 100 }, () => 50))
  );
  const [barChartData, setBarChartData] = useState<number[][]>(() =>
    Array.from({ length: 4 }, () => Array.from({ length: 8 }, () => 50))
  );
  const [kpis, setKpis] = useState<KpiState[]>([
    { value: 1250, delta: 0 },
    { value: 8734, delta: 0 },
  ]);
  const [tableData, setTableData] = useState<number[][]>(() =>
    Array.from({ length: 50 }, (_, i) =>
      Array.from({ length: 5 }, (_, j) => (i + 1) * 100 + j)
    )
  );
  const [flashCells, setFlashCells] = useState<Set<string>>(new Set());
  const [statusCells, setStatusCells] = useState<string[]>(() =>
    Array.from({ length: 100 }, () => 'idle')
  );

  const wsRef = useRef(createMockWebSocket());
  const benchmarkResolveRef = useRef<((result: DashboardBenchmarkResult) => void) | null>(null);
  const frameTimesRef = useRef<number[]>([]);
  const frameCountRef = useRef(0);
  const rafIdRef = useRef<number>(0);
  const benchmarkStartRef = useRef(0);

  const handleBatch = useCallback((batch: DashboardBatch) => {
    setLineChartData((prev) =>
      prev.map((chart, i) =>
        batch.lineCharts[i] ? batch.lineCharts[i].map((p) => p.value) : chart
      )
    );
    setBarChartData((prev) =>
      prev.map((chart, i) => (batch.barCharts[i] ? batch.barCharts[i] : chart))
    );
    setKpis((prev) =>
      prev.map((kpi, i) => {
        const update = batch.kpis.find((k) => k.index === i);
        return update ? { value: update.value, delta: update.delta } : kpi;
      })
    );
    setTableData((prev) => {
      const next = prev.map((row) => [...row]);
      const newFlash = new Set<string>();
      for (const update of batch.tableRows) {
        if (update.rowIndex >= 0 && update.rowIndex < next.length) {
          next[update.rowIndex] = update.values;
          for (let c = 0; c < update.values.length; c++) {
            newFlash.add(`${update.rowIndex}-${c}`);
          }
        }
      }
      setFlashCells(newFlash);
      // Clear flash after animation
      setTimeout(() => setFlashCells(new Set()), 300);
      return next;
    });
    setStatusCells((prev) => {
      const next = [...prev];
      for (const update of batch.statusCells) {
        if (update.cellIndex >= 0 && update.cellIndex < next.length) {
          next[update.cellIndex] = update.status;
        }
      }
      return next;
    });
  }, []);

  const startStream = useCallback(() => {
    const ws = wsRef.current;
    ws.connect(handleBatch);
    ws.setRate(speed);
    setRunning(true);
  }, [speed, handleBatch]);

  const stopStream = useCallback(() => {
    wsRef.current.disconnect();
    setRunning(false);
  }, []);

  const handleSpeedChange = useCallback(
    (newSpeed: number) => {
      setSpeed(newSpeed);
      if (wsRef.current.isConnected()) {
        wsRef.current.setRate(newSpeed);
      }
    },
    []
  );

  const runBenchmark = useCallback((): Promise<DashboardBenchmarkResult> => {
    return new Promise((resolve) => {
      benchmarkResolveRef.current = resolve;
      setBenchmarkRunning(true);
      setBenchmarkResult(null);

      // Start the stream at 60/sec
      const ws = wsRef.current;
      if (!ws.isConnected()) {
        ws.connect(handleBatch);
      }
      ws.setRate(60);
      setRunning(true);
      setSpeed(60);

      // Frame counting
      frameTimesRef.current = [];
      frameCountRef.current = 0;
      benchmarkStartRef.current = performance.now();
      let lastFrameTime = performance.now();

      const countFrame = () => {
        const now = performance.now();
        frameTimesRef.current.push(now - lastFrameTime);
        lastFrameTime = now;
        frameCountRef.current++;

        if (now - benchmarkStartRef.current < 10000) {
          rafIdRef.current = requestAnimationFrame(countFrame);
        } else {
          // Benchmark complete
          const frameTimes = frameTimesRef.current;
          const duration = now - benchmarkStartRef.current;
          const expectedFrames = Math.round((duration / 1000) * 60);
          const droppedFrames = Math.max(0, expectedFrames - frameCountRef.current);
          const avgFrameTime =
            frameTimes.reduce((a, b) => a + b, 0) / frameTimes.length;
          const sorted = [...frameTimes].sort((a, b) => a - b);
          const p99FrameTime = sorted[Math.floor(sorted.length * 0.99)] || 0;

          const result: DashboardBenchmarkResult = {
            framesRendered: frameCountRef.current,
            droppedFrames,
            avgFrameTime,
            p99FrameTime,
            duration,
          };

          setBenchmarkRunning(false);
          setBenchmarkResult(result);
          if (benchmarkResolveRef.current) {
            benchmarkResolveRef.current(result);
            benchmarkResolveRef.current = null;
          }
        }
      };

      rafIdRef.current = requestAnimationFrame(countFrame);
    });
  }, [handleBatch]);

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      wsRef.current.disconnect();
      if (rafIdRef.current) cancelAnimationFrame(rafIdRef.current);
    };
  }, []);

  // Benchmark hooks
  useEffect(() => {
    const hooks = {
      start: startStream,
      stop: stopStream,
      setSpeed: handleSpeedChange,
      runBenchmark,
    };
    (window as unknown as Record<string, unknown>).__benchmark = hooks;
    return () => {
      delete (window as unknown as Record<string, unknown>).__benchmark;
    };
  }, [startStream, stopStream, handleSpeedChange, runBenchmark]);

  return (
    <div className="dashboard">
      <h1 style={{ marginBottom: '8px' }}>Real-Time Dashboard</h1>
      <div className="dashboard-controls">
        <button onClick={running ? stopStream : startStream}>
          {running ? 'Stop' : 'Start'}
        </button>
        <div className="speed-slider">
          <label>Speed: {speed}/sec</label>
          <input
            type="range"
            min={0}
            max={SPEED_STEPS.length - 1}
            value={SPEED_STEPS.indexOf(speed)}
            onChange={(e) => handleSpeedChange(SPEED_STEPS[Number(e.target.value)])}
          />
        </div>
        <button
          className="secondary"
          onClick={runBenchmark}
          disabled={benchmarkRunning}
        >
          {benchmarkRunning ? 'Running...' : 'Benchmark (10s)'}
        </button>
        {benchmarkResult && (
          <span style={{ fontSize: '12px', color: 'var(--color-text-secondary)', fontFamily: 'var(--font-mono)' }}>
            Frames: {benchmarkResult.framesRendered} | Dropped: {benchmarkResult.droppedFrames} |
            Avg: {benchmarkResult.avgFrameTime.toFixed(1)}ms | P99: {benchmarkResult.p99FrameTime.toFixed(1)}ms
          </span>
        )}
      </div>

      <div className="dashboard-grid">
        {/* 4 Line Charts */}
        {lineChartData.map((data, i) => (
          <Widget
            key={`line-${i}`}
            title={`Line Chart ${i + 1}`}
            type="line"
            data={data}
            color={CHART_COLORS[i]}
          />
        ))}

        {/* 4 Bar Charts */}
        {barChartData.map((data, i) => (
          <Widget
            key={`bar-${i}`}
            title={`Bar Chart ${i + 1}`}
            type="bar"
            data={data}
            color={CHART_COLORS[i]}
          />
        ))}

        {/* 2 KPI Cards */}
        {kpis.map((kpi, i) => (
          <KpiCard
            key={`kpi-${i}`}
            title={i === 0 ? 'Revenue' : 'Users'}
            value={kpi.value}
            delta={kpi.delta}
          />
        ))}

        {/* 1 Data Table */}
        <DashboardTable rows={tableData} flashCells={flashCells} />

        {/* 1 Status Grid */}
        <StatusGrid cells={statusCells} />
      </div>
    </div>
  );
}

// frameworks/vue/apps/dashboard/src/App.vue
<script setup lang="ts">
import { ref, reactive, onMounted, onUnmounted } from 'vue';
import { createMockWebSocket } from 'shared-data/mock-ws';
import type {
  DashboardBatch,
  DashboardBenchmarkHooks,
  DashboardBenchmarkResult,
  KpiUpdate,
  StatusUpdate,
} from 'shared-data';
import ChartWidget from './components/ChartWidget.vue';
import KpiCard from './components/KpiCard.vue';
import StatusGrid from './components/StatusGrid.vue';
import DashboardTable from './components/DashboardTable.vue';

const ws = createMockWebSocket();
const isRunning = ref(false);
const speed = ref(60);
const benchmarkMode = ref(false);
const benchmarkResult = ref<DashboardBenchmarkResult | null>(null);

// Chart data: 4 line charts, 4 bar charts
const lineChartData = reactive<number[][]>(
  Array.from({ length: 4 }, () => Array.from({ length: 100 }, () => 50))
);
const barChartData = reactive<number[][]>(
  Array.from({ length: 4 }, () => Array.from({ length: 8 }, () => 50))
);

// KPI state
const kpis = reactive<KpiUpdate[]>([
  { index: 0, value: 1250, delta: 0 },
  { index: 1, value: 8734, delta: 0 },
]);

// Table state: 50 rows x 5 columns
const tableData = reactive<number[][]>(
  Array.from({ length: 50 }, (_, i) =>
    Array.from({ length: 5 }, (_, j) => (i + 1) * 100 + j)
  )
);
const flashingCells = ref<Set<string>>(new Set());

// Status grid: 100 cells
const statusCells = reactive<StatusUpdate['status'][]>(
  Array.from({ length: 100 }, () => 'idle' as StatusUpdate['status'])
);

function handleBatch(batch: DashboardBatch) {
  // Update line charts
  for (let i = 0; i < 4; i++) {
    const points = batch.lineCharts[i];
    if (points) {
      lineChartData[i] = points.map((p) => p.value);
    }
  }

  // Update bar charts
  for (let i = 0; i < 4; i++) {
    if (batch.barCharts[i]) {
      barChartData[i] = batch.barCharts[i];
    }
  }

  // Update KPIs
  for (const kpi of batch.kpis) {
    if (kpi.index < kpis.length) {
      kpis[kpi.index] = kpi;
    }
  }

  // Update table rows with flash
  const newFlashing = new Set<string>();
  for (const update of batch.tableRows) {
    if (update.rowIndex < tableData.length) {
      tableData[update.rowIndex] = update.values;
      for (let c = 0; c < update.values.length; c++) {
        newFlashing.add(`${update.rowIndex}-${c}`);
      }
    }
  }
  flashingCells.value = newFlashing;
  setTimeout(() => {
    flashingCells.value = new Set();
  }, 300);

  // Update status cells
  for (const update of batch.statusCells) {
    if (update.cellIndex < statusCells.length) {
      statusCells[update.cellIndex] = update.status;
    }
  }
}

function start() {
  ws.connect(handleBatch);
  ws.setRate(speed.value);
  isRunning.value = true;
}

function stop() {
  ws.disconnect();
  isRunning.value = false;
}

function toggleRunning() {
  if (isRunning.value) {
    stop();
  } else {
    start();
  }
}

function onSpeedChange(event: Event) {
  const val = Number((event.target as HTMLInputElement).value);
  speed.value = val;
  if (isRunning.value) {
    ws.setRate(val);
  }
}

function runBenchmark(): Promise<DashboardBenchmarkResult> {
  return new Promise((resolve) => {
    benchmarkMode.value = true;
    benchmarkResult.value = null;

    const frameTimes: number[] = [];
    let frameCount = 0;
    let lastFrameTime = performance.now();
    let rafId: number;

    function countFrame() {
      const now = performance.now();
      frameTimes.push(now - lastFrameTime);
      lastFrameTime = now;
      frameCount++;
      rafId = requestAnimationFrame(countFrame);
    }

    ws.connect(handleBatch);
    ws.setRate(60);
    isRunning.value = true;
    rafId = requestAnimationFrame(countFrame);

    setTimeout(() => {
      cancelAnimationFrame(rafId);
      ws.disconnect();
      isRunning.value = false;
      benchmarkMode.value = false;

      const sorted = [...frameTimes].sort((a, b) => a - b);
      const avg = frameTimes.reduce((s, t) => s + t, 0) / frameTimes.length;
      const p99 = sorted[Math.floor(sorted.length * 0.99)] || 0;
      const expectedFrames = 10 * 60;
      const dropped = Math.max(0, expectedFrames - frameCount);

      const result: DashboardBenchmarkResult = {
        framesRendered: frameCount,
        droppedFrames: dropped,
        avgFrameTime: Math.round(avg * 100) / 100,
        p99FrameTime: Math.round(p99 * 100) / 100,
        duration: 10000,
      };

      benchmarkResult.value = result;
      resolve(result);
    }, 10000);
  });
}

onMounted(() => {
  const hooks: DashboardBenchmarkHooks = {
    start,
    stop,
    setSpeed(batchesPerSecond: number) {
      speed.value = batchesPerSecond;
      if (isRunning.value) {
        ws.setRate(batchesPerSecond);
      }
    },
    runBenchmark,
  };
  (window as unknown as Record<string, unknown>).__benchmark = hooks;
});

onUnmounted(() => {
  ws.disconnect();
});

const CHART_COLORS = ['#3b82f6', '#22c55e', '#f59e0b', '#ef4444'];
</script>

<template>
  <div class="dashboard">
    <h1 style="margin-bottom: 8px">Vue - Real-Time Dashboard</h1>
    <div class="dashboard-controls">
      <button @click="toggleRunning">
        {{ isRunning ? 'Stop' : 'Start' }}
      </button>
      <div class="speed-slider">
        <label>Speed: {{ speed }} batches/sec</label>
        <input
          type="range"
          min="1"
          max="60"
          :value="speed"
          @input="onSpeedChange"
        />
      </div>
      <button class="secondary" @click="runBenchmark">
        Benchmark (10s)
      </button>
      <span
        v-if="benchmarkResult"
        style="font-size: 12px; font-family: var(--font-mono); color: var(--color-text-secondary)"
      >
        Frames: {{ benchmarkResult.framesRendered }} |
        Dropped: {{ benchmarkResult.droppedFrames }} |
        Avg: {{ benchmarkResult.avgFrameTime }}ms |
        P99: {{ benchmarkResult.p99FrameTime }}ms
      </span>
    </div>

    <div class="dashboard-grid">
      <!-- Row 1: 4 line charts -->
      <ChartWidget
        v-for="i in 4"
        :key="'line-' + i"
        :title="'Line Chart ' + i"
        type="line"
        :data="lineChartData[i - 1]"
        :color="CHART_COLORS[i - 1]"
      />
      <!-- Row 2: 4 bar charts -->
      <ChartWidget
        v-for="i in 4"
        :key="'bar-' + i"
        :title="'Bar Chart ' + i"
        type="bar"
        :data="barChartData[i - 1]"
        :color="CHART_COLORS[i - 1]"
      />
      <!-- Row 3: 2 KPIs, data table, status grid -->
      <div class="widget kpi-card">
        <KpiCard title="Revenue" :value="kpis[0].value" :delta="kpis[0].delta" />
      </div>
      <div class="widget kpi-card">
        <KpiCard title="Users" :value="kpis[1].value" :delta="kpis[1].delta" />
      </div>
      <div class="widget">
        <div class="widget-title">Live Data</div>
        <DashboardTable :data="tableData" :flashing-cells="flashingCells" />
      </div>
      <div class="widget">
        <div class="widget-title">Status Grid</div>
        <StatusGrid :cells="statusCells" />
      </div>
    </div>
  </div>
</template>
