// frameworks/svelte/apps/router/src/pages/Form.svelte
<script lang="ts">
  import { formSchema } from 'shared-data';
  import type { FormField } from 'shared-data';

  let formValues = $state<Record<string, string | boolean>>({});
  let errors = $state<Record<string, string>>({});
  let submitted = $state(false);
  let submitResult = $state<string | null>(null);

  // Initialize defaults
  for (const field of formSchema.fields) {
    if (field.defaultValue !== undefined) {
      formValues[field.name] = field.defaultValue;
    } else if (field.type === 'checkbox') {
      formValues[field.name] = false;
    } else {
      formValues[field.name] = '';
    }
  }

  function isFieldVisible(field: FormField): boolean {
    if (!field.condition) return true;
    return formValues[field.condition.dependsOn] === field.condition.value;
  }

  function validateField(field: FormField, value: string | boolean): string | null {
    if (!isFieldVisible(field)) return null;
    for (const rule of field.validation) {
      const strVal = typeof value === 'boolean' ? '' : (value ?? '');
      if (rule.type === 'required') {
        if (field.type === 'checkbox' && !value) return rule.message;
        else if (field.type !== 'checkbox' && !strVal.trim()) return rule.message;
      }
      if (rule.type === 'minLength' && typeof rule.value === 'number' && strVal.length > 0 && strVal.length < rule.value) return rule.message;
      if (rule.type === 'maxLength' && typeof rule.value === 'number' && strVal.length > rule.value) return rule.message;
      if (rule.type === 'pattern' && typeof rule.value === 'string' && strVal.length > 0 && !new RegExp(rule.value).test(strVal)) return rule.message;
    }
    return null;
  }

  function handleChange(name: string, value: string | boolean) {
    formValues = { ...formValues, [name]: value };
    if (submitted) {
      const field = formSchema.fields.find((f) => f.name === name);
      if (field) {
        const err = validateField(field, value);
        const ne = { ...errors };
        if (err) ne[name] = err;
        else delete ne[name];
        errors = ne;
      }
    }
  }

  function handleBlur(name: string) {
    const field = formSchema.fields.find((f) => f.name === name);
    if (field) {
      const err = validateField(field, formValues[name]);
      const ne = { ...errors };
      if (err) ne[name] = err;
      else delete ne[name];
      errors = ne;
    }
  }

  function handleSubmit() {
    submitted = true;
    const ne: Record<string, string> = {};
    for (const field of formSchema.fields) {
      const err = validateField(field, formValues[field.name]);
      if (err) ne[field.name] = err;
    }
    errors = ne;
    if (Object.keys(ne).length === 0) {
      submitResult = JSON.stringify(formValues, null, 2);
    }
  }

  function handleReset() {
    for (const field of formSchema.fields) {
      if (field.defaultValue !== undefined) formValues[field.name] = field.defaultValue;
      else if (field.type === 'checkbox') formValues[field.name] = false;
      else formValues[field.name] = '';
    }
    formValues = { ...formValues };
    errors = {};
    submitted = false;
    submitResult = null;
  }

  let visibleFields = $derived(formSchema.fields.filter(isFieldVisible));
</script>

<div class="page-header">
  <h1>Form</h1>
  <p>Dynamic form with validation and conditional fields.</p>
</div>

{#if Object.keys(errors).length > 0 && submitted}
  <div class="error-summary">
    <h3>Please fix the following errors:</h3>
    <ul>
      {#each Object.entries(errors) as [field, msg] (field)}
        <li><a href="#field-{field}">{msg}</a></li>
      {/each}
    </ul>
  </div>
{/if}

<form
  class="form-container"
  style="padding: 0;"
  onsubmit={(e: Event) => { e.preventDefault(); handleSubmit(); }}
>
  {#each visibleFields as field (field.name)}
    <div class="form-group" id="field-{field.name}">
      {#if field.type === 'checkbox'}
        <div class="checkbox-group">
          <label>
            <input
              type="checkbox"
              checked={!!formValues[field.name]}
              onchange={(e: Event) => handleChange(field.name, (e.target as HTMLInputElement).checked)}
              onblur={() => handleBlur(field.name)}
            />
            {field.label}
          </label>
        </div>
      {:else if field.type === 'radio'}
        <label>{field.label}</label>
        <div class="radio-group">
          {#each field.options ?? [] as opt (opt.value)}
            <label>
              <input
                type="radio"
                name={field.name}
                value={opt.value}
                checked={formValues[field.name] === opt.value}
                onchange={(e: Event) => handleChange(field.name, (e.target as HTMLInputElement).value)}
                onblur={() => handleBlur(field.name)}
              />
              {opt.label}
            </label>
          {/each}
        </div>
      {:else if field.type === 'select'}
        <label for={field.name}>{field.label}</label>
        <select
          id={field.name}
          value={typeof formValues[field.name] === 'string' ? formValues[field.name] : ''}
          class:invalid={!!errors[field.name]}
          onchange={(e: Event) => handleChange(field.name, (e.target as HTMLSelectElement).value)}
          onblur={() => handleBlur(field.name)}
        >
          <option value="">-- Select --</option>
          {#each field.options ?? [] as opt (opt.value)}
            <option value={opt.value}>{opt.label}</option>
          {/each}
        </select>
      {:else if field.type === 'textarea'}
        <label for={field.name}>{field.label}</label>
        <textarea
          id={field.name}
          placeholder={field.placeholder}
          value={typeof formValues[field.name] === 'string' ? formValues[field.name] : ''}
          class:invalid={!!errors[field.name]}
          oninput={(e: Event) => handleChange(field.name, (e.target as HTMLTextAreaElement).value)}
          onblur={() => handleBlur(field.name)}
        ></textarea>
      {:else if field.type === 'date'}
        <label for={field.name}>{field.label}</label>
        <input
          type="date"
          id={field.name}
          value={typeof formValues[field.name] === 'string' ? formValues[field.name] : ''}
          class:invalid={!!errors[field.name]}
          oninput={(e: Event) => handleChange(field.name, (e.target as HTMLInputElement).value)}
          onblur={() => handleBlur(field.name)}
        />
      {:else if field.type === 'file'}
        <label for={field.name}>{field.label}</label>
        <input
          type="file"
          id={field.name}
          class:invalid={!!errors[field.name]}
          onchange={(e: Event) => {
            const file = (e.target as HTMLInputElement).files?.[0];
            handleChange(field.name, file ? file.name : '');
          }}
          onblur={() => handleBlur(field.name)}
        />
      {:else}
        <label for={field.name}>{field.label}</label>
        <input
          type="text"
          id={field.name}
          placeholder={field.placeholder}
          value={typeof formValues[field.name] === 'string' ? formValues[field.name] : ''}
          class:invalid={!!errors[field.name]}
          oninput={(e: Event) => handleChange(field.name, (e.target as HTMLInputElement).value)}
          onblur={() => handleBlur(field.name)}
        />
      {/if}

      {#if errors[field.name]}
        <div class="error-message">{errors[field.name]}</div>
      {/if}
    </div>
  {/each}

  <div class="form-actions">
    <button type="submit">Submit</button>
    <button type="button" class="secondary" onclick={handleReset}>Reset</button>
  </div>
</form>

{#if submitResult}
  <div class="submit-result">
    <pre>{submitResult}</pre>
  </div>
{/if}

// frameworks/angular/apps/router/src/app/pages/form.component.ts
import { Component, signal, OnInit } from '@angular/core';
import { ReactiveFormsModule, FormGroup, FormControl, FormArray, Validators, ValidatorFn } from '@angular/forms';
import { formSchema, type FormField, type FormSchema } from 'shared-data';

@Component({
  selector: 'app-form-page',
  standalone: true,
  imports: [ReactiveFormsModule],
  template: `
    <div class="page-header">
      <h1>Dynamic Form</h1>
      <p>30-field form with validation</p>
    </div>

    <div class="form-container" style="padding: 0;">
      @if (submitted() && allErrors.length > 0) {
        <div class="error-summary">
          <h3>Please fix the following errors:</h3>
          <ul>
            @for (err of allErrors; track err.field) {
              <li>{{ err.message }}</li>
            }
          </ul>
        </div>
      }

      <form [formGroup]="form" (ngSubmit)="onSubmit()">
        @for (field of schema.fields; track field.name) {
          @if (isFieldVisible(field)) {
            <div class="form-group" [id]="'field-' + field.name">
              @switch (field.type) {
                @case ('text') {
                  <label [for]="field.name">{{ field.label }}</label>
                  <input type="text" [id]="field.name" [formControlName]="field.name" [placeholder]="field.placeholder ?? ''" />
                }
                @case ('select') {
                  <label [for]="field.name">{{ field.label }}</label>
                  <select [id]="field.name" [formControlName]="field.name">
                    <option value="">-- Select --</option>
                    @for (opt of field.options; track opt.value) {
                      <option [value]="opt.value">{{ opt.label }}</option>
                    }
                  </select>
                }
                @case ('checkbox') {
                  <div class="checkbox-group">
                    <label><input type="checkbox" [formControlName]="field.name" /> {{ field.label }}</label>
                  </div>
                }
                @case ('radio') {
                  <label>{{ field.label }}</label>
                  <div class="radio-group">
                    @for (opt of field.options; track opt.value) {
                      <label><input type="radio" [value]="opt.value" [formControlName]="field.name" /> {{ opt.label }}</label>
                    }
                  </div>
                }
                @case ('date') {
                  <label [for]="field.name">{{ field.label }}</label>
                  <input type="date" [id]="field.name" [formControlName]="field.name" />
                }
                @case ('textarea') {
                  <label [for]="field.name">{{ field.label }}</label>
                  <textarea [id]="field.name" [formControlName]="field.name" [placeholder]="field.placeholder ?? ''"></textarea>
                }
                @case ('file') {
                  <label [for]="field.name">{{ field.label }}</label>
                  <input type="file" [id]="field.name" />
                }
              }
            </div>
          }
        }

        <!-- Repeatable groups -->
        <div class="repeatable-section">
          <h3>{{ schema.repeatableGroup.label }} ({{ groups.length }})</h3>
          @for (group of groups.controls; track $index; let i = $index) {
            <div class="repeatable-group" [formGroup]="$any(group)">
              <button type="button" class="remove-btn danger" (click)="removeGroup(i)">Remove</button>
              @for (f of schema.repeatableGroup.fields; track f.name) {
                <div class="form-group">
                  <label>{{ f.label }}</label>
                  @if (f.type === 'textarea') {
                    <textarea [formControlName]="f.name" [placeholder]="f.placeholder ?? ''"></textarea>
                  } @else {
                    <input type="text" [formControlName]="f.name" [placeholder]="f.placeholder ?? ''" />
                  }
                </div>
              }
            </div>
          }
          <button type="button" class="secondary" (click)="addGroup()"
            [disabled]="groups.length >= schema.repeatableGroup.maxCount">
            + Add Reference
          </button>
        </div>

        <div class="form-actions">
          <button type="submit">Submit</button>
          <button type="button" class="secondary" (click)="onReset()">Reset</button>
        </div>
      </form>

      @if (submitResult(); as result) {
        <div class="submit-result"><pre>{{ result }}</pre></div>
      }
    </div>
  `,
})
export class FormPageComponent implements OnInit {
  readonly schema: FormSchema = formSchema;
  form!: FormGroup;
  readonly submitted = signal(false);
  readonly submitResult = signal<string | null>(null);

  get groups(): FormArray {
    return this.form.get('references') as FormArray;
  }

  get allErrors(): { field: string; message: string }[] {
    const errors: { field: string; message: string }[] = [];
    for (const field of this.schema.fields) {
      const ctrl = this.form.get(field.name);
      if (ctrl && ctrl.invalid && (ctrl.touched || this.submitted())) {
        for (const rule of field.validation) {
          const mapping: Record<string, string> = { required: 'required', minLength: 'minlength', maxLength: 'maxlength', pattern: 'pattern' };
          if (ctrl.hasError(mapping[rule.type] || rule.type)) {
            errors.push({ field: field.name, message: rule.message });
          }
        }
      }
    }
    return errors;
  }

  ngOnInit(): void {
    this.buildForm();
  }

  private buildForm(): void {
    const controls: Record<string, FormControl> = {};
    for (const f of this.schema.fields) {
      const vals: ValidatorFn[] = [];
      for (const r of f.validation) {
        switch (r.type) {
          case 'required': vals.push(f.type === 'checkbox' ? Validators.requiredTrue : Validators.required); break;
          case 'minLength': vals.push(Validators.minLength(r.value as number)); break;
          case 'maxLength': vals.push(Validators.maxLength(r.value as number)); break;
          case 'pattern': vals.push(Validators.pattern(r.value as string)); break;
        }
      }
      controls[f.name] = new FormControl(f.defaultValue ?? (f.type === 'checkbox' ? false : ''), vals);
    }
    this.form = new FormGroup({ ...controls, references: new FormArray([]) });
  }

  isFieldVisible(field: FormField): boolean {
    if (!field.condition) return true;
    const dep = this.form.get(field.condition.dependsOn);
    if (!dep) return true;
    return dep.value === field.condition.value;
  }

  addGroup(): void {
    const g: Record<string, FormControl> = {};
    for (const f of this.schema.repeatableGroup.fields) {
      const vals: ValidatorFn[] = [];
      for (const r of f.validation) {
        switch (r.type) {
          case 'required': vals.push(Validators.required); break;
          case 'minLength': vals.push(Validators.minLength(r.value as number)); break;
          case 'maxLength': vals.push(Validators.maxLength(r.value as number)); break;
          case 'pattern': vals.push(Validators.pattern(r.value as string)); break;
        }
      }
      g[f.name] = new FormControl('', vals);
    }
    this.groups.push(new FormGroup(g));
  }

  removeGroup(i: number): void {
    this.groups.removeAt(i);
  }

  onSubmit(): void {
    this.submitted.set(true);
    this.form.markAllAsTouched();
    if (this.form.valid) {
      this.submitResult.set(JSON.stringify(this.form.getRawValue(), null, 2));
    } else {
      this.submitResult.set(null);
    }
  }

  onReset(): void {
    this.form.reset();
    this.groups.clear();
    this.submitted.set(false);
    this.submitResult.set(null);
  }
}
