// frameworks/svelte/apps/router/src/pages/Home.svelte
<script lang="ts">
</script>

<div class="page-header">
  <h1>Home</h1>
  <p>Welcome to the Svelte Benchmark Router App. Navigate using the sidebar.</p>
</div>

<div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin-top: 24px;">
  <div style="background: var(--color-bg-secondary); padding: 16px; border-radius: var(--radius); border: 1px solid var(--color-border);">
    <h3 style="margin-bottom: 8px;">Dashboard</h3>
    <p style="color: var(--color-text-secondary); font-size: 13px;">Real-time data widgets with live charts and KPIs.</p>
  </div>
  <div style="background: var(--color-bg-secondary); padding: 16px; border-radius: var(--radius); border: 1px solid var(--color-border);">
    <h3 style="margin-bottom: 8px;">Table</h3>
    <p style="color: var(--color-text-secondary); font-size: 13px;">CRUD data table with sorting, filtering, and pagination.</p>
  </div>
  <div style="background: var(--color-bg-secondary); padding: 16px; border-radius: var(--radius); border: 1px solid var(--color-border);">
    <h3 style="margin-bottom: 8px;">Form</h3>
    <p style="color: var(--color-text-secondary); font-size: 13px;">Dynamic form with validation, conditional fields, and repeatable groups.</p>
  </div>
</div>

// frameworks/angular/apps/router/src/app/pages/home.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  standalone: true,
  template: `
    <div class="page-header">
      <h1>Home</h1>
      <p>Angular Router Benchmark - Multi-Page Application</p>
    </div>
    <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px;">
      <div class="widget">
        <div class="widget-title">Dashboard</div>
        <p style="color: var(--color-text-secondary);">Real-time dashboard with 4 simplified widgets.</p>
      </div>
      <div class="widget">
        <div class="widget-title">Data Table</div>
        <p style="color: var(--color-text-secondary);">CRUD table with 1,000 rows and full functionality.</p>
      </div>
      <div class="widget">
        <div class="widget-title">Dynamic Form</div>
        <p style="color: var(--color-text-secondary);">30-field dynamic form with validation and repeatable groups.</p>
      </div>
    </div>
  `,
})
export class HomeComponent {}
