// frameworks/vue/apps/router/src/pages/Login.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useRouter, useRoute } from 'vue-router';
import { login } from '../auth';

const router = useRouter();
const route = useRoute();

const username = ref('admin');
const password = ref('password');
const error = ref('');
const loading = ref(false);

async function handleLogin() {
  error.value = '';
  if (!username.value.trim()) {
    error.value = 'Username is required';
    return;
  }

  loading.value = true;
  // Simulate API call
  await new Promise((r) => setTimeout(r, 50));
  loading.value = false;

  login(username.value);

  const redirect = route.query.redirect as string | undefined;
  router.push(redirect ?? '/');
}
</script>

<template>
  <div class="login-page">
    <div class="login-card">
      <h2>Login</h2>
      <form @submit.prevent="handleLogin">
        <div class="form-group">
          <label for="username">Username</label>
          <input
            id="username"
            v-model="username"
            type="text"
            placeholder="Enter username"
          />
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input
            id="password"
            v-model="password"
            type="password"
            placeholder="Enter password"
          />
        </div>
        <div v-if="error" style="color: var(--color-error); font-size: 13px; margin-bottom: 12px">
          {{ error }}
        </div>
        <button type="submit" :disabled="loading" style="width: 100%">
          {{ loading ? 'Logging in...' : 'Login' }}
        </button>
      </form>
      <p
        style="
          margin-top: 16px;
          font-size: 12px;
          color: var(--color-text-muted);
          text-align: center;
        "
      >
        Use any username and password to log in.
      </p>
    </div>
  </div>
</template>

// frameworks/angular/apps/router/src/app/pages/login.component.ts
import { Component, signal } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  template: `
    <div class="login-page">
      <div class="login-card">
        <h2>Login</h2>
        <div class="form-group">
          <label for="username">Username</label>
          <input
            type="text"
            id="username"
            [value]="username()"
            (input)="username.set($any($event.target).value)"
            placeholder="Enter username"
          />
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input
            type="password"
            id="password"
            [value]="password()"
            (input)="password.set($any($event.target).value)"
            placeholder="Enter password"
          />
        </div>
        @if (error()) {
          <p style="color: var(--color-error); margin-bottom: 12px;">{{ error() }}</p>
        }
        <button
          style="width: 100%; margin-top: 8px;"
          (click)="login()"
        >Login</button>
        <p style="color: var(--color-text-muted); font-size: 12px; margin-top: 12px; text-align: center;">
          Enter any username/password to log in.
        </p>
      </div>
    </div>
  `,
})
export class LoginComponent {
  readonly username = signal('');
  readonly password = signal('');
  readonly error = signal('');

  constructor(
    private authService: AuthService,
    private router: Router
  ) {}

  login(): void {
    if (!this.username().trim()) {
      this.error.set('Username is required');
      return;
    }
    this.authService.login(this.username(), this.password());
    this.router.navigate(['/profile']);
  }
}
