// frameworks/svelte/apps/router/src/pages/Search.svelte
<script lang="ts">
  import { createMockApi } from 'shared-data';

  const api = createMockApi();

  let query = $state('');
  let results = $state<{ id: number; title: string; snippet: string }[]>([]);
  let searching = $state(false);

  let debounceTimer: ReturnType<typeof setTimeout> | undefined;

  function handleInput(e: Event) {
    const value = (e.target as HTMLInputElement).value;
    query = value;

    clearTimeout(debounceTimer);
    if (!value.trim()) {
      results = [];
      searching = false;
      return;
    }

    searching = true;
    debounceTimer = setTimeout(async () => {
      const response = await api.search(value);
      results = response.data;
      searching = false;
    }, 200);
  }
</script>

<div class="page-header">
  <h1>Search</h1>
  <p>Search with 200ms debounced API mock.</p>
</div>

<div class="search-container">
  <input
    type="text"
    placeholder="Search..."
    value={query}
    oninput={handleInput}
    style="width: 100%; padding: 10px 14px; font-size: 16px;"
  />

  {#if searching}
    <div style="margin-top: 16px; color: var(--color-text-secondary);">Searching...</div>
  {/if}

  {#if results.length > 0 && !searching}
    <div class="search-results">
      {#each results as result (result.id)}
        <div class="search-result-item">
          <h3>{result.title}</h3>
          <p>{result.snippet}</p>
        </div>
      {/each}
    </div>
  {/if}

  {#if query.trim() && results.length === 0 && !searching}
    <div style="margin-top: 16px; color: var(--color-text-secondary);">No results found.</div>
  {/if}
</div>

// frameworks/angular/apps/router/src/app/pages/search.component.ts
import { Component, signal } from '@angular/core';
import { createMockApi } from 'shared-data';

interface SearchResult {
  id: number;
  title: string;
  snippet: string;
}

@Component({
  selector: 'app-search',
  standalone: true,
  template: `
    <div class="page-header">
      <h1>Search</h1>
      <p>Search with 200ms debounce</p>
    </div>

    <div class="search-container">
      <input
        type="text"
        placeholder="Search..."
        style="width: 100%;"
        [value]="query()"
        (input)="onInput($any($event.target).value)"
      />

      @if (searching()) {
        <p style="color: var(--color-text-secondary); margin-top: 12px;">Searching...</p>
      }

      @if (results().length > 0) {
        <div class="search-results">
          @for (r of results(); track r.id) {
            <div class="search-result-item">
              <h3>{{ r.title }}</h3>
              <p>{{ r.snippet }}</p>
            </div>
          }
        </div>
      }

      @if (!searching() && query() && results().length === 0 && searchPerformed()) {
        <p style="color: var(--color-text-secondary); margin-top: 12px;">No results found.</p>
      }
    </div>
  `,
})
export class SearchComponent {
  readonly query = signal('');
  readonly results = signal<SearchResult[]>([]);
  readonly searching = signal(false);
  readonly searchPerformed = signal(false);

  private debounceTimer: ReturnType<typeof setTimeout> | null = null;
  private api = createMockApi(50);

  onInput(value: string): void {
    this.query.set(value);
    if (this.debounceTimer) clearTimeout(this.debounceTimer);

    if (!value.trim()) {
      this.results.set([]);
      this.searchPerformed.set(false);
      return;
    }

    this.debounceTimer = setTimeout(async () => {
      this.searching.set(true);
      const res = await this.api.search(value);
      this.results.set(res.data);
      this.searching.set(false);
      this.searchPerformed.set(true);
    }, 200);
  }
}
