// frameworks/react/apps/router/src/pages/Settings.tsx
import { useState } from 'react';

export default function Settings() {
  const [notifications, setNotifications] = useState(true);
  const [darkMode, setDarkMode] = useState(true);
  const [language, setLanguage] = useState('en');

  return (
    <div>
      <div className="page-header">
        <h1>Settings</h1>
        <p>Application settings</p>
      </div>
      <div style={{ maxWidth: '500px' }}>
        <div className="form-group">
          <label>
            <input
              type="checkbox"
              checked={notifications}
              onChange={(e) => setNotifications(e.target.checked)}
            />{' '}
            Enable notifications
          </label>
        </div>
        <div className="form-group">
          <label>
            <input
              type="checkbox"
              checked={darkMode}
              onChange={(e) => setDarkMode(e.target.checked)}
            />{' '}
            Dark mode
          </label>
        </div>
        <div className="form-group">
          <label htmlFor="settings-lang">Language</label>
          <select
            id="settings-lang"
            value={language}
            onChange={(e) => setLanguage(e.target.value)}
          >
            <option value="en">English</option>
            <option value="es">Spanish</option>
            <option value="fr">French</option>
            <option value="de">German</option>
            <option value="ja">Japanese</option>
          </select>
        </div>
        <button onClick={() => alert('Settings saved (mock)')}>Save Settings</button>
      </div>
    </div>
  );
}

// frameworks/angular/apps/router/src/app/pages/settings.component.ts
import { Component, signal } from '@angular/core';

@Component({
  selector: 'app-settings',
  standalone: true,
  template: `
    <div class="page-header">
      <h1>Settings</h1>
      <p>Application configuration</p>
    </div>
    <div class="form-container" style="padding: 0;">
      <div class="form-group">
        <label>Display Name</label>
        <input type="text" [value]="displayName()" (input)="displayName.set($any($event.target).value)" />
      </div>
      <div class="form-group">
        <label>Email Notifications</label>
        <div class="checkbox-group">
          <label>
            <input type="checkbox" [checked]="emailNotifs()" (change)="emailNotifs.set(!emailNotifs())" />
            Enable email notifications
          </label>
        </div>
      </div>
      <div class="form-group">
        <label>Theme</label>
        <select [value]="theme()" (change)="theme.set($any($event.target).value)">
          <option value="dark">Dark</option>
          <option value="light">Light</option>
        </select>
      </div>
      <div class="form-group">
        <label>Language</label>
        <select [value]="language()" (change)="language.set($any($event.target).value)">
          <option value="en">English</option>
          <option value="es">Spanish</option>
          <option value="fr">French</option>
          <option value="de">German</option>
        </select>
      </div>
      <div class="form-actions" style="border-top: none; padding-top: 8px;">
        <button (click)="save()">Save Settings</button>
      </div>
      @if (saved()) {
        <p style="color: var(--color-success); margin-top: 8px;">Settings saved!</p>
      }
    </div>
  `,
})
export class SettingsComponent {
  readonly displayName = signal('Admin User');
  readonly emailNotifs = signal(true);
  readonly theme = signal('dark');
  readonly language = signal('en');
  readonly saved = signal(false);

  save(): void {
    this.saved.set(true);
    setTimeout(() => this.saved.set(false), 2000);
  }
}
