// frameworks/react/apps/form/src/components/FormField.tsx
import type { FormField as FormFieldType } from 'shared-data';

interface FormFieldProps {
  field: FormFieldType;
  value: string | boolean;
  error?: string;
  onChange: (name: string, value: string | boolean) => void;
  onBlur: (name: string) => void;
}

export default function FormField({ field, value, error, onChange, onBlur }: FormFieldProps) {
  const id = `field-${field.name}`;
  const hasError = !!error;

  const renderInput = () => {
    switch (field.type) {
      case 'text':
        return (
          <input
            type="text"
            id={id}
            name={field.name}
            value={value as string}
            placeholder={field.placeholder}
            className={hasError ? 'invalid' : ''}
            onChange={(e) => onChange(field.name, e.target.value)}
            onBlur={() => onBlur(field.name)}
          />
        );

      case 'select':
        return (
          <select
            id={id}
            name={field.name}
            value={value as string}
            className={hasError ? 'invalid' : ''}
            onChange={(e) => onChange(field.name, e.target.value)}
            onBlur={() => onBlur(field.name)}
          >
            <option value="">-- Select --</option>
            {field.options?.map((opt) => (
              <option key={opt.value} value={opt.value}>
                {opt.label}
              </option>
            ))}
          </select>
        );

      case 'checkbox':
        return (
          <div className="checkbox-group">
            <label>
              <input
                type="checkbox"
                id={id}
                name={field.name}
                checked={value as boolean}
                onChange={(e) => onChange(field.name, e.target.checked)}
                onBlur={() => onBlur(field.name)}
              />
              {field.label}
            </label>
          </div>
        );

      case 'radio':
        return (
          <div className="radio-group">
            {field.options?.map((opt) => (
              <label key={opt.value}>
                <input
                  type="radio"
                  name={field.name}
                  value={opt.value}
                  checked={value === opt.value}
                  onChange={(e) => onChange(field.name, e.target.value)}
                  onBlur={() => onBlur(field.name)}
                />
                {opt.label}
              </label>
            ))}
          </div>
        );

      case 'date':
        return (
          <input
            type="date"
            id={id}
            name={field.name}
            value={value as string}
            className={hasError ? 'invalid' : ''}
            onChange={(e) => onChange(field.name, e.target.value)}
            onBlur={() => onBlur(field.name)}
          />
        );

      case 'textarea':
        return (
          <textarea
            id={id}
            name={field.name}
            value={value as string}
            placeholder={field.placeholder}
            className={hasError ? 'invalid' : ''}
            onChange={(e) => onChange(field.name, e.target.value)}
            onBlur={() => onBlur(field.name)}
          />
        );

      case 'file':
        return (
          <input
            type="file"
            id={id}
            name={field.name}
            className={hasError ? 'invalid' : ''}
            onChange={(e) => {
              const file = e.target.files?.[0];
              onChange(field.name, file ? file.name : '');
            }}
            onBlur={() => onBlur(field.name)}
          />
        );

      default:
        return null;
    }
  };

  // Checkbox has its own label pattern
  if (field.type === 'checkbox') {
    return (
      <div className="form-group" id={`group-${field.name}`}>
        {renderInput()}
        {hasError && <div className="error-message">{error}</div>}
      </div>
    );
  }

  return (
    <div className="form-group" id={`group-${field.name}`}>
      <label htmlFor={id}>{field.label}</label>
      {renderInput()}
      {hasError && <div className="error-message">{error}</div>}
    </div>
  );
}

// frameworks/angular/apps/form/src/app/components/form-field/form-field.component.ts
import { Component, input } from '@angular/core';
import { ReactiveFormsModule, FormControl } from '@angular/forms';
import type { FormField } from 'shared-data';

@Component({
  selector: 'app-form-field',
  standalone: true,
  imports: [ReactiveFormsModule],
  template: `
    <div class="form-group" [id]="'field-' + field().name">
      @switch (field().type) {
        @case ('text') {
          <label [for]="field().name">{{ field().label }}</label>
          <input
            type="text"
            [id]="field().name"
            [name]="field().name"
            [formControl]="control()"
            [placeholder]="field().placeholder ?? ''"
            [class.invalid]="showError"
          />
        }
        @case ('select') {
          <label [for]="field().name">{{ field().label }}</label>
          <select
            [id]="field().name"
            [name]="field().name"
            [formControl]="control()"
            [class.invalid]="showError"
          >
            <option value="">-- Select --</option>
            @for (opt of field().options; track opt.value) {
              <option [value]="opt.value">{{ opt.label }}</option>
            }
          </select>
        }
        @case ('checkbox') {
          <div class="checkbox-group">
            <label>
              <input
                type="checkbox"
                [id]="field().name"
                [name]="field().name"
                [formControl]="control()"
              />
              {{ field().label }}
            </label>
          </div>
        }
        @case ('radio') {
          <label>{{ field().label }}</label>
          <div class="radio-group">
            @for (opt of field().options; track opt.value) {
              <label>
                <input
                  type="radio"
                  [name]="field().name"
                  [value]="opt.value"
                  [formControl]="control()"
                />
                {{ opt.label }}
              </label>
            }
          </div>
        }
        @case ('date') {
          <label [for]="field().name">{{ field().label }}</label>
          <input
            type="date"
            [id]="field().name"
            [name]="field().name"
            [formControl]="control()"
            [class.invalid]="showError"
          />
        }
        @case ('textarea') {
          <label [for]="field().name">{{ field().label }}</label>
          <textarea
            [id]="field().name"
            [name]="field().name"
            [formControl]="control()"
            [placeholder]="field().placeholder ?? ''"
            [class.invalid]="showError"
          ></textarea>
        }
        @case ('file') {
          <label [for]="field().name">{{ field().label }}</label>
          <input
            type="file"
            [id]="field().name"
            [name]="field().name"
            (change)="onFileChange($event)"
            [class.invalid]="showError"
          />
        }
      }

      @if (showError) {
        @for (rule of field().validation; track rule.type) {
          @if (hasError(rule.type)) {
            <div class="error-message">{{ rule.message }}</div>
          }
        }
      }
    </div>
  `,
})
export class FormFieldComponent {
  readonly field = input.required<FormField>();
  readonly control = input.required<FormControl>();
  readonly showErrors = input(false);

  get showError(): boolean {
    const ctrl = this.control();
    return ctrl.invalid && (ctrl.touched || this.showErrors());
  }

  hasError(ruleType: string): boolean {
    const ctrl = this.control();
    const mapping: Record<string, string> = {
      required: 'required',
      minLength: 'minlength',
      maxLength: 'maxlength',
      pattern: 'pattern',
      custom: 'pattern',
    };
    return ctrl.hasError(mapping[ruleType] || ruleType);
  }

  onFileChange(event: Event): void {
    const file = (event.target as HTMLInputElement).files?.[0];
    this.control().setValue(file?.name ?? '');
    this.control().markAsTouched();
  }
}
