// frameworks/angular/apps/table/src/app/components/data-table/data-table.component.ts
import { Component, input, output } from '@angular/core';
import { type TableRow } from 'shared-data';

@Component({
  selector: 'app-data-table',
  standalone: true,
  templateUrl: './data-table.component.html',
})
export class DataTableComponent {
  readonly rows = input.required<TableRow[]>();
  readonly sortColumn = input<keyof TableRow | null>(null);
  readonly sortDirection = input<'asc' | 'desc' | 'none'>('none');
  readonly selectedIds = input<Set<number>>(new Set());
  readonly editingCell = input<{ rowId: number; column: keyof TableRow } | null>(null);

  readonly sort = output<keyof TableRow>();
  readonly rowClick = output<{ row: TableRow; event: MouseEvent }>();
  readonly startEdit = output<{ rowId: number; column: keyof TableRow }>();
  readonly commitEdit = output<{ rowId: number; column: keyof TableRow; value: string }>();
  readonly cancelEdit = output<void>();

  readonly columns: { key: keyof TableRow; label: string }[] = [
    { key: 'id', label: 'ID' },
    { key: 'firstName', label: 'First Name' },
    { key: 'lastName', label: 'Last Name' },
    { key: 'email', label: 'Email' },
    { key: 'department', label: 'Department' },
    { key: 'salary', label: 'Salary' },
    { key: 'startDate', label: 'Start Date' },
    { key: 'isActive', label: 'Active' },
  ];

  getSortIndicator(column: keyof TableRow): string {
    if (this.sortColumn() !== column) return '\u2195';
    return this.sortDirection() === 'asc' ? '\u2191' : '\u2193';
  }

  isSortActive(column: keyof TableRow): boolean {
    return this.sortColumn() === column && this.sortDirection() !== 'none';
  }

  isSelected(id: number): boolean {
    return this.selectedIds().has(id);
  }

  isEditing(rowId: number, column: keyof TableRow): boolean {
    const cell = this.editingCell();
    return cell !== null && cell.rowId === rowId && cell.column === column;
  }

  onHeaderClick(column: keyof TableRow): void {
    this.sort.emit(column);
  }

  onRowClick(row: TableRow, event: MouseEvent): void {
    this.rowClick.emit({ row, event });
  }

  onCellDblClick(rowId: number, column: keyof TableRow): void {
    this.startEdit.emit({ rowId, column });
  }

  onEditKeydown(event: KeyboardEvent, rowId: number, column: keyof TableRow): void {
    if (event.key === 'Enter') {
      this.commitEdit.emit({
        rowId,
        column,
        value: (event.target as HTMLInputElement).value,
      });
    } else if (event.key === 'Escape') {
      this.cancelEdit.emit();
    }
  }

  formatCell(row: TableRow, column: keyof TableRow): string {
    const val = row[column];
    if (column === 'salary') return '$' + (val as number).toLocaleString();
    if (column === 'isActive') return '';
    return String(val);
  }
}

<div class="table-container">
  <table class="data-table">
    <thead>
      <tr>
        @for (col of columns; track col.key) {
          <th (click)="onHeaderClick(col.key)">
            {{ col.label }}
            <span
              class="sort-indicator"
              [class.active]="isSortActive(col.key)"
            >{{ getSortIndicator(col.key) }}</span>
          </th>
        }
      </tr>
    </thead>
    <tbody>
      @for (row of rows(); track row.id) {
        <tr
          [class.selected]="isSelected(row.id)"
          (click)="onRowClick(row, $event)"
        >
          @for (col of columns; track col.key) {
            @if (isEditing(row.id, col.key)) {
              <td class="editing">
                <input
                  type="text"
                  [value]="row[col.key]"
                  (keydown)="onEditKeydown($event, row.id, col.key)"
                  (blur)="cancelEdit.emit()"
                  autofocus
                />
              </td>
            } @else {
              <td (dblclick)="onCellDblClick(row.id, col.key)">
                @if (col.key === 'isActive') {
                  <span
                    class="active-badge"
                    [class.active]="row.isActive"
                    [class.inactive]="!row.isActive"
                  >{{ row.isActive ? 'Active' : 'Inactive' }}</span>
                } @else {
                  {{ formatCell(row, col.key) }}
                }
              </td>
            }
          }
        </tr>
      }
    </tbody>
  </table>
</div>

// frameworks/vue/apps/table/src/components/DataTable.vue
<script setup lang="ts">
import { ref, nextTick } from 'vue';
import type { TableRow } from 'shared-data';

interface Props {
  rows: TableRow[];
  sortColumn: keyof TableRow | null;
  sortDirection: 'asc' | 'desc' | null;
  selectedIds: Set<number>;
  editingCell: { rowId: number; column: keyof TableRow } | null;
}

const props = defineProps<Props>();

const emit = defineEmits<{
  sort: [column: keyof TableRow];
  'row-click': [rowId: number, event: MouseEvent];
  'cell-double-click': [rowId: number, column: keyof TableRow];
  'cell-edit': [rowId: number, column: keyof TableRow, value: string];
  'edit-cancel': [];
}>();

const editValue = ref('');
const editInputRef = ref<HTMLInputElement | null>(null);

const columns: { key: keyof TableRow; label: string }[] = [
  { key: 'id', label: 'ID' },
  { key: 'firstName', label: 'First Name' },
  { key: 'lastName', label: 'Last Name' },
  { key: 'email', label: 'Email' },
  { key: 'department', label: 'Department' },
  { key: 'salary', label: 'Salary' },
  { key: 'startDate', label: 'Start Date' },
  { key: 'isActive', label: 'Active' },
];

function sortIndicator(column: keyof TableRow): string {
  if (props.sortColumn !== column) return '↕';
  if (props.sortDirection === 'asc') return '↑';
  if (props.sortDirection === 'desc') return '↓';
  return '↕';
}

function onCellDoubleClick(row: TableRow, column: keyof TableRow) {
  editValue.value = String(row[column]);
  emit('cell-double-click', row.id, column);
  nextTick(() => {
    editInputRef.value?.focus();
    editInputRef.value?.select();
  });
}

function onEditKeydown(event: KeyboardEvent, rowId: number, column: keyof TableRow) {
  if (event.key === 'Enter') {
    emit('cell-edit', rowId, column, editValue.value);
  } else if (event.key === 'Escape') {
    emit('edit-cancel');
  }
}

function formatCellValue(row: TableRow, column: keyof TableRow): string {
  const value = row[column];
  if (column === 'salary' && typeof value === 'number') {
    return '$' + value.toLocaleString();
  }
  return String(value);
}
</script>

<template>
  <div class="table-container">
    <table class="data-table">
      <thead>
        <tr>
          <th
            v-for="col in columns"
            :key="col.key"
            @click="emit('sort', col.key)"
          >
            {{ col.label }}
            <span
              class="sort-indicator"
              :class="{ active: sortColumn === col.key }"
            >
              {{ sortIndicator(col.key) }}
            </span>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr
          v-for="row in rows"
          :key="row.id"
          :class="{ selected: selectedIds.has(row.id) }"
          @click="emit('row-click', row.id, $event)"
        >
          <td
            v-for="col in columns"
            :key="col.key"
            :class="{
              editing:
                editingCell?.rowId === row.id && editingCell?.column === col.key,
            }"
            @dblclick="onCellDoubleClick(row, col.key)"
          >
            <template
              v-if="
                editingCell?.rowId === row.id && editingCell?.column === col.key
              "
            >
              <input
                ref="editInputRef"
                v-model="editValue"
                type="text"
                @keydown="onEditKeydown($event, row.id, col.key)"
                @blur="emit('edit-cancel')"
              />
            </template>
            <template v-else-if="col.key === 'isActive'">
              <span
                class="active-badge"
                :class="row.isActive ? 'active' : 'inactive'"
              >
                {{ row.isActive ? 'Active' : 'Inactive' }}
              </span>
            </template>
            <template v-else>
              {{ formatCellValue(row, col.key) }}
            </template>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
