// frameworks/svelte/apps/router/src/components/AuthGuard.svelte
<script lang="ts">
  import { navigate } from 'svelte-routing';
  import type { Snippet } from 'svelte';

  interface Props {
    isAuthenticated: boolean;
    children: Snippet;
  }

  let { isAuthenticated, children }: Props = $props();

  $effect(() => {
    if (!isAuthenticated) {
      navigate('/login', { replace: true });
    }
  });
</script>

{#if isAuthenticated}
  {@render children()}
{/if}

// frameworks/react/apps/router/src/components/AuthGuard.tsx
import { useContext } from 'react';
import { Navigate } from 'react-router-dom';
import { AuthContext } from '../App';

interface AuthGuardProps {
  children: React.ReactNode;
}

export default function AuthGuard({ children }: AuthGuardProps) {
  const { isAuthenticated } = useContext(AuthContext);

  if (!isAuthenticated) {
    return <Navigate to="/login" replace />;
  }

  return <>{children}</>;
}
