// frameworks/vue/apps/router/src/components/LoadingSkeleton.vue
<script setup lang="ts">
interface Props {
  lines?: number;
  showBlock?: boolean;
}

withDefaults(defineProps<Props>(), {
  lines: 5,
  showBlock: true,
});
</script>

<template>
  <div>
    <div v-if="showBlock" class="skeleton skeleton-block"></div>
    <div
      v-for="i in lines"
      :key="i"
      class="skeleton skeleton-line"
      :style="{ width: i === lines ? '60%' : '100%' }"
    ></div>
  </div>
</template>

// frameworks/react/apps/router/src/components/LoadingSkeleton.tsx
export default function LoadingSkeleton() {
  return (
    <div>
      <div className="skeleton skeleton-block" style={{ height: '40px', width: '200px', marginBottom: '16px' }} />
      <div className="skeleton skeleton-line" style={{ width: '100%' }} />
      <div className="skeleton skeleton-line" style={{ width: '90%' }} />
      <div className="skeleton skeleton-line" style={{ width: '75%' }} />
      <div className="skeleton skeleton-block" style={{ marginTop: '16px' }} />
      <div className="skeleton skeleton-line" style={{ width: '85%' }} />
      <div className="skeleton skeleton-line" style={{ width: '60%' }} />
    </div>
  );
}
