// frameworks/angular/apps/router/src/app/components/loading-skeleton/loading-skeleton.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-loading-skeleton',
  standalone: true,
  template: `
    <div>
      <div class="skeleton skeleton-block"></div>
      <div class="skeleton skeleton-line" style="width: 80%;"></div>
      <div class="skeleton skeleton-line" style="width: 60%;"></div>
      <div class="skeleton skeleton-line" style="width: 90%;"></div>
      <div class="skeleton skeleton-line" style="width: 50%;"></div>
    </div>
  `,
})
export class LoadingSkeletonComponent {}

// frameworks/react/apps/router/src/components/LoadingSkeleton.tsx
export default function LoadingSkeleton() {
  return (
    <div>
      <div className="skeleton skeleton-block" style={{ height: '40px', width: '200px', marginBottom: '16px' }} />
      <div className="skeleton skeleton-line" style={{ width: '100%' }} />
      <div className="skeleton skeleton-line" style={{ width: '90%' }} />
      <div className="skeleton skeleton-line" style={{ width: '75%' }} />
      <div className="skeleton skeleton-block" style={{ marginTop: '16px' }} />
      <div className="skeleton skeleton-line" style={{ width: '85%' }} />
      <div className="skeleton skeleton-line" style={{ width: '60%' }} />
    </div>
  );
}
